= The Chosen One

进退两难。我回头看看，明知早已放弃了所有退路。

寂清的夜晚，呼吸格外重而且闷。**危险**，亲爱的，我对你并不陌生。我曾经循着月光，投足于百丈山脊，稍有不慎，就会被罡风击落，魂销骨散；我曾经历陷重围，七八位可敬的敌手个个亮出爪牙，泛着泠泠寒光；我曾经与巨人一族长年作战，竟赢得他们的尊重和永恒的荣誉——累累伤疤。

是的，巨人并非上古神话，真实存在于这个冷酷无情的世界。而我则是此修罗场上的老兵，彼红尘浮世中的倦客。

我的听力如神。隔着几间屋子，守夜人的鼾声均匀安定，很好，在你的职责上酣睡，于我有利；窗外檐下雏燕醒了，迷迷糊糊中啁啁找妈妈，很好；不止我一个清醒，窸窸窣窣的高频声暗示着饥饿的老鼠也发现了目标，而此时的我羞愧无力，只能向**全知全能全善**的造主祈祷。
// https://en.wikipedia.org/wiki/Problem_of_evil 全知全能全善
// The problem of evil acutely applies to monotheistic religions such as Christianity, Islam, and Judaism that believe in a monotheistic God who is omnipotent, omniscient and omnibenevolent;[10][11] 

七是神圣的数字。上帝花了六天创造天地万物和我族，在第七天休息。虽然不明白万能的上帝为何也要休息，，，**亵渎！**神的意志岂是我等可以测度的？七是完全的数目，七是四加三而成；四代表世人，三代表神。人和神连起来，就是完全的！六是邪恶的，666是主的敌人撒旦的象征，而六是三加三而成的，神和神连起来？噢，我好像多明白了点什么。。。

吱，一声凄厉的惨叫传来，黑暗中的我和其它几个同伴同时转头，只见一个橘色的身影重新溶化成夜。那是附近咖啡馆豢养的橘猫，谋杀老鼠的冷血机器。燕子一家安全了！万能的主回应弹我的祷告！是的，赞美上帝，一切归美于祂。和捕鼠的胖猫无关。

顺便说下，这胖猫并不爱吃鼠辈，它会把晚上的战利品堆成小山，明早赶着叼去讨好它的主子，奴隶性！天生的奴才贱骨！

我的同胞们又沉沉睡去，留下出离愤怒的鄙人。我的同胞猥琐懒惰，早已忘记对我族造主的义务。哀其不幸，怒其不争！和平安宁的生活扼杀了他们的血性、理想，他们变得犹豫、软弱、不思进取，甚至在这神之梯大会上也只想呼呼大睡，拖到结束。

神之梯，以前的我听到这古老传说也高傲地扭过鼻头，不屑一顾。那时的我是多么无知呀！

面对我族的日益堕落，唯一的天主派遣他的儿子传达福音。听听圣子的教诲吧，愚昧的世人！他牺牲了自己宝贵生命来唤醒你们这群迷途的羔羊！他说，“凡喝这世间水的，还要再渴。人若喝我所赐的水，就永远不渴。我所赐的水要在他里头成为泉源，直涌到永生。”
// “圣训”来源于现代标点和合本，为了上下文加上“世间”二字

我心中的一切疑惑、俳徊、痛苦如冰雪在烈日下融化，他在我心中种下了一眼泉！从此以后我再也不用整天胡思乱想，比如，既然他是圣子，他仅仅献出生物学上的生命为人类洗涮罪恶也就显得没有那么了不起，况且他还能复活的。。。看，一旦放弃思考，我变得愉快又虔诚！

记载我族历史的圣经中有一段古老传说：弥赛亚将会降临，拯救被神挑中的子民。被神祝福的，我族称为选民。选民自然是人类中最优秀的，他们也不得不接受自己的使命：支配劣等种族。

神喜欢考验世人，虽然祂是全知的，理论上应该。。。神是伟大的，自己的先知与儿子也反复考验，，，当然在考验之前，全知的祂早已知道结果，咳咳，想来考验是一场体育运动。。。吧。

