= The Chosen One

进退两难。我回头看看，明知早已放弃了所有退路。

寂清的夜晚，呼吸格外重而且闷。**危险**，亲爱的，我对你并不陌生。我曾经循着月光，投足于百丈山脊，稍有不慎，就会被罡风击落，魂销骨散；我曾经历陷重围，七八位可敬的敌手个个亮出爪牙，泛着泠泠寒光；我曾经与巨人一族长年作战，竟赢得他们的尊重和永恒的荣誉——累累伤疤。

是的，巨人并非上古神话，真实存在于这个冷酷无情的世界。而我则是此修罗场上的老兵，彼红尘浮世中的倦客。

我的听力如神。隔着几间屋子，守夜人的鼾声均匀安定，很好，在你的职责上酣睡，于我有利；窗外檐下雏燕醒了，迷迷糊糊中啁啁找妈妈，很好；不止我一个清醒，窸窸窣窣的高频声暗示着饥饿的老鼠也发现了目标，而此时的我羞愧无力，只能向**全知全能全善**的造主祈祷。
// https://en.wikipedia.org/wiki/Problem_of_evil 全知全能全善
// The problem of evil acutely applies to monotheistic religions such as Christianity, Islam, and Judaism that believe in a monotheistic God who is omnipotent, omniscient and omnibenevolent;[10][11] 

七是神圣的数字。上帝花了六天创造天地万物和我族，在第七天休息。虽然不明白万能的上帝为何也要休息，，，**亵渎！**神的意志岂是我等可以测度的？七是完全的数目，七是四加三而成；四代表世人，三代表神。人和神连起来，就是完全的！六是邪恶的，666是主的敌人撒旦的象征，而六是三加三而成的，神和神连起来？噢，我好像多明白了点什么。。。

吱，一声凄厉的惨叫传来，黑暗中的我和其它几个同伴同时转头，只见一个橘色的身影重新溶化成夜。那是附近咖啡馆豢养的橘猫，谋杀老鼠的冷血机器。燕子一家安全了！万能的主回应弹我的祷告！是的，赞美上帝，一切归美于祂。和捕鼠的胖猫无关。

顺便说下，这胖猫并不爱吃鼠辈，它会把晚上的战利品堆成小山，明早赶着叼去讨好它的主子。奴隶性！天生的奴才！跪久了再也站不起来了吗？！

我的同胞们又沉沉睡去，留下出离愤怒的鄙人。他们猥琐懒惰，早已忘记对我族造主的义务。哀其不幸，怒其不争！和平安宁的生活扼杀了他们的血性、理想，他们变得犹豫、软弱、不思进取，甚至在这神之梯大会上也只想呼呼大睡，拖到结束。

神之梯，以前的我听到这古老传说也高傲地扭过鼻头，不屑一顾。那时的我是多么无知呀！

面对我族的日益堕落，唯一的天主派遣他的儿子传达福音。听听圣子的教诲吧，愚昧的世人！他牺牲了自己宝贵生命来唤醒你们这群迷途的羔羊！他说，“凡喝世间水的，还要再渴。人若喝我所赐的水，就永远不渴。我所赐的水要在他里头成为泉源，直涌到永生。”
// “圣训”来源于现代标点和合本，为了上下文加上“世间”二字

我心中的一切疑惑、俳徊、痛苦如冰雪在烈日下融化，他在我心中种下了一眼泉！从此以后我再也不用整天胡思乱想，比如，既然他是圣子，他仅仅献出生物学上的生命为人类洗涮罪恶也就显得没有那么了不起，况且他还能复活的。。。看，一旦放弃思考，我变得愉快又虔诚！

记载我族历史的圣经有一段古老传说：弥赛亚将会降临，拯救被神挑中的子民。被神祝福的，我族称为选民。选民自然是人类中最优秀的，他们也不得不接受自己的使命：支配劣等种族。

神喜欢考验世人，虽然祂是全知的，理论上应该。。。神是伟大的，自己的先知与儿子也反复考验，，，当然在考验之前，全知的祂早已知道结果，咳咳，想来考验是一场体育运动。。。吧。

巨人有一万种可怕，最可怕的却让人意外。按说光靠他们的体形与力量，我族就疲于应付，可他们竟会妖法。

我现在就站在巨人妖法构建的机关房前。我族崇尚科学，可惜科学还对付不了奇术。龙从云，妖乘风，巨人蓄养机械怪兽，常常祭起妖法，驾上风砂，肆无忌惮地在路上逍遥。

我族竟日劳作，未遑宁居，巨人遊荡燕处，不劳而获。我族饥寒交迫，巨人纸醉金迷，他们的美食堆满，像大风刮来一般容易。妖法\...我喉头咕噜咕噜作响，妖法让生活如此便利，他们一定经不起诱惑！他们一定是靠把灵魂出卖给魔鬼，才习得魔法的！一定是！

记得下午的时候，天上的乌云向我招手，用惯有的忧郁告诫：据他观察，巨人已掌握了云之奥义，甚至还刻意凌驾在他的头上。

依我看，虽然可怕，妖术并非不可战胜。巨人无敌天下靠得是另一项惊天动地的魔法，它令宇宙中的一切文明闻风丧胆，是呀，巨人竟可以随时随地撒谎。

站在机关房前，我感到孤独渺小。回想过去六天的经历，宛如梦魇。此时的月光如水，铺在地砖上，白茫茫的，更添寒意。作为巨人的俘虏，是的，说出来令人不齿，我又一次中了美人计！
// 写得过于明白了？或者放在开头

六天前，一位狱友奔来相告，说他无意中窥破了一个大秘密。我们这才知道典狱长将凤凰藏入了新修成的机关房。

一直以来，囚徒如我都将机关房当成花式杀人室。巨人也不避人，将各种不可思议、花样百出的机关摆入，等着我们经不起诱惑，自行送死。巨人们如此了解人类，超出了我的预料。“好奇杀死猫”，人类亦如是。不久某位狱友终究勘不破XX，乘夜色溜了进去，之后传来的阵阵惨叫。。。光想起就让我毛骨悚然。

他的动静叫醒了守夜巨人，巨人走来，哈哈大笑，将可怜的囚犯捞出。这举动迷惑了我们，考虑到必须时时用最大的恶意惴测巨人，最终，人类的靠者、牧羊人、先知、区区在下得到了唯一合理的解释：巨人之所以救了人类，并非善意，而是借机告诉我们，生死富贵荣辱完全由他们控引。果然，这之后，狱友频频倒向了巨人，成为毫无廉耻的汉奸、卖国贼！虽然狱友手上有什么了不起的国可以卖，我尚未想到，但\...打倒汉奸、卖国贼需要理智吗？！烧\...烧死他们，全家，婴儿也不能\...正义的爱国者万岁万岁万万岁！

正因为如此，六天前的我正打算告诫同侪：不要受诱惑，软弱的**sinner**，那凤凰肉一定是魔鬼之血幻化而成！就在那时，一道光笼罩住我，就算一亿颗太阳同时发出光热，也比不上那光！那道光照亮了我的内心，吹走了心中一切阴霾，祂无比温暖，无比庄严，无比仁慈，却又无比严厉；祂告诉我，这是祂为人类设下的考验。于是我将福音转达给伙伴们，唯一的真神喻示，谁能够在七天内破解所有机关，偷到凤凰就将成为神的选民，The Chosen One！（当然，全知的神早已知晓结果，说了，所谓考验，很像体育运动。）

然而，谁能想到那些怕死鬼被机关房吓破了胆子，不敢尝试，反而质疑起我来。他们问我要证据，问我为何知道那是上帝的声音？而非撒旦的引诱？

What the fuck！问先知要证据？我们搞得还是宗教吗？我告诉他们，那就是上帝的声音，无可质疑，就像摩西听到的十诫，耶稣知道他是上帝之子，洪秀全做梦得知他是耶稣的二弟，杨秀清是三弟\...够了！不可质疑，不可分辩，神的意志岂容尔等妄议！

于是软弱者干脆说，他反正不想成为选民，就不尝试了。妈的，神叫你们来，你们不来就得死！你以为宗教像女人一样，想上就上？你以为宗教是请客吃饭？记得古老的东方有一条谚语：上贼船容易下\...啊呸，魔鬼的诱惑让我差点想歪了，该死该死！

所以只有我一人孤零零站在最后一道机关面前，距离凤凰肉仅仅三米。可这三米比天边爱情还要遥远。过去六天，我拼尽全身一切力量，一切血肉，甚至一夜头白，痛苦得将我的头发生生拔出，绞尽脑汁，终于将前面的机关一一破解，来到了最后的真理大厅。

可人力有时而穷，最后一道机关我试验了七七四十九种方法，用尽了八九七十二番变化，也无从下手。我终于多明白了一个真理，人力再伟大，在万能的主面前连尘埃都算不上。

抬头看看月亮，时间也背叛了我，最多只剩一刻钟，难道\...难道说我并非传说中的选民，不配被弥赛亚拯救？不！！！这一定是对我的考验，像好莱坞电影那样，一定要等到最后一秒才能得救。

然而软弱的我终于忍不住在心中大声呼喊，万能的主啊，难道你要抛弃你最忠实的奴仆而不顾？？！！伊曼纽尔！伊曼纽尔！！！

清晰无比的声音在我心中流淌起来，涛声如雷。God only helps those who help themselves，天助自助者，天助自助者！！！上帝的响应如此洪亮，启示了无知的我。原来上帝无需做任何事，看着他的信徒挣扎就可以了。该死的魔鬼又一次诱惑了我，上帝的意思明明是：祂当然不会帮你，但如果你靠自己的努力侥幸成功，你可以把功劳都归因到祂的身上！

来不及细细辨析启示，我忽然想到破解机关的办法，是啊，任何人都不可能通过这机关，这没有错，但谁说不能绕过它？这机关用木头草草制成，只要打一个洞穿出，像壁虎一样游到另一端，再破壁而入不就可以了嘛？！

想到这里，怀着对上帝无限的感激，我伸出双手，运起九阴白骨爪，狠狠向墙壁抓去。。。