= 晚餐

:docdate: 2017-9-30 ——

[, 上古神话]
""
在东海的极东处，有两棵桑树，枝葉交缠，互相扶持，不知生长了多少年，也不知它们有多高。我们只知道雲霓也无法拂到它的下枝。在洪荒时代，九个太阳居住于下枝，一个太阳栖息于上枝。每天凌晨，太阳之母，东夷女神羲和将逐一为每个儿子沐浴，再从树顶上驾起日车，载驰着十兄弟照耀世间，给人类带来光明与希望。
""

“日本根本不是扶桑。”繁西认真的劲头上来，死活不同意和曦的说法。

看着繁西认真的傻样，和曦捂着肚子偷笑，有意逗他，“小学生懂什么？王维王摩诘，唐朝大诗人你总听说过吧？他写过一首诗《送秘书晁监还日本国》。”

“想你小学生也不懂什么叫秘书晁监。来来来，姐姐教你个乖，唐朝有中央机关叫秘书省，掌管图书经籍，秘书省的长官称为秘书监。闲差，大大的闲差，sinecure，拉丁语，哈，小学生哪里懂。当时秘书监由晁某担任，所以按唐人习惯尊称为秘书晁监。”

“他其实是个来中国学习的日本人，遣唐使，叫什么来着\...？不准笑！不叫晁盖！对了，叫阿倍仲麻吕，好像。等他看厌长安名花一万万之后，准备回国，上至唐明皇，下至公卿巨宦纷纷写诗相赠，不入流的诗人杜甫都不配为他写诗吟别！”

“扯远了，王维诗里写了‘乡树扶桑外，主人孤岛中’。说明唐人已认定扶桑即日本，日本即扶桑。别不服，唐诗里还有两千多处证据，姐姐一一引用，怕只怕压死你！李白也写诗送过晁某，那首是千古绝响，可惜我的对面坐的小学生，和他谈不了人话。”

小学生被唐诗中两千多处证据諕住，吓得转了攻击方向，依然不服。他告诉和曦，倭人是世界上最崇拜真理正义的人类。唐时中国是世界帝国，开边开到中亚斯坦，杀人如麻，尸积成山。倭人怎能不羡慕如此天朝上国？穷人攀附富人总需沾亲带故，他们在中国典籍中搜刮，指着富士山对唐人说那就是天朝文献中的扶桑，连发音都很像。唐人怜惜这群把床单挖个洞套头，一夫多妻，不远“万里”而来的夷狄，胡乱承认罢了。自黑船来袭之后，倭人立刻明白世界大势已变，劫略屠杀才是新的真理与正义，于是他们患上集团失忆症，富士山神山依旧，只是扶桑是什么？我们的祖先是神武天皇，有祖传破刀烂镜子为证。支那人大大的狡猾，以前骗我们说神武天皇传自吴太伯，富士山就是扶桑，现在统统要拨乱反正。
// 繁西的历史观

“按照我的理论，扶桑不是日本，也不是最近几百年大家乱猜的阿米狗墨西哥。”繁西公布**独家研究成果**，“我以为，扶桑最大的可能是新西兰。”

“新疆，西宁，兰川？”

滚！

在星期六上海滩的月夜，伴着小提琴师身姿的摇曳，一边吃着期盼已久的烛光晚餐，一边争辩着对社会人生毫无益处、意义的话题，说明\...说明用餐的二人是一对相爱至深的情侣。

扶桑之前争论温泉，温泉之前和牛，和牛争辩不过因为埋头用餐的和曦随口问起，“牛排怎样？”

出南京城花了一小时，路上两个半小时，在上海又堵了一小时，比预计迟到了两小时，开车的和曦又累又饿，然而\...眼前的坏蛋一点也不体恤我！

都和他说是米其林三星餐厅，有着穿要求，可他呢？像平常一样穿件破T恤就来了。和曦盯着繁西T-Shirt上的"I'm Not Antisocial I'm Anti-Stupid"看。

混蛋！繁西就是个毛孩子，好歹你也是上市公司CEO，整天这么cynical的。你是有意穿来挑衅的吧！这世上固然都是蠢货势利眼，可打破他们的幻梦才是犯罪！

想起昨晚被繁西捉上床时，他穿的好像是"Don't say maybe if you want to say no"，见鬼，你又不缺性伴，何必与我们女人过不去！

繁西，你这种东西怎么会有女朋友的！和曦生气了，指责男友是懒鬼，不肯履行男友的义务，陪她去日本泡温泉。繁西不耐烦的嘟囔，明明去年去过四、五次了。汤山也有温泉，随时可以去。

废话，去年的事情还能作数吗？自从去年年底的那次旅游，你就再也不陪我出国玩了，甚至连国内稍远的地方也不去了。

日本的温泉有雪猴子可以看，汤山的温泉看你这只猴嘛？和曦质问。

繁西翻起白眼，自告奋勇要求担任温泉猴子一角，在和曦泡汤时。只见他鼓起腮帮，猴头猴脑地挠痒，嘎吱嘎吱吊嗓子乱叫，自作聪明地举起双臂攀住想像中的香蕉树，还用双拳愤怒地砸胸口。讨厌，猴子与猩猩都分不清！

和曦本来已经笑了，可惜身后的两个提琴师小姑娘笑出了声，误了曲调。

繁西意犹未尽，“如果泡温泉的和曦欣赏红彤彤的猴屁股，那不如看我的。”不知从何处学来梨花诗，繁西吟道：“我的屁股/是全天下/最好看的屁股。红润、白腻、圆润，长期锻炼自然紧致挺翘，难怪你昨晚抱着它啃了好长时间，毛都啃荒了，你是识货的。”

去死，死啦死啦滴！和曦愤怒地瞪了小提琴师，繁西是我的，你们红什么脸？就算在想像里，他的屁股也只属我一人！

繁西真讨嫌，闺房里的事情到处说，包间里明明有外人。和曦想了想，又说，“你也知道我不能去汤山的，不吉利！”

“南京本地的民俗学家/诗人/小说家考证，汤山即是当年羿皇射落九个太阳的地方，时间在五帝之一的尧时。据说坠下的太阳钻入大地，自此汤泉喷涌不止。当地还能找到宋时土人修建的庙宇纪念为民除害\...呸，多管闲事多吃屁的后羿。”

和曦指着自己的鼻子，“你有没想过为何从未见我去汤山？连顺路经过都没有，宁愿绕道？你难道不知道九个太阳是谁的儿子？最适合和曦的温泉在日本，和曦应该去日本玩，多多滴！扶桑女神爱回家！爱回家洗她仅存的傻儿子繁西！繁西你这么不要脸不害臊，姐姐最后警告你一遍，温泉里严禁性交，太干，插不进来！”

“牛排怎样？”繁西心不在焉，疑惑地随着和曦重复，仿佛听不懂这简单的四个字。“还好吧。”回过神的繁西草草答道，抓起一片面包，去蘸前餐上装点的鱼子酱。

大部分人类在几十年还算“漫长”的生命中都会感染如下疾病：突然兴起，花费无数时间、精力、金钱为所爱的人制作菜肴，只盼着心上人说一句“好吃”，接着狼吞虎咽，最好连盘子也一并吞下去。

所以和曦愤怒起来，体会到无数母亲、妻子所经历过的心酸里程，明明费了这么一番辛苦，为何你对我的一片苦心如此漫不经心，一点也未感动，**难道是因为不够爱我？**
// 希望越大失望越大，心里企盼与现实差距，心理强烈失望

仔细想来和曦并未付出时间现力，似乎没有资格要求上述回报。然而在我们的时代，金钱等于爱情，金钱的多少相当于爱情的强烈程度，这是比人权宣言更加不言自明的真理。

和曦抢过繁西手中产自伊朗的鱼子酱，将黑色美梦一股脑倒在生蚝上，恶狠狠地白眼翻他，气鼓鼓地一口吞下。继续白眼，用银勺刮下最后的鱼子，拌着海胆嚼了。见鬼，十八道菜的大餐好是好，只是每道菜的份量不足一口，尤其在盛怒之下，什么味道也没留下。

“对着我眼前的美人哪有人还有心思品味牛排的？”繁西懒懒自辩，手伸到台布之下轻轻捉住和曦的右脚，悄悄除了鞋袜，拉到大腿面上，细细玩了起来。

繁西前倾，神秘兮兮地小声耳语，“那两个提琴还不如你。”

当然不如，（插一）