= 晚餐

:docdate: 2017-9-30 —— 2017-10-30

[, 上古神话]
""
在东海的极东处，有两棵桑树，枝葉交缠，互相扶持，不知生长了多少年，也不知它们有多高。我们只知道雲霓也无法拂到它的下枝。在洪荒时代，九个太阳居住于下枝，一个太阳栖息于上枝。每天凌晨，太阳之母，东夷女神羲和将逐一为每个儿子沐浴，再从树顶上驾起日车，载驰着十兄弟照耀世间，给人类带来光明与希望。
""

“日本根本不是扶桑。”繁西认真的劲头上来，死活不同意和曦的说法。

看着繁西认真的傻样，和曦捂着肚子偷笑，有意逗他，“小学生懂什么？王维王摩诘，唐朝大诗人你总听说过吧？他写过一首诗《送秘书晁监还日本国》。”

“想你小学生也不懂什么叫秘书晁监。来来来，姐姐教你个乖，唐朝有中央机关叫秘书省，掌管图书经籍，秘书省的长官称为秘书监。闲差，大大的闲差，sinecure，拉丁语，哈，小学生哪里懂。当时秘书监由晁某担任，所以按唐人习惯尊称为秘书晁监。”

“他其实是个来中国学习的日本人，遣唐使，叫什么来着\...？不准笑！不叫晁盖！对了，叫阿倍仲麻吕，好像。等他看厌长安名花一万万之后，准备回国，上至唐明皇，下至公卿巨宦纷纷写诗相赠，不入流的诗人杜甫都不配为他写诗吟别！”

“扯远了，王维诗里写了‘乡树扶桑外，主人孤岛中’。说明唐人已认定扶桑即日本，日本即扶桑。别不服，唐诗里还有两千多处证据，姐姐一一引用，怕只怕压死你！李白也写诗送过晁某，那首是千古绝响，可惜我的对面坐的小学生，和他谈不了人话。”

小学生被唐诗中两千多处证据諕住，吓得转了攻击方向，依然不服。他告诉和曦，倭人是世界上最崇拜真理正义的人类。唐时中国是世界帝国，开边开到中亚斯坦，杀人如麻，尸积成山。倭人怎能不羡慕如此天朝上国？穷人攀附富人总需沾亲带故，他们在中国典籍中搜刮，指着富士山对唐人说那就是天朝文献中的扶桑，连发音都很像。唐人怜惜这群把床单挖个洞套头，一夫多妻，不远“万里”而来的夷狄，胡乱承认罢了。自黑船来袭之后，倭人立刻明白世界大势已变，劫略屠杀才是新的真理与正义，于是他们患上集团失忆症，富士山神山依旧，只是扶桑是什么？我们的祖先是神武天皇，有祖传破刀烂镜子为证。支那人大大的狡猾，以前骗我们说神武天皇传自吴太伯，富士山就是扶桑，现在统统要拨乱反正。
// 繁西的历史观

“按照我的理论，扶桑不是日本，也不是最近几百年大家乱猜的阿米狗墨西哥。”繁西公布**独家研究成果**，“我以为，扶桑最大的可能是新西兰。”

“新疆，西宁，兰川？”

滚！

在星期六上海滩的月夜，伴着小提琴师身姿的摇曳，一边吃着期盼已久的烛光晚餐，一边争辩着对社会人生毫无益处、意义的话题，说明\...说明用餐的二人是一对相爱至深的情侣。

扶桑之前争论温泉，温泉之前和牛，和牛争辩不过因为埋头用餐的和曦随口问起，“牛排怎样？”

出南京城花了一小时，路上两个半小时，在上海又堵了一小时，比预计迟到了两小时，开车的和曦又累又饿，然而\...眼前的坏蛋一点也不体恤我！

都和他说是米其林三星餐厅，有着穿要求，可他呢？像平常一样穿件破T恤就来了。和曦盯着T-Shirt上的"I'm Not Antisocial I'm Anti-Stupid"看。

混蛋！繁西就是个毛孩子，好歹你也是上市公司CEO，整天这么cynical的。你是有意穿来挑衅的吧！这世上固然都是蠢货势利眼，可打破他们的幻梦才是犯罪！

想起昨晚被繁西捉上床时，他穿的好像是"Don't say maybe if you want to say no"，见鬼，你又不缺性伴，何必与我们女人过不去！

繁西，你这种东西怎么会有女朋友的！和曦生气了，指责男友是懒鬼，不肯履行男友的义务，陪她去日本泡温泉。繁西不耐烦的嘟囔，明明去年去过四、五次了。汤山也有温泉，随时可以去。

废话，去年的事情还能作数吗？自从去年年底的那次旅游，你就再也不陪我出国玩了，甚至连国内稍远的地方也不去了。

日本的温泉有雪猴子可以看，汤山的温泉看你这只猴？和曦质问。

繁西翻起白眼，自告奋勇要求担任温泉猴子一角，在和曦泡汤时。只见他鼓起腮帮，猴头猴脑地挠痒，嘎吱嘎吱吊嗓子乱叫，自作聪明地举起双臂攀住想像中的香蕉树，还用双拳愤怒地砸胸口。讨厌，猴子与猩猩都分不清！

和曦本来已经笑了，可惜身后的两个提琴师小姑娘笑出了声，误了曲调。

繁西意犹未尽，“如果泡温泉的和曦欣赏红彤彤的猴屁股，那不如看我的。”不知从何处学来梨花诗，繁西吟道：“我的屁股/是全天下/最好看的屁股。红润、白腻、圆润，长期锻炼自然紧致挺翘，难怪你昨晚抱着它啃了好长时间，毛都啃荒了，你是识货的。”

去死，死啦死啦滴！和曦愤怒地瞪了小提琴师，繁西是我的，你们红什么脸？就算在想像里，他的屁股也只属我一人！

繁西真讨嫌，闺房里的事情到处说，包间里明明有外人。和曦想了想，又说，“你也知道我不能去汤山的，不吉利！”

“南京本地的民俗学家/诗人/小说家考证，汤山即是当年羿皇射落九个太阳的地方，时间在五帝之一的尧时。据说坠下的太阳钻入大地，自此汤泉喷涌不止。当地还能找到宋时土人修建的庙宇纪念为民除害\...呸，多管闲事多吃屁的后羿。”

和曦指着自己的鼻子，“你有没想过为何从未见我去汤山？连顺路经过都没有，宁愿绕道？你难道不知道九个太阳是谁的儿子？最适合和曦的温泉在日本，和曦应该去日本玩，多多滴！扶桑女神爱回家！爱回家洗她仅存的傻儿子繁西！繁西你这么不要脸不害臊，姐姐最后警告你一遍，温泉里严禁性交，太干，插不进来！”

“牛排怎样？”繁西心不在焉，疑惑地随着和曦重复，仿佛听不懂这简单的四个字。“还好吧。”回过神的繁西草草答道，抓起一片面包，去蘸前餐上装点的鱼子酱。

大部分人类在几十年还算“漫长”的生命中都会感染如下疾病：突然兴起，花费无数时间、精力、金钱为所爱的人制作菜肴，只盼着心上人说一句“好吃”，接着狼吞虎咽，最好连盘子也一并吞下去。

所以和曦愤怒起来，体会到无数母亲、妻子所经历过的心酸里程，明明费了这么一番辛苦，为何你对我的一片苦心如此漫不经心，一点也未感动，**难道是因为他不够爱我？**
// 希望越大失望越大，心里企盼与现实差距，心理强烈失望

仔细想来和曦并未付出时间现力，似乎没有资格要求上述回报。然而在我们的时代，金钱等于爱情，金钱的多少相当于爱情的强烈程度，这是比人权宣言更加不言自明的真理。

和曦抢过繁西手中产自伊朗的鱼子酱，将黑色美梦一股脑倒在生蚝上，恶狠狠地白眼翻他，气鼓鼓地一口吞下。继续白眼，用银勺刮下最后的鱼子，拌着海胆嚼了。讨厌，十八道菜的大餐好是好，只是每道菜的份量不足一口，尤其在盛怒之下，什么味道也没在口中踟蹰。

“对着眼前的美人谁还有心思品味牛排？”繁西懒懒自辩，手伸到台布之下轻轻捉住和曦的右脚，悄悄除了鞋袜，拉到大腿面上，细细玩了起来。

又前倾，神秘兮兮地小声耳语，“那两个提琴还不如你。”

当然不如，繁西闲时有一个喜好的运动：逼和曦跪在琴凳上拉小提琴，然后从后方撩起裙子侵犯她。经过无耻的特训，和曦已经可以古井无波地完成曲调，分毫不乱。繁西很得意，以为自己训导有方，丝毫没想到最可能是女性对阴道性交一点也不敏感的缘故。

吹捧的话和曦爱听，虽仍虎视眈眈，心里决定暂时饶了他。用叉子叉起一小块繁西的牛排，细细嚼了，“叫你不和我去日本吃！USDA Prime就是不如松阪和牛，去年那个A5级到现在还忘不了。”

据说物理学有句名言：物质永生，不会消失，只会转化。所以标价500美元/磅的A5级松阪牛排自从去年进入和曦肚内，依物理学原理，从未消失，只是发生了不好的转化。。。转化成看不起其它一切牛肉的资本。

繁西绝望地看着和曦，“您老吹松阪牛肉一年多了，行行好，可否让牛歇一歇？”

不能！和曦柳眉倒竖，把脚丫抽回，乱蹬。我倒也想歇歇，谁知那个狗头孟任平白无故地刺激我，不行，和曦也要去日本玩！立刻、马上、时不我与！

半月前孟任三人从日本归来，像所有难得出国的普通人，兴奋不已。逢人便拉着夸说旅行经历，展示与山川名胜的美美合影，分享专卖给游客的土特产。这一切让去东京次数还多过新街口的和曦烦恼不止。

哼，折腾家里人也就算了，那狗头居然把她小店街的狐朋狗友也招家里，一窝又一窝，乌烟瘴气！她的那些“朋友”，大多是典型的小店街女服务员，初中没念完就从穷乡僻壤跑出来到大城市打工，无知无识，穷得叮当响，一辈子在最低保障线上或者下挣扎，所以听到她的日本奇遇记艳慕不已，如痴如醉。

最可恨的是\...繁西也入了迷，每次都掺在服务员中听孟任说书。那传奇故事的精彩程度自然不是《环游地球八十天》所能限量，几乎达到了神怪小说《西游记》的水平。

“不是每个去日本的游客都差点把京都鹿苑烧掉的。就是日本人鬼吹的现代古董金阁寺。”繁西赶紧为生肖同属野猴子的孟任辩护，“这么传奇的经历比小说还有趣。”

呸，不管你如何卖力，她都不会让你脱裤子的，你就死心吧！

繁西兴致上来，连新端上的龙虾也未留意，努力讲述和曦早已听厌的故事。无非是孟任如何如何在东京瞎晃，误入了一处私家花园。站在清幽的花园里，摆脱闹哄哄游人的她开怀畅笑，顺手扯住一位路过的海洋生物学家，夺过他手上的大剪子，咔嚓咔嚓，为他修剪了四株在孟任看来“格局拘仄，气骨调丧”的盆景树。看着那矮小干枯男人纵横四溢的老泪，孟任很满足，扶老携幼是她的夙愿，而感激的泪水是世间最真诚的礼物。

谁知那老年男人不依不饶，对着孟任叽叽呱呱说着鬼子话。虽然语言不通，但孟任知道那男子居然一身是胆，敢向永恒的君王提出不情之请，求恳她平生的绝学。

平生绝学怎能轻易与人？总得矜持三秒吧。三秒后兴致勃发动青雲的无上帝王纠住男子，跳上赶来的警车向千代田区永田町进发。

站在奇怪的礼堂，眼看着几百名奇形怪状、浑不似人类的男子，人来疯的至尊迫不及待又毫无保留地向倭人传授。当然时间有限，四个小时内，只好将平生最自负绝学之纲要悉心传授，以防她口中的东夷人终生只是沐猴而冠。这绝学的纲要她命名之曰——礼之本。

和曦越想越气，孟任崇拜者中颇有几个姿色撩人的年轻女孩，繁西和她们搅一起，怕是为了接近那个王可可吧？初中生配高中生，有共同语言的吧？

“孟孟就这样把日本朝野搞得鸡飞狗跳。”毫无说书能力的繁西道，“折腾了半月，他们好不容易成功哄骗孟孟三人完成了**中国大返**，据说他们现在在急论倒底是以天皇名义赐予那四棵玉碎的盆景树神名抑或爵位。神名的话，XXXX，爵位的话，XXX。再吵下去，日本的内战指日可待。”

装出很感兴趣的样子，和曦顺着繁西，“是呦，我就是听了她的和风讲座，才想去日本的。带人家去日本玩，吃正宗的日本料理，好不好，好不好吗？”扑闪着大眼睛，学苏姬。

“日本料理？”繁西倒吸一口气，鼻孔中喷出八吨不屑，“咸，而且油。”

“喂，繁西你真是孤陋寡闻。国际公认，只有法国菜和日本菜才是高档料理。你这种土豹子真以为中国菜有什么了不起？中国餐馆在国外遍地都是，档次也和遍地都是的麦当劳，肯得基相仿！快餐。换句话说，你见过遍地开花的高档馆子？你见过人人叫好的文学名著？杜甫的诗这国家真真正正能欣赏的超过一千人？”

“反正我吃不了你鬼吹的松阪牛排，咬一口半嘴脂肪。我喜欢的牛肉还是传统的南京回民酱牛肉。不管多老多粗多瘦的牛肉，老卤炖上三天，快刀呛纹理削成蝉翼一样透明，再批在热滚滚的拉面上，一样入口即化，还免了肥腻。”

和曦大骂繁西不懂牛肉，因为**国际公认**，牛排要嫩还要肥，牛牛平时还喝啤酒，享受定期按摩。

繁西冷笑，动用了全身的cynicism，和平时一样，“就我所知，长达千年，西方人有且仅有一种**正确**的性交姿势，也就是一般所说的‘传教士’体位。所以在我们这个被西方人统治的世界，绝不能存在一种不需要高档牛排但仍然美味的烹饪方式吧。”

“日本菜高档？呵呵，日木人最了解这个世界的运作方式，毕竟，他们‘脱亚入欧’了吗嘛。深谙商业社会的真理，贵即是好。曾经有个心理学实验，同样的披萨，标两种不同的价格，结果虽然两拨顾客买到的披萨是一样的，付出高价的那群消费者觉得更美味更满足。日本人依靠高挡装修，神秘且富有异国情调的日语词，昂贵的标价把顾客当猪宰而不自知。要说法国菜高档我承认，历史上法国人从太阳王年代就爱享受。日本历史的大部分都不吃肉，天天吃草，要做人间佛国，连幕府将军吃的从记载看都是猪狗食，他们的厨师才摸了几天肉？大体而言，日本人做的食物，越生的越好，毕竟生食比赛的不是烹饪技巧。”

“日式料理三宝，拉面，咖喱，天妇罗可以说是女娲禁止兄妹通婚以来，人类文明最大的耻辱！”
//  不得以因为篇幅，去掉咖喱的批评，一笔代过

“日式拉面，也就是他们鼓吹的豚骨拉面，根本不是拉面，而是压面。”曾经的兰州拉面馆小伙计繁西给出了专业意见，“拉面需要高超技巧和数年艰苦不懈的练习，压面需要屁股，足够肥重的屁股；豚骨真是新鲜美味的名词，妙在不懂中文的美国人和不懂中文的中国人都想不到它是菜场里最无人问津，廉价的猪筒子骨；一辈子没吃过广式叉烧的土人也许并不能望文生义得出叉烧即叉子上的烤肉，而非日本猪骨味精汤上浮着的半两肥膘。日式拉面唯一的优点是一碗汤免费送你两锅猪油。从设计看，日式拉面刻意选用一切可以节约成本的食材，它的目的是为了摊主尽可能的最大利润，而不是口味。当然在我们这个谎言编织成的现代社会，相对于其它骗局，比如钻石、保健品、米其林三星，它又诚实的像个新出生的孩子。

“你的意思我受骗了？”和曦不敢相信，翻开桌边的宣传纪念册，指给繁西。

“你仔细看措词。‘米其林三星主厨，集团在香港拥有同名的米其林三星酒店’云云。。。就是不提这一家是不是米其林三星，尽胡扯不相干的。虽然我不懂那什么米其林的把戏，但从这宣传册刻意回避的问题推理：米其林只颁给某家具体的餐馆，不授予某个厨师，也不授予整个集团，所以上海这家才会如此变扭宣传，让你自己产生这家也榜上有名的错觉。”

急切之下，和曦还留有一丝幻想，“不过是你的**推理**罢了。亏你天天胡吹循证科学，说‘一克实证胜过一万头康德’，还说只有日本人的思维能力才会低下到推理的程度。原来你‘只看到别人眼中的刺，却看不到自己眼中的梁木’。更没有想到你成了你姐姐平生最讨厌的鲁迅，‘不惮于用最大的恶意揣测旁人。’”

繁西嬉皮笑脸，像个猴，“看场合呗。和曦请你留意：真知是昂贵的，昂贵可不是譬喻，它不该在酒桌上挥霍。酒桌上只宜谈风月。有女士的话，风月不敢谈，只好谈轻浮的话题。酒桌上讨论G蛋白偶联受体，泊松分布，Bayesian inference in simple linear regression，不是吃饱了撑的吗？其实看开点，还指望商人诚实？这家是不是真米其林又如何，米其林本身不也是个中产阶级骗局嘛？看过报导，米其林们的主力消费者并不是中产阶级幻想中的上流社会，恰恰是咬着牙攒钱，一年半载来体验一次的中产阶级。所以不是中产来米其林消费，而是米其林消费中产阶级。”

99%的情侣争执到这种程度就会走向分手。和曦却难过起来，“我对他不好，和他一起这么久了，竟然才知道他不爱吃牛排的。”看着繁西的眼珠快要迸出，又免不了好笑，不就因为你当过几天兰州拉面馆小伙计，至少这么维护牛肉拉面的荣誉吗？

繁西又开始诋毁天妇罗，突然，一缕神秘的微笑浮出。

啪，和曦抄起桌上餐刀刀背砍在繁西头上。两行泪崩，“繁西，你在想别的女人，居然笑得这么温柔！和我。。。和我在一起时从没见你这样笑过！”

繁西嗅出危险，把椅子拖到和曦身边，凑近今晚第一次真正伤心的她，“只是想起去年东京的那什么馆子，把槐花裹了炸天妇罗，狗屁不通，一嘴油味，你不也没吃下去吗？想到这，我就想起我家都是生食槐花，不用任何烹饪。不过刺槐花有时有剧毒，只有我姐姐能分辨。可惜姐姐忙了，没空顾及弟弟，只知道天天围着她的情人和曦转~~”

呸，才没有呢！和我在一起，就算姐姐也不能想！和曦心里略好一点，可繁西一脸坏笑又凑上来，“这样说来，在牛排上桌之前，你一个人偷偷笑得那么开心，是在想哪个野男人？”

啊啊啊！不好，被抓了现行！**虽然女人想其他男人天经地义，男人想其他女人碎尸万段！**但想归想，被情郎看穿就不好了，关键心中的那人还没法提起。

和曦把小手递给大手，将头靠在他的肩上。“讨厌鬼，心思细密的像个女人。”一起看着眼前的黄埔江与摇曳的灯影，心思渐渐慵懒，变成午后的猫，慢慢靠在他的心头，一动也不想动。

和曦靠了一会儿，又感无聊，心想人类一方面“惜时如金”，形容人生“白马过隙”，短暂得如“薤草上的露水”，只待太阳一出即晞干不见；另一方面又耐不住任何无聊，所以需要刺激，无时无刻的刺激，以至于世上有数不清毫无意义只为了“谋杀时间”的活动。比如今晚的晚餐。。。
// 与后面重出。。。合并吧

和曦开口，“你说的都是穷人的日本料理，日系的高档你又没吃过。。。几次。”

“嘿嘿，虽然没吃过几次，但我知道高档餐厅的定律公式，所以和常吃的老客没有区别。”

 繁西的高档餐厅公式：
    1. 选用最好的食材，别怕，价格乘四，卖给食客。
    2. 加松露、鱼子酱、鹅肝，每种原料都可以让菜价翻倍。
    3. 日系餐馆还可以加松茸。菜价翻倍。
    4. 如果想标999美元，直接加金箔不啰嗦。

和曦笑了，想起拿到南京大学录取通知书的那一日，虽然自己是免试入学，通知书本是意料中事，仍然带了苏姬飞往纽约，特意去品尝$999的冰激凌庆祝。那里面确实有冰冷的黄金。

// 和曦 一段金箔代表工匠精神
“狗屁工匠精神。废物才要不断强调努力认真。常温下，黄金不会与身体发生任何化学变化，所以吃多少拉多少。如果使用黄金代表极致的‘工匠精神’，那我拉出黄金岂不也说明我拉屎的态度达到了极致。”

“繁西，你好恶心！”

“别笑！”繁西反而认真了，“这是正经事业。你知道深圳那边的黄金加工厂嘛，有人承包它的厕所，一年承包费几百万。加工厂车间总有黄金粉尘，被打工妹吸入，最后完璧送给粪坑。没错屎中炼金！可比金矿炼金容易多了，产量也大。”

和曦笑得趴桌上颤抖，“繁西你每天研究什么？怎么尽知道这些没用的冷知识？”

“那我说个有用的。”繁西将龙虾上配的松露挑出来摆到和曦的盘子上，眼看着她吃下，美美地眯眼睛。

“据说全世界只有两个地区长有野生松露。一个是阿尔卑斯山南麓，法国和意大利的山区。另一个是地形复杂，保有海量上古孑遗生物的云南。”

“雲南松露不好吃，根本不是一个味。”和曦客观地指出。

“没错，但你知道为什么嘛？成熟的松露才好吃，不熟的就是雲南味道。可外表上分不出，阿尔卑斯山的农民训练狗来寻找成熟松露。云南农民靠感觉乱挖树根，十挖九空，不旦费时费力，偶尔挖到的因为分不出生熟，只好当生的卖，不值钱，还坏了名头，连你都晓得了。”繁西用胡说八道终结胡说八道，“要是医药公司搞不下去，我也去云南挖松露，挖真正法式大餐水准的。”

“你也会训练狗来找松露？”

“不，用猪。猪的嗅觉可比狗灵敏多了。一百年前的农民都用猪，后来因为种种原因，这项技艺失传了。但也无所谓，用狗虽然产量低，品质差，但物以稀为贵，单价反而上去了，所以也没人刻意恢复光荣传统。”

濛濛细雨天气，易聚难散忧愁。湿滑挽着春寒，不旦反射冷光还浸入了骨髓。如果不是这无法抵御的刺伤，和曦一定以为这一切只是梦寐。然而穷人没空也没有权力伤感，目送着繁西套上皮裤，踩着黑亮亮的胶雨鞋，呱叽呱叽顿在泥泞中。两只小猪循着啧啧声，东倒西歪地跟着他们的父亲繁西渐行渐远。妈妈和曦还有三个小时的空闲，打扫缝补、烹饪美食为爸爸 也为贪吃的孩子们。最后还要将孩子们的小屋洒扫得香喷喷，完成这些，留给她的只剩下等待与希望。

好幸福好浪漫！和曦想。与她同桌异梦的繁西也在幻想。只是在他的幻想里，艰难苦恨中等待他归来的只能是姐姐繁娃。。。

“要说明新西兰才是扶桑，我们得先搞清中文典籍中的东夷族倒底是谁？”繁西开始胡言乱语。

“综合上古神话对东夷族的描述，我们大体可以得知东夷人皮肤黝黑，身材壮硕，生活在中国东南方几万里处的海中，所以不可能是日本人。”繁西得意自信的样子仿佛他发明了广义相对论，“综合各种神话的考证方法可大有来历，连外国人都承认，叫meta-analysis，看谁敢有不同意见！”

“现实中符合这一描述的只有一种人类——南岛人，又叫波利尼西亚人。对，你脑海中立刻浮现出夏威夷群岛热情的比基尼土著少女。从目前DNA证据看，事先声明我不是DNA方面的专家，无力批判他们的学术，南岛人大约从五千年前逐渐从中国大陆登上了台湾，就是现在台湾岛上的泰雅人，然后沿菲律宾、印尼、巴布亚新几内亚，扩散到整个太平洋，最远到了复活节岛和马达加斯加。南岛人是标准土著，原始人，没有文明。他们的科技不过是砍倒一棵树，挖空了做独木舟，绝对没有中国的龙骨造船术。然而没有罗盘、星历、六分仪的他们为何比欧洲人更早统治太平洋？有人称他们的独木舟连渤海都划不出去！最可怕的，他们是如何知道太平洋上诸岛屿位置的？”

见和曦露出认真听讲的俏模样，繁西愈加得意，“根据我的理论，五千年前华夏一族在他们神明带领下，开始压迫中国大陆原住民东夷人的生存空间。不得已他们的母亲女神和曦只得向他们喻示牛奶与蜂蜜的应许之地。通过女神的神力，独木舟中东夷人穿过疾风骤雨，向着女神微笑的远方奋力击桨。一旦明白了这些，又考虑到新西兰分为南北二岛，也符合扶桑有两棵的传说，所以我们的理论完备了。逻辑自洽（?）”

讨厌！心里美滋滋的，和曦想，人家才不黝黑，也不壮硕，更不会给你生十个孩子，才不要做什么东夷人的太阳女神羲和呢！

陶醉了一会儿，见繁西正注视着七十多层下的外滩与浦江。灯红酒绿，游船翩翩，纸醉金迷，和曦忍不住问，“黄浦江景如何？”

“不过一条臭小河吧。”

哈？和曦不忿，明明我很喜欢外滩的，你敢不喜欢？遂骂之，“我代表几千万上海人民骂你，‘侬这只猪啰！’不识好歹！”

繁西想想，自己先笑了，“作为松江人，正统吴语的继承者，知道侬是我的意思。这样看来，和曦是少有能自我反省的人才，意识到自己是猪头的事实。”

和曦立时记起古代诗词中，**侬**多训成**我**，比如南宋大诗人吴郡范石湖《四时田园杂兴》中的“黄尘行客汗如浆，少住侬家漱井香”。原来上海活在他们正宗吴人眼中不过是洋泾滨吴语，**中华大地有神功，个个挥舞鄙视链**。就拿小小江苏来说，苏南的看不起苏比，苏北看不起南京，南京\...只好瞧不起安徽了。

上海人一定看不起松江的穷，松江人。。。和曦想起父亲的同事陆书记一家。每每提到上海，提到南京路，衡山路，徐汇，外滩那一脸的不屑正与繁西相同。

“昨夜魂归秀雅桥，华亭鹤唳动秋高”。和曦想起繁娃一首诗的首联，也许这群寄居南京的游子真正眷恋，梦魂萦绕的永远只有那早已成为历史尘埃的秀野桥。
// 今天才知道是秀野桥，不过也差不了多少吧。作为松江人听写应该有可能听写成秀雅。

虽然陆书记经常笑说他的爷爷本不姓陆，过继给华亭陆家罢了。过继不久，陆家因为抽鸦片也败落下来，但两千多年的旧家习性或多或少传到了陆书记这一辈，哪怕他自己全无知觉。

松江陆家源于吴郡陆氏，吴郡陆氏的始祖叫陆通，传说他就是对着孔子纵笑纵歌“凤兮凤兮，何德之衰”的楚狂接舆。传说当然靠不住，这个陆通其实是齐宣王的孙子，大约与荀子同时或略早，战国中晚期。此后每一代吴氏祖先都是明确可以稽考的人物，再无半点神话的味道。这种绵延瓜蒂两千多年清名不堕的家族放眼世界绝无仅有，但在此地不足为珍，毕竟孔子、颜子、孟子、曾子等等世家更加久远煊赫。

作为东吴四姓之一，陆家最不稀奇的就是出名人。华亭侯首封于大名鼎鼎与刘备、诸葛亮周旋的陆逊。之后的陆抗、陆机、陆云不减乃祖；唐时陆氏出任宰相有六人，最著名的首推陆贽。在中国历史上，他比陆逊这些丞相、将领、都督、文学家加一起还重要，被宋朝人广泛崇拜为唐时的贾谊。苏东坡称其“智如子房文则过，辩如贾谊术不疏”。朱子最不喜东坡，然并未厌乌及屋，对陆贽仍心有戚戚，大力推崇。

然而又如何？和曦想，几十年前革命炮火把这些迂腐的旧家统统打成了齑粉。光有钱有什么用？是，陆书记是比爸爸官大，葉家比舅舅还有钱，但就算现在冠冕不绝，可没有了诗礼传家，没有了耕读不缀，“君子之泽五世而斩”，哪里就比我们和家苏家强了？陆家，葉家这些眼睛长在脑门顶上的世家还能风光几日？最好笑的是繁家，唉呦喂，你们是什么东西，也配怀旧的啰？
// 语序
// 欧洲那些old money，以钱为传承的家族才能蹦跶几年？
// 研究中国历史的，把中国的世家为何动不动能传承上千年研究透了，就是一部大学问

两千年的世族启发了和曦。她思忖片刻，换上清纯可爱小狐狸妆，拂晓的晨星于是向繁西媚眼，“就算这不是真正的米其林三星餐馆，就算你不喜欢浦江，但说心里话你真的不喜欢今晚的生活，这种有钱人的生活，有香槟、美人、美食，还有提琴师的环绕？说心里话。”

繁西眉都未皱，“任何人如果声称不喜欢，他就是无耻的撒谎精。”

嘻嘻，和曦凑得更近了，“你不希望孩子们重复这种生活？在高档餐厅吃着鹅肝，与聪明漂亮的女子约会，一起看明月从海上慢慢升起？”

“固然好，但为了这种生活成为钱的奴隶。。。”

和曦早已预料这种答案，忽然转了话锋，“虽然你常常喊着‘也不怎么想活下去’‘活着死了也没多大区别’，但扪心自问，你真的不害怕死亡嘛？”

“怕，当然怕，怕的一屄。”不想活下去自然不等于不怕死，天壤之别。

“是了，姐姐果然没有看错你，你不是那种会撒谎的骗子，这几乎是你唯一的优点。世上哪有人不怕死？斯宾诺莎？哼哼，反正我觉得不害怕死亡违背人性，虚伪。你知道吗，文天祥一开始也想着蒙古人能放他一条生路，让他隐居。这才是真实的他，也就是我爱的那个。孔子梦到两楹之间的翌日，对赶来的子贡荷杖而歌，那歌声又何尝不是对死亡迫在眉睫的宽解？”

繁西愕然，想不到兴抖抖来吃顿饭，还要讨论哲学问题，世上果然没有免费的午餐。晚餐也没有。。。

“繁西，你知道么，现在世上的所有人”，和曦指指自己与他，又抓起手指画一个圈代表所有人，“世上的所有人不分贵贱其实都是古代有钱人的后代。任何一本中国人的家谱都能上溯到三皇五帝，至少也是齐宣王那种。美国总统，所有的，包括那个黑人都是英国国王的后裔，顶多是汉诺威系还是都铎系的差别。为什么呢？不需要读到社会学或是历史学的博士，你也能想到历史上穷人的后代已经死光了，灭绝了，不存在了。穷人没有足够的食物，没有挡雨的屋宇，没有良好的医疗，更无力结婚，就算侥幸有了后代，死亡率也高的吓人。

现在的穷人是以前富人的遗存，然而未来的穷人多半和现代的穷人无关。从这一点看，钱多多少少代表着immortal。孩子倒底是父母生命的一种延续。”繁西听出无数漏洞，仍然笑着认可这是一种有趣的理论，一个他**愿意相信**的理论。

“其实为了钱你要做的牺牲也不大呀。为不同国王、总统、资本家、财主服务，王政时喊Long Live the King，民主制就喊自由平等博爱、民有民治民享、绞死暴君，反正流行什么喊什么，只要不傻到去想正义是什么，就可以一代又一代幸福富有的生活下去，让孩子们重复着这种生活方式，不也很美好吗？”

阴雨缠绵一月半，任何人都会厌倦烦燥。和曦托着腮，坐窗前看寒雨打湿松岗，渐渐溅起烟霓。雲，是雲！她兴奋起来，雲会是这样生出并遨游半空的嘛？

眼前的烟雾动了，一团团，自行行动起来，向着和曦冲来，不需要脚。呯！团团烟雾撞入柴门，竟裹着好几个蒙面人！不答话，也不理会和曦，那行人径自冲入孩子们的房间。尖叫！恐惧！愤怒！立刻充斥茅舍。这伙强梁有备而来，从腰间抽出布口袋，置于孩子身前，扬起短棍，无情打在宝贝的尾巴上。娇生惯养的宝宝哪里受过这种虐待？倏地一窜，全部钻入了歹人预备的黑布袋中。不~~！！和曦尖叫，像所有母亲一样扑过去，乱舞两爪用尽全力争夺。黑衣人齐声狂笑，领头的强盗一把推倒和曦，扬长而去。

为什么，为什么？她伏地痛哭，渐渐泪化成了河，化成了江，化成了白茫茫一片海。精卫鸟在她头顶盘旋，凄厉鸣叫，“精卫，精卫~”地叫，哀叹连它也填不满的伤心汪洋。和曦只想知道为什么？为什么强人要抢走她所有的孩子？为什么，为什么她扑上去时，扯开带头大哥的面罩，下面竟是熟悉到不能再熟悉的。。。繁西！

// 这里可以分章
双腿抽搐了几下，惊醒在月光艇上。蜷着身子，捂住抽筋的小腿，双泪滂沱。

所以繁西也只好醒了，迷迷糊糊伸出手臂揽她。和曦更加激动，凑到他的耳边，“繁西！你为什么要勾结外人抢走我的孩子，我的十个宝贝！他们是我们未来生活的希望啊！”

呃？莫名其妙的繁西因为经验丰富，知道如何处理莫名其妙。他半起身，扳起她的脚，等她疼痛渐止，又从后捉起她，将她俯按在月光织成的船板上，向下指指点点，教她分辨沙洲、星屿，在波光粼粼的大洋之上。

泪从未干，只在眼中。她缓缓平息，清醒过来。

张望，只见庄严与肃穆的凝重笼盖四野。月在中天，所以层雲阵阵，灯塔时而闪烁，提醒着旅者有些漆黑并不是大海。

指向西方天际，星星火光，和曦问，“那里是上海？我们都跑这么远了？”

黑夜中的一对眼睛反射着星光，笑了，“是啊，程序设定好了，凌晨四点抵达舟山，航线也是一样的。”

繁西没说“一样”是与谁相比，和曦更懒得知道。她翻身枕肱，叉开两腿对着朗月。
// 一段对肉体的描述。最后踢开繁西，没有心情。“你的女朋友还要慢慢充气，”乐得发抖。

和曦反手在床铺上一抓，揪下一块，握在拳中，用力揉搓，干干的，她想。稍举，松开，金色流沙从指间流失，倏地又变回月光，向天涯行客流淌。唉，她叹一口气，这月光艇果然是大好的法宝。

上个月，繁好那灾星无聊之下做了这艇以供淫游。试航之前，她在繁家每一号人物面前吹嘘，说这月光艇虽只花了一天功夫，却是你们这些乡民、井底之蛙一辈子可望不可及的宝物。吹嘘也就算了，那二百五成天没事在家，琢磨要给这月光艇起一个娇人的名字。她把大家喊来，群策群力。等大伙儿绞尽脑汁，又冷笑着把全家人的心血批评的纤毫不剩。哼，她自己起的名字更烂，一开始叫**众星罗**，结果还没活过一日，又改成**列缺**，还是不到一日，再改**纷庬**，目前勉强稳定在**雲师**上。

可惜那时孟任去了日本，不然两个喜欢夸耀宝物的混蛋一定会“狗咬狗，一嘴毛”，岂不快哉！和曦倒是按外国传统准备了香槟，以至烧漏了钱包。谁想繁好鄙视地冷笑，连声谢谢也吝啬，接过瓶子，右手握着苏姬跳上**雲师**，扬帆于苍穹。留和曦在尘世鬼叫，“为什么不带我一个！我以为我们已经是好朋友了呢！”

于是借着暝暝夜色，繁好苏姬姐妹拍手欢笑，身边炉火明丽，火中的烤肉任君恣肆；眼前樽中甘醴，洋洋四溢亦无人怜惜。她俩歌唱，她俩舞蹈，时而摔角，时而赛跑，等闹到筋疲力尽就相拥一处，呼呼大睡。月到中天时，繁好突然有了新主意。踢倒广寒宫的城阙，她大摇大摆，逍遥尾蛇。苏姬缩在身后，左顾右盼。仙子常仪吓得变作玉兔，玉兔只好变成蟾蜍；吴刚闪了腰，一瘸一拐碎步跑来殷勤谄媚地奉上玉斧。繁好嘎嘎大笑，将月中金桂砍翻，斫下新枝。临行又顺手铰下一股月光。

回到**雲师**，以桂枝为钓杆，月光为垂纶，又系上从东海中摸来的五色石，正是当年精卫叼来填海的痴心所化。姐妹俩向下俯视，只看见深沉不语的海洋泛起无垠清光，天际外似有似无浮着黢黑岛屿。繁好纵起雲帆，须臾已在海岛之上。她降下丝绦，那岛屿竟开始缓缓震动，一举吞下了石饵。繁好提线，得意看着在钓线上挣扎的巨鲸，苏姬与影子手舞足蹈。等巨鲸赤尾之时，方才剪断丝矰，放它一条生路。终于为李白报了仇，，，算吧，她想。

真是好宝贝，和曦又一次赞叹，可以随心意大小幻形，仅需月光。如果去年有这东西，也许繁西就不会受刺激；不受刺激，今年也就会随我四处旅游了。说起来，去年的地中海海岛之旅开始时一帆风顺，马略卡、塞浦路斯、圣托里尼、米科诺斯、马耳他，个个令人窒息迷醉。繁西那夹生鬼明明也很喜欢的，谁想回程路上出了岔子，该死，让繁西看到了不该看到的东西！

繁西躺在一旁，欲望渐落，大脑于是有了用途，用来思考。

思考之下，且喜且疑。喜的是和曦也可以乘坐**雲师**，据繁好说，一身浊气的人类可坐不上此艇。那么理论上自己和她可以永远相守在钧天界，，，如果她不反对。
// 一身浊气的人类  有意用的模糊的表达

然而如果和曦也是女神，为什么之前教她法术，却连最简单的也学不会，不，她根本感觉不到灵力！另外，苏姬。。。

繁西思路断了。轻暖无骨的肉体挤进他怀中，哦，天上风大，和曦冷了。她将冰冷的小肚子贴繁西身上，抱怨他不知**雲师**的诸多变化，连风也不会挡。又问他在想什么？抱着玉人的繁西正酝酿体力，不但心外无物，心上也无事。干脆逗她，“在想你想的是哪个男人？”

啊啊啊，小气鬼！不就是下午和爸爸那个了一下，晚饭时想起，偷笑了一下，被他惦记到如今！不小心那个\...一下，也是很平常的，谁没有过？又想起前两天向繁好透露了针对繁西的大阴谋，好不容易得到她的首肯，所以最近得对繁西好点，假嘛假嘛一下。
// 越来越喜欢将南京方言写入。尤其是对话，想法中。因为和曦是南京人啊。她就是这样思考。

抱起繁西的脑袋，和曦吻住，笑谑了一会儿，热起来，一手拂在他的颈后，一路抚摸下去，直到臀部。猛然纵身一挺，反而骑到他的身上，微皱眉黛，吃痛将繁西惯用的作案工具吞并没收。嘻嘻，她笑起来，眯眼，反弓，夹住火烫的阴茎来回动，想起现在的环境，遂肆无忌惮地吼叫起来，在海天之间的孤雲之上，一点不怕被明月知晓。

良久，和曦全身大抖几下，从胸腔里发出含糊不明的呻吟，瘫软下去，两腿间的渴望暂时满足，加上之前的几次，一时疲累欲死。

躺下后，忍不住好笑，想着刚才与繁西交尾，难免与他交颈摩擦，那快乐痛苦痉挛触电的感觉如约而至。在今天以前，和曦一直以为这就是爱的本质，只有与恋人，比如繁西交合时才能享受这种无上的极乐，谁知下午与父亲不小心碰了一下，不旦自己，父亲明显也感觉到了。什么爱的标志？根本就是性欲的冲动，低级的肉欲！只不过父亲和我都能做到‘**发于情，止于礼**’。可某些姐弟，哼，铁定耽于欲望，仗着隐匿无人知晓，做出禽兽猪狗的事情，我一定要牢牢看住他们，好维护世界的。。。和平？见鬼，一时找不到合适的词汇。

想到修美的两个人如果做出那种丑事，和曦不禁吞下大口口水，好热好刺激，赶紧转移思路。

既然一直以来误以为的爱其实并不是，那么。。。和曦摇醒繁西，“齐桓公小白白，太子丹繁西，快醒醒，你知道爱究竟是什么嘛？”

过了太多生活的繁西艰难苏醒，吃力地发觉原来自己是齐桓公加太子丹。很吓人，对不？但仍比不上下个问题的冲击力。

“爱倒底是什么？”苦笑，不就随口鄙视了一下康德，至于逼我一晚上回答两个哲学上的终极问题么？相比之下，鸿门宴如凯风拂体一般鸟语花香、春光明媚。

这种问题自然没有答案，所以繁西与世界上一切哲学家答的同样不靠谱，“在我看来，两个臭烘烘的人类愿意抱在一起睡觉，就是爱了。”抱着和曦的他又沉沉离去。

哦，和曦居然当真，开始认真思考。然而立刻想到，繁西，不论正确与否，顶多回答了‘什么是爱’，而自己问的却是‘爱是什么？’，就好像‘繁西是人类’也许是正确的，但不代表‘人类是繁西’也是无疑的。

啊啊啊，思考好累，真不如弄钱享受，和曦闭上眼睛，也想加入繁西均匀低沉的呼吸。可惜一闭眼，令她惊悚排瓜的一幕又会浮现，总在最不经意间偷袭。

父亲办公室外面的休息室是和曦的游乐场，别人在那里等待召见，她在那里寻宝。南京本地企业的代金券，高档烟酒，最少也有进口巧克力，对于自以为拮据的和曦统统不可错过。

不管多少年后，和曦都不会忘记下午在休息室的所见。正当她走入，兴致勃勃向着柜子，完全没有防备的她看到了，看到了两个女人在等父亲，一个看杂志，一个玩手机，都坐在沙发上。听到响动，那两位女子也抬起精心打扮、浓装艳抹的脸蛋，其中一位正是父亲的专属医师韩美。她意外的表情也永远印在了和曦的脑中。

像受到惊吓的猫儿，和曦啊的一声弓背蹦高两尺多。又不像擅长平衡的猫儿，在惊愕之下，她落地时微微扭伤了脚踝。忍着痛，连招呼也忘了，急急趋出，直走出五号楼才弯腰按揉痛处。韩美被和曦吓到，从她的惊惶失措中读出了她的内心，于是沉下面上的笑容，坑头激动地去辨认杂志上奇形怪状的中国字。

步入休息室的惊鸿一瞥，让和曦读出了父亲今晚的安排。与自己的其实也差不多，快乐的约会，晚餐，看演出或电影，再\...再逐一或者同时或者交替与晚上的伴侣性交，像操母狗一样。

自和曦记事以来，父母已然分居，几乎不来往，只少一纸正式证书罢了。在父亲家里，韩美填补了空缺，尽心地照顾和曦的起居，和曦也将她当成了半个母亲，每次见面总是言笑晏晏的。父亲当然不止一个情人，但韩美是跟他时间最长也最得宠的那个。父亲经常与她打情骂俏，也不避和曦。甚至有一次经过父亲卧室，听到门后的她吃吃笑，问最近介绍的几个医生护士父亲有没肏过？滋味如何？是医生的温柔还是护士的激情更能打动他？反正按韩美的说法，学医的把性交只看作正常必不可少的生理需要，不像其他女人毫无理智地把性与感情纠缠在一起。

韩美了解和书记的日程，才会毫不避讳地化了妆，带了人等待他出来，却未想到和曦这个不速之客。而和曦知道韩美平日从不刻意打扮，嫌脂粉污染天生妖娆的面庞，所以一觑之下就明白了一切。

和曦也不知道学医的是否都像韩美所说，把性交当成正常必不可少的生理需要，与感情全无关系。和曦甚至怀疑韩美自己也做不到，她家好像并没有开公司，父亲当然会照顾她，但不开公司得到的好处终究有限。难道她对父亲就是传说中的**真爱**？

一想到真爱，忍不住发现从没有忘记那年夏天，正是和曦升入初中前的那个。当天下午本来要在游泳班渡过，但因为水质问题，训练临时取消。和曦暗自庆幸，连日积累的乳酸早让她意志摇摇。愉悦之下，她忍不住想给父亲一个惊喜，跑去撒撒娇，使他开怀大笑。

回家后却不见父亲的踪影，和曦只好算了，到冰箱里拿了雪糕，准备去小书房看爱情小说，好甜蜜好幸福的下午！

走上三楼，穿过甬道，十二岁的和曦轻得像夏木的阴影，来到小楼西北角上的小书房。书房问奇怪地虚掩着，冷气从门隙泄出，一并出来的还有女人似快乐更似痛苦的呻吟和男人雄浑的喘息，一如所有色情小说中的偷窥场面。

生活不是小说，虽然常和色情文学压韵。
// 借用了西方人的模式

和曦并没有追随小说里常见的情节：性在偷窥那一刻觉醒，一面含羞看着父亲与韩美交合，一面将右手夹在两腿之间，抚摸阴蒂，让“大滴大滴的爱液啪㗳啪㗳溅落在地板和芳心上”，最后“不巧”被性交中的男女捉住，半推半就加入那场orgy，任“父亲的精液灌满女儿的子宫”。

相反，刚看了两眼，和曦吓得魂飞魄散，脸色苍白毫无知觉的回到自己的卧室锁门躺下。

十二岁的和曦对性并不陌生。她看了太多太多的爱情小说，知道“王子与公主从此幸福地生活在一起”之后总得做点什么。人类是一种无法忍受无聊的动物，成就固然重要，然而所有人只能看到立在鼻子尖上的三分钟，想着用什么办法消灭它，最终迷失在各种运动制造的快乐冲动中直到死亡带来永久的安宁，前提你不能信仰佛教。
// 偶而写一句调皮的废话也不过分吧

王子与公主幸福生活同样需要不停的无意义活动刺激，而和曦从阅读中得知了幸福生活的保障——性爱。所有的爱情小说，至少和曦读过的，都将性爱描写成人生最美好的体验，至高无上的愉悦，相爱的情侣感情升华到了最高阶段才能在激情之下开展的活动。

所以在十二岁少女的浪漫想像中性爱是。。。呃，二十二岁的和曦早已遗失了少女的美好，忘记了，只依稀记得星空、玫瑰、白马王子穿着华美的礼服握着全套公主裙的自己双手在雲端山盟海誓，拥抱，还有接吻。。。

接吻？！！和曦抓过被子覆盖全身，缩成虾子的形状，偷笑到窒息，少女想像带来的剧烈幸福和欢快其实远远胜过十年后她从真正性爱中获得的。

可惜，和曦看到的却是真实人类性交的场面，她眼中不免布满松驰的皮肉，酒色充实的肚腩，短到失去美感的腿，奇形怪状的疮痣，绵延到肛周的虬乱阴毛和那在记忆里挥之不去的腥臭。很多年后和曦不免在自己的性爱生活中也闻到那股味道，只是作为当事人而非旁观者，倒不怎么反感。

那时的和曦并没有意识到父亲与韩美的交配其实已经强过90%的人类伴侣。所以在想像的玫瑰城堡沦陷之后，她经历了几个月的梦魇，在梦中她总看到一个面目丑恶的男子将他赤裸女伴按在书桌上，母狗一样趴着。那男子竹杆也似的细腿却不免支撑起他肥大下垂的肚子，他的面容髣髴父亲，却不知激动还是渴望令其扭曲得无法辨识。男人的臀部总是方的，用力使他更“方”，闷哼一下又一下，墙砖似的两块肌肉推动身体向前击打在韩美的一摊肉上。只推得三五下，男子“操你妈的”咒骂起来，刚刚杀猪一样乱叫的韩美格格娇笑，原来过份剧烈的动作造成阴茎滑出了阴道。

于是和曦看到了最丑陋的部分：像烧焦的半截枣木棍，形状\...没法形容，反正看了那东西任何人不该相信基督教中人类是依上帝形像创造的鬼话，假设上帝有哪怕日本人的审美能力。男子长有的畜生器官恬不知耻地翘着，从女性阴门中带出的汁水倒真的“啪㗳啪㗳溅落在地板”上。

男子一声号令，韩美白了他一眼，似乎很不情愿地用双手掰开屁股，露出应有的两个洞口。并不像书中的“蜜穴”“少女珍宝馆”韩美能够展示的只有黝黑、形状不那么规则的肛门和之下一寸的血盆大口。男子见了，嘿一声兴奋，用手扶着鸡巴就着亮光硬顶了进去。啪啪啪，皮肉撞击声又骤，女人痛苦的喊叫迎合上来，渐渐“被干到连绵不断的尖啸。”

虽然夜夜梦魇，和曦装作无事，每日正常起卧。但和书记与韩美毕竟是成年人，几十年的人生经验健在，多少看出些端倪，也不点破，只是谨慎多了，重新扮成了没有性生活的一对圣人/伪人，如同世上所有正常父母一样。

想到如此激动，如何睡得着？和曦只好仰卧观看天河旋转。不知道父亲在做什么？和曦脸上发烧，多半，多半已经做完该做的事情，正抱着韩美或另一个呼呼大睡吧。父亲毕竟不年轻了，多半硬不到这么晚。啊啊啊，和曦你倒底在想什么肮脏的事情！她害羞地对自己喊。

想起繁西之前说的“两个臭烘烘。。。就是爱了”，偷笑，现在父亲正抱着韩美，那么父亲爱上了韩美？那样也不错，我倒是不讨厌她。一阵冷风吹过，和曦一个寒噤，想明白了：父亲绝不爱韩美，他如果爱她，就绝不会允许她带上第二个人。而下午休息室中的第二个女人才是让和曦心灵受创的原因，那女子的面孔浮现出来，赫然竟是韩美的亲生女儿。

繁西醒了，坐起来，呆了一会儿，向下望去，看到黑沉沉的山峦矗立在茫茫大海之上，心知普陀已近。又回身找宝宝，见她安静躺在月光里。“既然没睡着，正好免得被我吵醒。我们正在降落，雲中最后的半小时。”又用额头去贴和曦脑门。

笑着温存了半分钟，和曦坐起，学着繁西的坐姿，抱住双腿，靠紧他。那些小说都是乱写的，什么性爱是至高无上的快乐幸福，灵与肉的升华，我怎么觉得还不如这样靠着繁西，静静地看时光把我们的青春啃食。只有等失去后，你才会晓得青春的滋味，和曦想。

如果这月光艇能航行得更远一点就好了，繁西排斥A380,但不会拒绝乘着它旅行。去年的地中海岛屿之旅真好，就是从伦敦回国出了岔子。去的时候坐一等舱，回国时坐的比一等舱还高级，叫什么Residence Class，家居级？两个的机票加一起竟然到了六位数，美元。反正不用我掏钱，呵呵。

从未听过这种级别，和曦特意将它留到了旅行的尾巴上，把它也当成了施行的一部分，期望它给地中海之行划上完美的休止符，永远留存在记忆中。

繁西好奇心动，上网查了半天，告诉她，“这是某家中东航空公司特有的服务，还高于一等舱。”

是的，高出太多了，上了飞机后，两人才发对家居级真的是家居级，已经没有座位的概念。反而由起居室，独立浴室，有双人大床的卧室构成，真正的飞行Hotel。比Hotel还要过分的是，这个空客A380中的套房还配有专门随飞的管家，只有一个职责：尽可能地满足两人的一切需求。

那次飞行的Butler是一位满头金发，年轻高挑的欧洲女子，会说四、五种欧洲语言，显然爱过良好的教育。在她热情带领下，在空乘一路致意下，进入了驾驶舱。与机长们言谈甚欢。机长介绍说如果一切顺利的话，8个小时后将抵达伦敦——上海的中转站，迪拜。夹生鬼繁西还开起了玩笑，说“我倒是希望不那么顺利，好多享受一点贵公司的服务。”气氛多好啊，当时。

谁知在点餐时出了第一个小岔子。金发美女管家拿来了菜单，短暂的二十分钟接触，她已看出了二人组织的权力结构。所以菜单交给了正坐在起居室沙发外沿的和曦，接着异常自然，显然已经做过千百次，熟练无比地双膝跪下，刻意缩在和曦的影子里，低伏着为她指指点点。

“繁西你个臭东西，还上市公司CEO呢，一幅穷酸相。”和曦骂自己的男友，“都怪你！你以为我不吃惊的？作为女权主义者，你以为我能忍受这个？说你小家子气，你还和我犟！你屁股上像安了弹簧，腾得站起身，一脸的惊讶和愤怒，想去搀扶，反弄得女管家尴尬不已。学学姐姐，不动声色地保持微笑，不经意向里挪一个位子，握住美女的手坚定掉她和我并排一处讨论，总算挽回了融洽。我要是男人，这美女已然到手，晚上就可以剥光吃了。”

然而繁西嘴头子依旧不服，“和女权主义有什么关系？他们一样有男butler，见鬼，butler又不分男女了，英语就是一团糟啊。男管家一样会跪了和你说话，他们这种就像几年前国内流行的日本跪式服务。”

“再说了，Residence只算第三等有钱人的出行方式。第三等已经堕落到这种地步，可想而知。。。哼！”繁西自从那次旅行后对乘飞机出行动了兴致，专门花了点时间研究。

第一等有钱人自己有飞机，按繁西的说法，云上的淫乱派对是私有飞机主的**天赋人权**。和曦想想舅舅，觉得也不是没有可能的。第二起有钱人租飞机。然而不管多有钱，与繁好一比？呃，比不了，根本不是同类。

两人不再言语，静静看着洋中的白浪变大变巨。繁西忽然笑了，和曦就问为什么，他反而扭捏了一下说，“我怕说不好，只不过一直看明月随便乱想到的。我看着这月，看它将月光洒在艇上，大洋上，浪尖上，海岛的沙滩上，觉得很美，忍不住想到一百年后，三百年后，三千年后我们也许早死了，但未来人类如果碰巧也处于与我们一样的月夜，不免也会生出和我一样的情感。如果一个我根本不认识的未来人类与我生出同样情感，到底他是繁西，我是繁西？他又何尝不是我，我也不见得就不是他。一想到这里，我只觉得似乎构成我灵魂的一部分始终活着，活在未来人类的身体里，仿佛从未真正/完全死去。哈哈，太蠢了，我表达不出，只有等别人也看到我眼前的海上明月夜才能明白。”

是的，和曦想，“晚餐时逗他，逗他说只有有钱人才能把后代传下去。这也是永生唯一的方法。他就告诉你另一番理论。所以，这世上居然有人奇怪，**我为什么爱他？**”

虽然爱他，他仍然是头号混蛋，臭流氓，不和我去国外玩的懒鬼！都怪那倒头Residence Class，在迪拜的休息室又出了乱子！

和曦在那次事件中受的冲击一点不比繁西小，只不过她还没意识到。飞机在迪拜暂停两个小时，所以和曦、繁西得以体验只属于两人的休息室和专属的地面butler。飞机上的套房就已足够奢华，地面lounge配得上地球上的任何帝王。和大厨交谈了一会儿，在butler殷勤服务下，繁西也渐渐忘记了之前的一点不快。谁想到这时候繁西看到了不该看到的，受了刺激，再也不想豪奢出遊。见鬼，天文数字的单程票竟然还能出这种疏忽，该死的航空公司！和曦只想告诫为有钱人服务的公司：千万千万要审查你们电视的片源，因为总有像繁西一样的软蛋会不小心发现世界的真相，Ignorance is blessing。在你的顾客享受帝王晚餐时，千万别让电视上出现新闻，因为新闻有可能，就像两人正巧看到的那样，出现某个撒哈拉以南黑人儿童因为缺少一两美元的药品正在痛苦中死亡。繁西在回程的路上再没有开口说一个字，在看到那对充满恐惧、孤独、绝望的眼睛后。

// 骨瘦如柴，眼睛比例等
// 加公司融资：繁西：创业公司就是杀父仇人+出卖灵魂也要尽可能融资（但繁西行为没有话语坚定，远不如后来的和曦
// 太多（假）笑，穿过25道门的lounge后的新世界，飞行的过程还可能略详细一点点。
// 今天统计了一下字数，才发现写的比预想多了七八千字。。。唉。。。估计又要分章，明年写任何章节，一定要控制住。
// 比预料多出的 1）孟任日本行 2）繁好的月光艇 3）和书记的具体性交细节 4）松江世家，但也略去了很多之前想写的
// 加一：两人从众多排队人羡慕的眼神中进入饭店，和曦讲，这饭店网上有预定的唯一目的是让人不能发现95%拿着预约单进入者都是关系户。
// 加一：史学界对为什么只有中国存在动辄两三千年的世家不感兴趣。而这，在和曦看来，却是历史的大问题。
// 加二：不久前航空公司将痛经女子赶下飞机，理由当然是冠冕堂皇的飞机上无相关医护人员，为顾客安全考虑云云。。。但只要给够钱，想来就算和曦想在飞机上生孩子也可以。