// 2024-11-15
// 繁娃醒悟时刻：1. 12星座恋爱运势表  2. wedding cake consultation 不但不会做，也完全想不到，这是她的宇宙中不存在的事务，永远也不可能想到，不可能去做的，以后再去美国欧洲，不管遇见什么，都没给她这份震憾，因为其它都可以从书上，报纸上读到。这个做梦也没想到过。

曦园初建时，和曦与正常人一致，盼着大、盼着气派、盼着眨眼就已建好住进来。

等真的住进来，兴奋的喘息稍过。她尴尬地发现，自己只有一个屁股，连房间一角的躺椅都填不满，何况整个城堡。

是的，和曦的房子光顾着气派，外观多多少少像中世纪欧洲古堡，也和那些古堡一样，平时只邀请鬼怪居住。

为了治疗恐惧，和曦光速修缮，将城堡中间，三楼四楼五楼每层隔离出三四个房间，新建墙垣。晚上时，只要将三楼的入口一闭，这十几个房间就形成独立的一套，自成一统，不与外界音信。

和曦还怕。躺床上，不像在闺房，像仰在仓库。于是又光速改造。

勉强安心时，她自嘲已住在套中套中套中套。就算有一百个敌兵，也休想冲进来立刻把她搜出来。和曦去过江苏电视台，去过南京电视台，陪爸爸去过教育台，觉得所有电视台加起来都不如自己亲手打造的迷宫。

于是花费很长时间给卧室起名。葱管最后停留在“洞房”二字上。
//因为是套中套中套中套

和曦当然知道这会引起疑惑。要的就是这种感觉，偶尔，一辈子一两回，高高在上，看着俗人张大嘴角流口水的蠢样。

洞房，至少在上古、中古时，与后来不同。唐人曰：“市言唯恐田园陂地之不广也，簪珥羽钿之不侈也，洞房绮闼之不邃也”。是了，洞房与绮闼对偶，邃才是洞房之骨，不读书的俗人哪里懂得。

// 如果有另一个我，和曦想，必须先错愕，然后思索，最后恍然。

繁娃不晓得这番由来，就见洞房二字怪怪的，旋即想到屈原杜甫也用。如此说来，自己确实有可能刻意使用这字眼。“看吧，我果然也可能是那什么倒头和曦。”
//从繁，伏羲氏之胤，变成和，高辛氏，子姓，帝俊的子孙。另一个地方偶然想到
// 2024-11-09 
坐在桌前，繁娃自然地伸左手向抽屉。

不开。。。她不知道昨天就卡住了，而和曦还未喊人来看。

于是更努力试了试，咔咔直响，抽屉开了。

但被一团白雾遮蔽。这。。。怪事太多了，繁娃渐渐觉得这才是常态。

手探雾团，手便消失了。。。准确地说，手的感觉消失了。一片虚无。

繁娃惊瞿抽手。等抽离雾气时，手又回来了。

常态。。。她反而调皮起来，又把手探进去，又抽出来，咯咯笑。

终于，愤怒撞头的声音突然在她脑中尖啸，

“无礼的偷窥者，受死吧！！！”

繁娃害怕了五秒，等待着惩罚。结果？结果并未到来。

一个法术机关罢了，没什么好怕的。甚至。。。可以欺负。

于是又进入了抽屉。想像着手指在其中撩拨。

那声音疯了，喘着粗气，摔破嗓子，吼道，

“唱起来，唱出来！死变态！”

一道道符文凭空眼前，带着无光的深邃。

[quote, attribution, "citation title and information"]
----
ᚾᚪ ᚾᛖ ᚠᚩᚱᚷᛁᚠᛖ ᛁᚳ ᚦᛖ
ᚾᚪ ᚾᛖ ᛏᚱᚢᚳᛁᚷᛖ ᛁᚳ ᚦᛖ
ᚾᚪ ᚾᛖ ᛋᚹᛁᚳᛖ ᛁᚳ ᚦᛖ ᚾᛖ ᚠᚩᚱᛋᚳᚱᛁᚠᛖ
ᚾᚪ ᚾᛖ ᚹᛖᛈᛋᛏ ᚦᚢ ᚠᚩᚱ ᛘᛖ
ᚾᚪ ᚾᛖ ᚠᚩᚱᛚᚩᛖᛏᛖ ᛁᚳ ᚦᛖ
ᚾᚪ ᚾᛖ ᛞᚱᛖᚠᛖ ᛁᚳ ᚦᛖ ᚾᛖ ᚷᛖᛚᛖᚩᚷᛖ
----

这。。。这，无约而至的千年文字令她动念，血液不受抑制的冲上大脑，心脏随着喘息悸动。

这是符文，维京。。。不，北日尔曼符文。
// 瞎写的，不用考证。应该是盎格鲁 弗里西亚符文，属于北日尔曼符文。

是的，繁娃疑惑地自问，never give me，不，有格。。。 ich þē，never give 与格单数you I。

“唱出来，大声唱出来！亵渎者！”

会的，我会的。。。于是唱道：
[quote, attribution, "citation title and information"]
----
nā ne forġife iċ þē
nā ne truciġe iċ þē
nā ne swīce iċ þē ne forsċrīfe
nā ne wēpst þū for mē
nā ne forlǣte ic þē
nā ne drēfe iċ þē ne ġelēoge
----
// 中计了，嘲弄
// 2024-11-10
阴森的声音又来，这次夹带了不小的嘲弄，

“唱吧，唱吧。你中计了！笨蛋！”

可惜繁娃已然无法停止，热血翻涌，浑身颤抖，干脆从头唱起，
[quote, attribution, "citation title and information"]
----
Lufu nis unc uncūð
Þū wāst þā þēawas ond ēac iċ wāt
full ġefæstnung is mīn rǣd lā
nān ōðer wer ne ġeseleð þis þē
...
----

一曲渐渐终了。繁娃面红耳赤，脸红到可以上台演关公。堕入无尽的羞耻深渊。

繁娃**自以为**并非极端人士，虽不喜欢庸俗，但喜欢唱歌，可以忍受流行歌曲，不论如何甜腻。

初见高古幽奥，以千百年前的符文写成。唱一两句后，繁娃就知上当，这首歌分明是用北欧符文写成的当代口水歌。

但一般的流行歌曲，不至如此委屈。

这不是一般的歌曲，歌词本身带着暗黑的魔力。
// 不畅

// 2024-11-14
必须特定的曲调、必须特定的符文、以及必须自己演唱，才能触发这道黑暗魔法。繁娃因此觉得这是有人刻意为自己设计的。

如此严苛的使用范围，这道法术就此拥有强大的邪恶力量也就一点也不出奇。

繁娃生平极少害羞，但这是魔法直接的精神污染，一旦中术，就无可抵挡。短短的几分钟，她止不住地想逃离地球，从此削迹人寰。

繁娃捧着赤胀的面庞，缩成小小一球。这时还没意识到，经此一役，她彻底失去了羞赧的能力。

不远的将来，当她面对形形色色猥琐油腻的男子时，脱衣、赤裸、用脚勾上男人脖子的速度快得像变魔术。那时，她又觉得这是一种难得的优点了。

耻辱的感觉渐渐消化，她看向抽屉，白雾已散。因为好奇，而中计的她发现抽屉里的东西

平平无奇。

或者说，正常姑娘的抽屉。

// 2024-11-26
几支眉笔，小镜子，口红若干，还有个大卷发棒。零钱和几支钢笔加杂其间。

繁娃将每支笔都捏上来细看，又放回去，心知不便宜。有支用了大漆螺钿的尤为熠熠。繁娃旋开笔，用手背试试粗细。很好，是我喜欢的1.0，还有湖蓝墨水，当然商品名多半是瓦尔登湖蓝。不知放了多久，仍然没有断线，一划出水。如果我有钱，大概一定会拥有吧。

关了这一扇，去开下一扇。这一层满满摆着各种本子，几倍于上一层的笔，还有尺子和计算器。繁娃手快，先捡起玉印。

镜像的篆字不好认呀，她感叹。又一次牺牲手背，看看。唉，无非“和曦”、“和曦御赏”之类。依然没有线索。

有一枚长玺，繁娃盖在右手背上，八个字，是？“乃命和曦钦若昊天”

尚书上面的，尧典？她想着自语，‘于是命令和曦，去钦近昊天’。昊天，伏羲氏吧。但有点不对，原文好像不是这样的。刚要细想，一阵剧烈的头疼传来。

扶额冷笑，算了，无非小女生的绮思。

要说小女生的绮思，这本才是集大成者！繁娃捂嘴笑着，从抽屉深处抽出表面嵌着水钻，中学女生人手一册，带着铜锁，光闪闪的日记本。

刚想着如何破锁，里面的绮梦已经迫不及待，五颜六色，齐齐扑到她的脸上，隔断了她的视线，阻碍着她的呼吸。

她反而犹豫了。她突然想起好像是弗洛伊德记录过这样一梦：有位未经人事的少女，梦到全身赤裸，开腿躺在床上。而她的床前，或者说腿前，一群野兽，有狮子老虎，排着队，急切的想进入她女性的入口。

如果我是这位和曦就算了，如果不是，又看到类似春梦，不是让他人难堪吗？繁娃想，并不是所有人都像我一样，对性没有什么禁忌。

就强压住窥视的念头，随手翻起散落的小本本。

刚翻开第一页，就吓一跳。只见上面堂而皇之的手写道，“宇宙的终极奥义是什么？。。。”问号之后的点点点，一点更比一点更重，更圆，更犹疑。

42，繁娃认真回忆了一会儿。对，一定是42。

自信翻页来看，结果却是疑问句，78还是19968？

// 2024-11-27 09:30
书写者应该犹豫了良久，也许隔了许多天，换了支笔，勾下了前者。多半觉得还是小的好。

竟然不是42！繁娃有些生气，嘟嘴嘟了有一会儿，又释然笑道，也许和我看的不是同一本小说。

况且原文好像说“生命、宇宙以及任何终极答案”的答案是42，本子上却写成‘宇宙的奥义’，问题不同呢。

奥义，梵语词，中文意译。直译好像是座前？引申为对内弟子的教诲。很少用了，除了日本。繁娃把握不准语义，也许宇宙的公开答案和秘密答案不一样？这也常有。

算了，为什么为无聊的问题操心？她丢开了，又乱翻几页。

一些账目，大开销，买的全不知所谓。繁娃更怀疑了。

又翻了翻，手绘。日本卡通风，人物统统含泪闪光大眼睛。。。好吧，还是少女漫。

无可救药。她硬邦邦地丢了册子。拿起八音盒玩，听了曲子，额，巴赫的D小调Toccata and Fugue。

怪人。

又抓起一册，翻开，又画着好多日本漫画。。。再一本，继续漫画，有些画空白处还标着些数字诸如226、108、23631之类。繁娃捋着鬓角，不得要领。

可能还是账单吧。

打开最下的抽屉，哦，好多证件。

看看最新的那本护照，姓名，照片都是那个和曦。

当然，这不重要，繁娃奇怪的认为，姓名，样貌都不重要，都不是**人**的本质。

不管转世轮回多少次，不管重生多少遍，那个永远不会改变的你，才是你。
