// 几十个房间的建筑，和曦只有一个屁股。当时只顾着气派了。
// 和曦的卧室，自称洞房，因为在套中套中套中套。
// 2024-11-15
当曦园初建时，和曦和正常人一致，只盼着大、盼着气派、盼着眨眼就建好住进来。

等真住进来，兴奋劲稍过。和曦不由尴尬发现，自己只有一个屁股，连房间一角的躺椅都填不下，更别说整个城堡了。

是的，和曦的房子光顾着气派了，外观多多少少像中世纪欧洲古堡，也和那些古堡一样，平时只有鬼怪居住。

为了不害怕，和曦又光速修缮，将城堡中间，三楼四楼五楼每层隔离出三四个房间，新建墙垣。晚上时，只要将三楼的入口一闭，这十几个房间就形成独立的一套，自成一统，不与外界通音信。

和曦还在怕。躺床上，不像在闺房，像仰在仓库。于是又光速改造。

等勉强安心时，她只好自嘲已住在套中套中套中套。就算有一百个敌人，也休想冲进来就能搜出她来。和曦去过江苏电视台，觉得电视台也不如自己亲手打造的迷宫。

于是又花了很长时间给自己的卧室起名。最终葱管停留在“洞房”二字上。

和曦当然知道这会引起疑惑。和曦要的就是这种感觉，偶尔高高在上，看着俗人张大嘴角流口水的蠢样。

洞房，至少在上古、中古时，与后来所指不同。“市言唯恐田园陂地之不广也，簪珥羽钿之不侈也，洞房绮闼之不邃也”。是了，俗人哪里懂屈原杜甫。

// 2024-11-09 
坐在桌前，繁娃自然地伸左手向抽屉。

不开。。。她不知道昨天就卡住了，而和曦还未喊人来看。

于是更努力试了试，咔咔直响，抽屉开了。

但被一团白雾遮蔽。这。。。怪事太多了，繁娃渐渐觉得这才是常态。

手探雾团，手便消失了。。。准确地说，手的感觉消失了。一片虚无。

繁娃惊瞿抽手。等手抽离雾气时，手又回来了。

常态。。。她反而调皮起来，又把手探进去，又抽出来，咯咯笑。

终于，愤怒撞头的声音突然在她脑中尖啸，

“无礼的偷窥者，受死吧！！！”

繁娃害怕了五秒，等待着惩罚。结果？结果并未到来。

一个法术机关罢了，没什么好怕的。甚至。。。可以欺负。

于是又进入了抽屉。想像着手指在其中撩拨。

那声音疯了，喘着粗气，摔破嗓子，吼道，

“唱起来，唱出来！死变态！”

一道道符文凭空眼前，带着无光的深邃。

[quote, attribution, "citation title and information"]
----
ᚾᚪ ᚾᛖ ᚠᚩᚱᚷᛁᚠᛖ ᛁᚳ ᚦᛖ
ᚾᚪ ᚾᛖ ᛏᚱᚢᚳᛁᚷᛖ ᛁᚳ ᚦᛖ
ᚾᚪ ᚾᛖ ᛋᚹᛁᚳᛖ ᛁᚳ ᚦᛖ ᚾᛖ ᚠᚩᚱᛋᚳᚱᛁᚠᛖ
ᚾᚪ ᚾᛖ ᚹᛖᛈᛋᛏ ᚦᚢ ᚠᚩᚱ ᛘᛖ
ᚾᚪ ᚾᛖ ᚠᚩᚱᛚᚩᛖᛏᛖ ᛁᚳ ᚦᛖ
ᚾᚪ ᚾᛖ ᛞᚱᛖᚠᛖ ᛁᚳ ᚦᛖ ᚾᛖ ᚷᛖᛚᛖᚩᚷᛖ
----

这。。。这，无约而至的千年文字令她动念，血液不受抑制的冲上大脑，心脏随着喘息悸动。

这是符文，维京。。。不，北日尔曼符文。
// 瞎写的，不用考证。应该是盎格鲁 弗里西亚符文，属于北日尔曼符文。

是的，繁娃疑惑地自问，never give me，不，有格。。。 ich þē，never give 与格单数you I。

“唱出来，大声唱出来！亵渎者！”

会的，我会的。。。于是唱道：
[quote, attribution, "citation title and information"]
----
nā ne forġife iċ þē
nā ne truciġe iċ þē
nā ne swīce iċ þē ne forsċrīfe
nā ne wēpst þū for mē
nā ne forlǣte ic þē
nā ne drēfe iċ þē ne ġelēoge
----
// 中计了，嘲弄
// 2024-11-10
阴森的声音又来，这次夹带了不小的嘲弄，

“唱吧，唱吧。你中计了！笨蛋！”

可惜繁娃已然无法停止，热血翻涌，浑身颤抖，干脆从头唱起，
[quote, attribution, "citation title and information"]
----
Lufu nis unc uncūð
Þū wāst þā þēawas ond ēac iċ wāt
full ġefæstnung is mīn rǣd lā
nān ōðer wer ne ġeseleð þis þē
...
----

一曲渐渐终了。繁娃面红耳赤，脸红到可以上台演关公。堕入无尽的羞耻深渊。

繁娃*自以为*并非极端人士，虽不喜欢庸俗，但喜欢唱歌，可以忍受流行歌曲，不论如何甜腻。

初见高古幽奥，以千百年前的符文写成。唱一两句后，繁娃就知上当，这首歌分明是用北欧符文写成的当代口水歌。

但一般的流行歌曲，不至如此委屈。

这不是一般的歌曲，歌词本身带着暗黑的魔力。
// 不畅

// 2024-11-14
必须特定的曲调、必须特定的符文、以及必须自己演唱，才能触发这道黑暗魔法。繁娃因此觉得这是有人刻意为自己设计的。

如此严苛的使用范围，这道法术就此拥有强大的邪恶力量也就一点也不出奇。

繁娃生平极少害羞，但这是魔法直接的精神污染，一旦中术，就无可抵挡。短短的几分钟，她止不住地想逃离地球，从此削迹人寰。

繁娃捧着赤胀的面庞，缩成小小一球。这时还没意识到，经此一役，她彻底失去了羞赧的能力。

不远的将来，当她面对形形色色猥琐油腻的男子时，脱衣、赤裸、用脚勾上男人脖子的速度快得像变魔术。那时，她又觉得这是一种难得的优点了。

耻辱的感觉渐渐消化，她看向抽屉，白雾已散。因为好奇，而中计的她发现抽屉里的东西

平平无奇。

或者说，正常姑娘的抽屉。
