// 2024-11-09 
[Verse 1]
Lufu nis unc uncūð
Þū wāst þā þēawas, ond ēac iċ wāt
full ġefæstnung is mīn rǣd lā
nān ōðer wer ne ġeseleð þis þē

[Pre-Chorus]
iċ nille būtan þē mīn mōd areċċan
iċ bidde þē, understand!

[Chorus]

[Verse 2]
iċ cūðe þē swā lange
þīn mōd is ċeariġ ac þū ne dærst cweðan
unc is full swutol þæt hēr nū ġelimpð
unc is þæt gamen lā ful cūð pleġa

[Pre-Chorus 2]
and ġif þū friġne mīnra wilma
ne cweð þe þū ne meaht onġitan

Anglo-Saxon runes
ᛚᚢᚠᚢ ᚾᛁᛋ ᚢᚾᚳ ᚢᚾᚳᚢᛞ
ᚦᚢ ᚹᚪᛋᛏ ᚦᚪ ᚦᛠᚹᚪᛋ, ᚩᚾᛞ ᛠᚳ ᛁᚳ ᚹᚪᛏ
ᚠᚢᛚᛚ ᚷᚩᛖᚠᚪᛋᛏᚾᚢᛝ ᛁᛋ ᛘᛁᚾ ᚱᚩᛖᛞ ᛚᚪ
ᚾᚪᚾ ᚩᛞᛖᚱ ᚹᛖᚱ ᚾᛖ ᚷᛖᛋᛖᛚᛞ ᚦᛁᛋ ᚦᛖ
ᛁᚳ ᚾᛁᛚᛚᛖ ᛒᚢᛏᚪᚾ ᚦᛖ ᛘᛁᚾ ᛘᚩᛞ ᚪᚱᛖᚳᚳᚪᚾ
ᛁᚳ ᛒᛁᛞᛞᛖ ᚦᛖ, ᚢᚾᛞᛖᚱᛋᛏᚪᚾᛞ

// 和曦的卧室，自称洞房，因为在套中套中套中套。

坐在桌前，繁娃自然地伸左手向抽屉。

不开。。。她不知道昨天就卡住了，而和曦还未喊人来看。

于是更努力试了试，咔咔直响，抽屉开了。

但被一团白雾遮蔽。这。。。怪事太多了，繁娃渐渐觉得这才是常态。

手探雾团，手便消失了。。。准确地说，手的感觉消失了。一片虚无。

繁娃惊瞿抽手。等手抽离雾气时，手又回来了。

常态。。。她反而调皮起来，又把手探进去，又抽出来，咯咯笑。

终于，愤怒撞头的声音突然在她脑中尖啸，

“无礼的偷窥者，受死吧！！！”

繁娃害怕了五秒，等待惩罚。结果？结果并未到来。

一个法术机关罢了，没什么好怕的。甚至。。。可以欺负她。

于是又进入了抽屉。想像着手指在其中撩拨。

那声音疯了，喘着粗气，摔破嗓子，吼道，

“唱起来，唱出来！偷窥者！”

一道道符文凭空眼前，带着无光的深邃。

[quote, attribution, "citation title and information"]
----
ᚾᚪ ᚾᛖ ᚠᚩᚱᚷᛁᚠᛖ ᛁᚳ ᚦᛖ
ᚾᚪ ᚾᛖ ᛏᚱᚢᚳᛁᚷᛖ ᛁᚳ ᚦᛖ
ᚾᚪ ᚾᛖ ᛋᚹᛁᚳᛖ ᛁᚳ ᚦᛖ ᚾᛖ ᚠᚩᚱᛋᚳᚱᛁᚠᛖ
ᚾᚪ ᚾᛖ ᚹᛖᛈᛋᛏ ᚦᚢ ᚠᚩᚱ ᛘᛖ
ᚾᚪ ᚾᛖ ᚠᚩᚱᛚᚩᛖᛏᛖ ᛁᚳ ᚦᛖ
ᚾᚪ ᚾᛖ ᛞᚱᛖᚠᛖ ᛁᚳ ᚦᛖ ᚾᛖ ᚷᛖᛚᛖᚩᚷᛖ
----

这。。。这，无约而至的古老文字令她动念，血液不受抑制的冲上大脑，心脏随着喘息悸动。

这是符文，北欧维金。。。不，北日尔曼符文。
// 瞎写的，不用考证。应该是盎格鲁 弗里西亚符文，属于北日尔曼符文。

是的，繁娃疑惑地自问，never give me，不有格的。。。 ich þē，never give you I。

“唱出来，大声唱出来！亵渎者！”

会的，我会的。。。于是唱道：
[quote, attribution, "citation title and information"]
----
nā ne forġife iċ þē
nā ne truc(i)ġe iċ þē
nā ne swīce iċ þē ne forsċrīfe
nā ne wēpst þū for mē
nā ne forlǣte ic þē
nā ne drēfe iċ þē ne (ġe)lēoge
----
// 中计了，嘲弄
