= 猫咪咖啡馆

:docdate: 2018年/2月/15日

“猫咪咖啡馆？猫咪咖啡馆？在哪呢？”赵思琪攥着杂志，立在路的尽头，东张西望。不会地址印错了吧？

路已至尽头，这条街也没听说有岔路，难道错过了？赵思琪扭转脚踝，面向来路。

右手是路面，左手是一处深深庭院，南京随处可见的民国小楼，掩在藤萝爬满的栅栏后。街上行人不多，倒是运处有数个工人搭起塔架粉刷墙壁。另一些人忙着铺排马赛克转，钉设线条。嘻嘻，这么一搞，这些八九十年代的老破楼还挺好看的，真没想到，赵思琪想，仅仅靠刷上两种鲜明互补的颜色，竟意外的抓眼。
// 不满，另赵的想法不能使用过多的文学词汇

又见街对面有两个丫头在跳皮筋，丢沙包，赵思琪望了一会儿，呆呆吐出一口气，一时间仿佛与儿时的自己在这旧巷斜阳里不期而遇。只可惜那时的自己早已遗失，连模糊的影子都无可寻觅。

//2019-11-16 两拨老者过来。拊髀雀跃，在此生活几十年，近来连姓字已忘，哪知道猫咖呢？

右手遮住太阳，笑着穿过道路，走向两个小娃儿，“嗨！你们两个！知道猫咪咖啡馆怎么走么？”

“不晓得！孟姐姐说了，问人要讲礼貌，方方最乖的。”胖丫头扭过去，不看赵思琪，弯腰去拾毽子。

扎小辫的胖丫头抱着皮球，迎了来，“圆圆知道。孟姐姐说回答别人也要礼貌的。姐姐你刚才站的地方就是，只不过咖啡馆在院子里，被树挡了。姐姐还请别大声喊，这时间孟姐姐多半在午睡哩。”

好笑！我赵思琪还需要听两个矮冬瓜教训？回头望望来处，果然院子里有个招牌，一行字透出盘屈XX的枝叶。“爪白白咖啡馆？”赵思琪多少疑惑。

方方也走了来，“孟姐姐说了，一个东西有两个名字很正常。就像方方是个乖孩子，又叫方方一样。爪白白咖啡馆就是猫咪咖啡馆，猫咪咖啡馆也叫爪白白。不信看招牌上还有许许多白小爪子呢。”

笑嘻嘻谢过两个丫头，赵思琪咚咚咚跑过街，穿过院门，边跑边想，“此间人为什么全都傻傻的？”

// 2/28
果然好多白爪子，笑了，又见一朵朵白爪爪渐渐从半空中的招牌上延蔓汇聚至紧闭大门的右侧。倾身，只见一个没有标识的圆形按钮被三个跃跃欲试的猫爪簇拥。呃？难不成？赵思琪忍不住学着猫爪的暗示按下电锯。大门发出嘎嘎响声，慢慢顺着轨道挪开。

赵思琪于是走了进去，愣住。谁能想到，大门之后竟是另一道大门。

这。。。忽听右手有响动，转头，只见两个姑娘站在吧台对自己笑。其中一个红朴朴脸的女孩子对自己点头，“才到啊！等你好久了！”
//不畅

// 3/4
连续两天未睡午觉的孟任很暴躁，想咬人。看看面前啰啰嗦嗦争讼的两个人，有心打断，又觉得失礼，只好强忍住，想昨天的事情。

昨天的事更头大。自从将小店街道路封闭，改成步行街之后，孟任中心始终难安。打造步行街固然有一千种好处，一万种必要，但肆意破坏城市交通这一条在她心中挥之不去。
// 小店街特殊交通问题，和街道收费问题放到领地巡视一章

集思广益之下，孟任自以为找到了最佳方案：地下隧道。

小店街地理环境特殊，整条街位于一座小小丘陵之上，所以有人提议从小店街所有的广州路的山脚处开挖一条隧道，直接穿到金银街/北京西路的某处，一劳永逸地解决小店街过于狭窄逼仄，行人与机动车永恒的恶斗。

于是昨日清晨，孟任召集了小店街所有商家，住户代表以及热心公益的活跃份子开会，探讨这个方案的最大挑战，当然也是任何项目的天敌——*钱从哪里来？*

那些家伙有意气朕！孟任拍了桌子！眼前的两个吓了一跳，惊疑不定。抱歉，抱歉！不是说你们。好几年没听过如此精妙绝伦的辩论了，你们请继续。孟任不无尴尬地编成一团，耳朵趴下，让自己看上去不仅小小的，还很可爱哩。

那么多问题可以讨论，就算不谈钱，那么谈谈如何估计预算，如何勘探地理水文，如何满足法律法规要求，对了，他们说挖一切洞穴都归什么倒头人防管，也不知是不是。

就算讨论一下隧道两端出入口具体地点的选择也好哇，如果直接与道路连接，那么需要与交通部门沟通，若是借用已经挖有地下停车场的大单位现成出口，那得找这些口子上的负责人。。。吧。谁能想到昨天早上的讨论从一开始就跑偏了。。。直到太阳西下。

// 3/5
奇怪了，奇怪了！那人为何还未到？

昨日一定撞了太岁，诸事不谐。所以今日特地早起，打了一卦，大吉！今日有吉士相访。打卦就是这样，藏起来，不轻动，偶尔算上一卦没有不准的。这位传说中的佳士多半是来共襄义举，XX革命的。

昨天刚揭晓计划的时候，倒博得了满场赞誉。立刻有人跟上提议：既然挖山建隧道，不如乘势，再修建个地下停车场，供居民、商家使用。

任何大工程开工的成本很高，但顺便多挖个停车场也许只需用到预算的十分之一、五分之一，十分划算，性价比高，停车场车位按居民户数100%配比好了。以后小店街人车彻底分离，居住环境自然水涨船高。

言之有理。孟任听了总要矜持一会儿，摆出凝重的姿态，再点头，像平时一样。所以被人抢了先。又一个女子站了出来，反对。

她说，在城市中心本不必要开车，尤其南京这种公共交通发达的都市。她说，居民中只有5%有车，都是王可可那样的有钱人也说明了这一点。她说，有钱人为了自己方便，却把别人置于危险的境地，我们不能助长这种行为。她说，95%的小店街居民可以无需汽车好好地活着，有钱人就算没有车难道活得还能比常人更艰难？你如果喜欢开车乱晃，何不在郊区买别墅，大路朝天，随便开，又何必非要屈尊挤到小店街上来？她说，其它地方她管不了，但小店街上还可以听到穷人的心声。她说小店街上的人可不像外面的，从小被阔佬请的理论家洗脑，把拥有私人汽车当成天赋人权！她对着所有在场的母亲哭诉，询问她们一生之中，是否常常担心满地乱跑玩耍的孩子被各路无法无天的驾驶者撞倒？她不问她们是否注意到了，许多司机的驾驶习惯是冲着人群，狂按喇叭，知道行人会像四下躲闪的蟑螂一样在最后一刻跳开！

这一番话治愈了全场的嘈杂，只留下凄厉的余韵在会场上空往返周旋。幸好，被点名的王可可蹦了出来。谁都知道，钱包鼓涨的速度可赶不上她脾气的增长。她与她家的三台车完全不能忍受别人的任何指点。而自从王可可发家后以来，她在很多人心中也成了正确的化身，支持者甚众。

王可可和她的支持者，攻击那女子分裂人群，暴露了搞阶级斗争的野心，她们还数落那女人愚蠢，建地下车库正是为了让母亲们不用担心淘气的孩子。她们指出人类的正常欲望是无法强行抑制的，有钱了，让生活更舒适便利正属于此。强行压抑只会适得其反，与其堵不如疏，小店街属于大家，决策万万不能被某些空谈正义之辈裹挟。。。

于是议题偏离了路线，争吵持续了整整一天，幸好孟任始终在场，不然只怕会发生流血事件。最终舆论渐渐向意见极端者倾斜，如同大多数群众运动。。。

孟任头大如斗。

“想不到你这么年轻，还怪漂亮的。”白葭里娓又瞄了赵思琪一眼，“还在上学吧。对了我叫白葭里娓，白葭是姓。不是你们汉人。你要是嫌啰嗦，不妨喊我里娓好了。”

“今天，，，今天下午没课。”赵思琪可以控制嘴巴，可管不住不断涨红的腮红。

白葭里娓善意地笑了，拉着她的手问东问西。得知她的学校是个编号七十多的高中时，更笑，“那里去不去倒也无大碍。”

// 3/6
说着，白葭里娓往墙上一按，赵思琪进来的第一道大门应声缓缓关闭。就在此时，一只白白爪子从门外伸进来，啪的拍在门上，自动门于是改变了方向，又哗哗敞开大口。白爪子的主人随即雄纠纠，气昂昂的挺着胸脯子跑进大门，竖着骄傲的卷尾巴，分明是一只纯白大公狗。

接下来的一幕令赵思琪刻骨难忘。喵喵喵、喵喵喵，毫无纪律的乱叫着，一只又一只毛绒绒的小猫咪跟着打头的大狗鱼贯进入前厅，而为这支杂乱无章队伍殿后的又一只纯白母狗也摇着尾巴进来。

哦哦哦哦哦～，被毛绒绒几吨可爱击中，赵思琪差点晕过去，“牧猫犬？？？”她不禁想。刚要开口，就见里娓蹲下去，嘻嘻嘻笑，伸手去摸，“乔乔，今天又贪玩了，现在才回来呀。”

那领头的大公狗一见里娓，疯了似的就扑过来，在她怀里乱蹭、温存、打滚、舔手，嘴里不停呜呜长啸。

哪知殿后的母狗不开心了，汪汪凶吼，正撒娇的乔乔狗听了，只得离开，前往第二道门口，坐下排队。

赵思琪努力托着下巴看一只又一只小猫咪在母狗的号令下东摇西倒的勉强排成一线。

白葭里娓抿嘴偷笑，“孟孟，你也忒认真了，依我看，不用点，一只都没少。”

母狗回头，不服气，低沉地吼叫。里娓于是与她议论了一会儿，终被且长且短的犬吠声打败，笑着让步，“好好好，只是请你带快点，有客人等着进去呢。”

名为“孟孟”的母狗一愣，似乎忘记了之前的计数，迟疑片刻，只好又凑到公狗旁蹭蹭闻闻，再凑到小猫身上闻闻蹭蹭，从头点数。将小猫一一点毕，母狗凝神回忆，忽然汪汪大叫，一道烟奔了出去。

“抱歉呀，最后**臭繁西**老想逃跑，所以门禁电脑设定的特别严，大门不关上，二门就不会开。看样子只是王可可又溜了，孟孟很快就会将她抓回来。”白葭里娓转身对赵思琪解释。呵呵，呵呵，完全不知道臭繁西、王可可为何物的赵思琪只好干干地陪笑。

孟孟狗奔出去之后，乔乔复活了，先是撩拨身后的猫孩子，可猫咪们已安静下来，乖乖趴在地砖上等妈妈，守纪律。乔乔只好钻进里娓的长裙，围着她的脚趾舔，把她逗得格格直笑。忽然，乔乔发现了新人，想起自己的工作，一路小跑到吧台后，叼着一块木牌子出来。
//里娓的服饰别忘记补上

摇尾巴，昂着头，尽全力将牌子举高，奔来。赵思琪凑近一看，庆幸自己从不戴眼镜。谁能想到那木牌子上的竟是广告：一家小火锅店和一家**正宗**的南京菜馆。

赵思琪立刻像正常路人一样，无法抗拒。弯腰摸摸乔乔的耳朵，抱着他一顿亲，告诉他一定会去他们家的饭店拜访。然而任凭赵思琪如何努力，乔乔总不肯放下牌子。赵思琪不得法，只得保持弯腰的姿势看向白葭里娓，向她求援。里娓指指牌子上的二维码，赵思琪于是省悟，掏出手机扫码，地图立时弹出，标出了两家店的位置和前往路线。赵思琪看看，原来也在这街上，很近，街头到巷尾的距离。

乔乔满意了，放下牌子，伸出爪爪。赵思琪嗷嗷两声，赶忙与他握爪。

孟孟狗这时也回来了，嘴里叼着只小小花豹。花。。。花豹？金钱豹？赵思琪一日之内惊吓太过，能够惊诧的神经暂时疲惫，对不断输入的刺激不再敏感，只余下疑惑重重。

好了，人齐了，大家直起身等待大门关闭。不料乔乔鼻尖又耸，不顾孟孟的反对，重新叼上广告板，冲出大门，拦住了门外经过的数个韩国女留学生。

小店街毗临南京大学留学生宿舍，这里韩国女留学生从不稀奇。稀奇的是，人们总能一眼就将她们分辨出来。

韩国女子也像一切人类，长有一对美丽的眼睛，只奇怪她们的眼睛并非为了寻找世间的美而生。小店街上的韩国女留学生，不分来历背景，燕瘦环肥，统统摒弃自然母亲赐予她们的天然风姿，只向同一种美伏首：商人广告狂轰滥炸之下的大一统容貌。这种标准的商人美要求女性戴上面具，皮肤像死尸一样惨白。至于嘴唇也一定要像恐怖片中的死尸鲜艳的红。据说如此浓妆会显得精神百倍。只是“精神百倍”这种东西如果发现在死尸脸上。。。总之，喊出**“古来万事贵天生”**的李白定不会欣赏她们。

孟孟狗等的不耐，坐到大门门线上，放下口中挣扎不休，鬼叫连连的小花豹，用一只爪子拍牢，再汪汪催促。然而，招揽顾客是乔乔唯一敢于违抗孟孟的时刻。

孟孟无奈，又见猫娃儿个个抓耳挠腮，知道时间大了，于是再次清声发令，驱走了规矩。轰的一声，树倒猢狲散，几只猫儿化身橙色、青色、白色的闪电，在小小门厅左突右蹙。剩下的打呵欠、磨爪爪、敲脑袋、闻屁股、捉尾巴不一而足。赵思琪也学里娓，蹲下来，与小猫咪一一招呼，爱抚。

// 3/8 
抚摸小猫，心神宁定，一切都变得似水晶般清澈透明。门外鸟儿的鸣唱，囧窗间泥土青草的芬芳纤毫可辨。一阵又一阵时而兴奋激动时而低昂压抑的声浪传来，隐隐可知是外国话。

赵思琪然而脸红，从那些外国女人的表现上看，自己刚才也多半失态的不行。“好恶心，这些外国女人，一点不矜持，没见过世面，不就是狗叼广告牌嘛。。。鬼喊鬼叫的，像做那。。。那什么一样，呸！”批评完韩国人，赵思琪心下稍愈。又见乔乔伸出爪子，留学生嗷嗷的上去握，“哼，那狗爪子不知道踩过多少泥，多少痰，扒过多少屎尿，你们还真不讲究，对了，我好像也。。。”

此时白葭里娓又侧过来，不无羡慕地道，“这对狗是王可可家的，从小孟姐姐训练出来，有两个本事。一是搜寻流浪猫狗弃养的幼崽，将之带大。狗妈妈教出的猫咪也像狗狗一样听话。二是招徕顾客，王可可家两爿饭店靠这两位天天爆满，翻台几趟呢，小店街上就数她家首富。”

事实上，这对狗，公狗乔乔母狗孟孟是王可可的新婚礼物。

新婚的时候，王可可的丈夫见她眉宇间只有强装出来的喜悦，思来想去，忽然记起她初来小店街时的事情。

那一日深夜，还不适应机器人生活的服务员王可可披着寒冷的清光返回拥有八九个舍友的集体宿舍。此时的漫天星光只愿意照见她心中酸楚无限。经过垃圾箱时，意外看到一团灰黑色的肉块蠕动，定睛细看，原来是只狗仔，一只眼流脓，身上随处斑秃疤痕。

很多年后，王可可每次回忆都认定这是被人用烟头一个又一个缓缓烫出的。世界上最贫穷的人，体验过极度艰难的人类常常有最大的爱心，王可可只犹豫了三秒，毅然地将小狗带回。

花光了预支的薪水，小狗不旦活了下来，眼睛也好了，毛光光皮实实，十分活泼可爱，最意外的是，他竟然是只纯白的狗子。

又一日，王可可又一次工作到深夜，宿友忘了关门，小狗溜出来找妈妈。等发现时，他已变成路中央冰冷僵硬的尸体。

王可可崩溃了，扶着尸体，三天三夜未下床。最后还多亏了孟任，成立起“王可可帮助小组。”小组的头一件事——孟任自任组内的唯一领导小组长。然后小组长发令，动员素来与王可可亲爱的女服务员轮班日夜陪伴，陪她说话，陪她家务，逼她工作，让她没有任何时间独处思考悲哀。如此戚戚哀哀半年，她才恢复常态。

新婚的丈夫想起此事，决定送两只纯白的狗给妻子。所以花了一万多托朋友购买。是的，在中国，花钱最快的办法永远是托朋友代购。这朋友如此可靠，真的送来一对纯白无一根杂毛的小狗，绝对不是市场上常见骗新手的染色病狗。

王可可倒不在乎狗的品种 ，如她丈夫所料，爱死了这一对。想起孟任，于是给其中的母狗取名孟孟，又抱着公狗半天，不避任何人的目光，命名为乔乔。

然而小饭店的老板娘注定没有每日溜狗的闲暇。

// 3/9
所以几年来这对狗每日上午随王可可夫妇出门，自行跑到孟任处，再领着一队他俩带大的小猫到小店街荒弃的后山玩，日中返回，吃肉梳洗睡觉，下午再出门四处招揽顾客。到四、五点时，王可可家的饭店就可以爆满。两只狗于是卸下职责，趴在饭店外的木架上对着小店街望呆，大嚼王可可买来的进口带骨牛肉。

为家庭努力工作，得到进口牛肉的回报，这一切看上去完美。只可惜不久前，有些外国留学生过来拍了视频传到youtube上，大部分观众哈哈一乐，可总有正义感特强，习惯告奸的正义人士传言：广告牌是用钉子钉在狗嘴上的。

外国人里总有一部分被伟大的基督精神感召，他们一生不做任何事情，除了证明自己比别人圣洁。所以有几个在宁的外国人，突然成为了世上顶顶的爱狗人士，专程跑来小店街。等他们发现任何正常智力的人类都可以推断出的事实：广告牌并非钉在狗的牙床之上，他们娴熟地切换了抗议姿势，转而举着牌子在饭店门口静坐，牌子上还写有神奇的外国大字：**Work or Wok?**
// 这一段源于真实事件

可怜小店街上民众教育程度太低，竟无法领会外国大爷精妙无双的Pun。孟任苦苦翻烂手边的英文字典也不得要领，只好请教和曦。和曦看了，哈哈大笑，愉快地吊起了书袋，“Wok是粤语的镬，就是锅子啦，啊，这你也知道？广东人跑到美国开饭店，早年常常按粤语将镬拼成英文写在招牌上。那个结尾的K想来就是粤语表现入声的舌塞音，同样的还有白菜bok choy。这些都不是正经的英语，所以很多字典不收。但美国人只要看到Wok就知道是中餐馆，所以现在墨西哥人开中餐也会写上这个Wok。真正的中国人为了与他们区别，反而不再用了。”见孟任的眼睛已经晕迷，更乐，“说起来那外国佬挺有才，意思是这些狗如不**工作**就会给炖到**锅**里去。骂王可可逼狗劳作，顺便骂中国人吃狗肉。”

// 3/12
谁都知道孟任最敬畏外国人，听了和曦的解释，倒想劝王可可。只是王可可已非吴下阿蒙，像所有无辜单纯的人遭遇诬陷时一样，她火冒三丈，指着抗议者一顿骂，说她最爱狗，一辈子从未起过，哪怕一次吃狗肉的念头。难道有人吃狗就代表所有中国人都吃狗肉？中国人吃狗，你跑我家抗议，美国人吃牛肉，你怎么不跑白宫抗议？越骂越气，当即指挥两条狗出去咬人。

一阵鸡飞狗跳之后，两狗欢乐地舔拭爪子，毫不内疚地品尝趾间的血液。天哪！多么无知且狼心狗肺的畜生，这些血液属于把全部身心血肉都为狗狗着想的犬中圣马丁、玻利瓦尔啊！

// 3/16
进了二门，赵思琪倒吸一口凉气，“好宽敞。”在外面看不出，进来方知这家咖啡馆以回字型设计，几乎占据了整个院落
//不知怎么描写，这牵涉到开头对这里的印象。
// 旧房子和玻璃新的阳光房融为一体
// 违建
“来了，来了！”一群女孩子笑嘻嘻跑出来，有的牵狗，有的抓猫，顺便扭头与白葭里娓打招呼，更有两位笑着说，“直接把客人领上去吧，孟姐姐一会功夫催问几遍了。”

于是又来到二楼，穿过架在半空长长的木甬道。一时间，阳光搅起树影，挥洒陪伴她们。赵思琪伸出小手去捉，暖风从她指间蜿蜒游走，只余下醺醺的二人。

于是进了东北的角屋。靠门的地方，横七竖八躺着八九张沙发，符合最近流行灰冷色调的“北欧风”。又是一群女孩子或坐或卧，有的看书翻杂志，有的吃零食，有些对着小镜子补妆，更多的捧着手机消磨。

沙发区后，靠近北窗，有一男一女，也不从面前的凳子，站在那里指手划脚，动了意气。这两个身前对着张木桌，也是现在流行的时尚，漆成白橡木色。桌子后坐着个小姑娘，满脸的不耐烦，一看就不是个正经的女姑娘。
// 少服饰

“哎哟，你们两位还在争哪！”白葭里娓不客气地打断，笑道，“我下去的时候是你们二位，谁想到回来还是你们二位。李梅姐你也是老前辈了，怎么还不知道每天多少起人来找孟姐姐？照你们这样争下去，孟姐姐不要吃饭啦！”

男子闻言回头，赵思琪这才发现他深目高眉，不似中原人。只见他无奈地搔头，“不怪我，是园长太顽固，也不懂我们的民族习惯，明明从小学到大学都设有回民餐厅，她的幼儿园倒敢违抗国家政策，不收我的孩子。”

三十多岁的女子听了，越发不忿，不经意间高了音调，“我们违反了什么国家政策？！上次和你一起去宗教局，你也亲耳听到了，宗教局的领导说私立幼儿园有权自行录取，也没规定一定要有回民餐厅。里娓，害得孟姐姐吃不上饭是我的不对，但道理总要讲清楚。你儿子完全可以送来我们园，但吃饭不能特殊，别人说什么你家娃也得吃什么。并没有不收你的孩子，你自己不把他送来，专和我歪缠有什么用！”

说话的女子叫李梅，呆、笨、认死理，早先在小店街做服务员，所以很早就跟着孟任鬼混。

// 3/17
后来她在的店铺倒闭，像每天路边大多数小店一样。经同乡介绍，去了家私立幼儿园打杂，就此别离了小店街。好容易逃离魔窑，冥顽不灵的她仍把孟任平日的胡言乱语当成真理。想起孟任成天挂在嘴边当招牌的**学**与**日新**，也硬着头皮学起了幼儿教育。两年之后，居然混到了幼教资格证，转成了正经的**执证**教师。

谁都知道，中国人最舍得在孩子身上花钱。她的幼儿园赶上了城市化的浪潮，新近又弄来一笔巨额投资，所以像任何企业一样决心大大扩张。十家新建的幼儿园就有一家在小店街，集团还专门任命李梅出任园长，自然是希望和小店街大头头孟任搞好关系，至少不开罪她。

然而李梅一切都好，就是缺乏商人的灵活/油滑。她左手一本幼儿园规章制度，右手一本《幼儿教育》，做任何事情，都要先以查黄历请菩萨式的虔诚在书中寻找依据。别说与书上写的有一个字的差别，就算差一个标点符号，她也必然不行。与她龃龉的男子是小店街上新疆餐厅新聘来的青海大厨，小娃儿长到可以送幼儿园的年龄，本想着就此可以轻松一半，哪知一头撞上李梅的死脑筋，生疼。

已经很不耐烦的孟任，抓住这个空隙，对二人扬唇，“朕也听了半天了。”装出一付剧烈思考、脑海冒泡的模样，良久，“大厨也不足，李梅也过了，都有错。”

见二人呆呆凝望自己，孟任心底得意，得意成抓耳挠腮的猴子王，“先说你，宗教局的人也说，无论小学大学，上学的问题都可以为你出面，就是幼儿园没办法，可见李梅他们没有违反政策嘛。”

又指李梅，“你的死脑筋又犯了，比牛还犟。大厨又不要你专门为他家孩子开餐厅，他自己每天送饭，你为何就不肯行个方便呢？”

李梅急了，“不是不肯行个方便。”把右手的《幼儿教育》摊开，哗哗翻到一页，“孟姐姐请看，这里写着的，写着的！‘幼儿在园中必须按规定吃园餐，这是他们人生第一次参加集体活动，可以潜移默化地培养他们尊重社会、学校以及公众的行为规范的意识，并且纠正由于家长溺爱形成的挑食的坏习惯和唯我独尊的小皇帝、小公主思想。’我们园的规章制度也禁止家长送饭，我马上翻给你看。”
// 有意把引文写成啰嗦的长句。

“够了够了，”孟任摆摆小手，自认很潇洒，“朕怕你根本不懂什么叫民族宗教吧。”

李梅怔住，出身寒鄙的她见过的第一位回族人就是眼前的大厨，还是从他的口中第一次听到**伊斯兰法**四个字。等搞清楚这四字怎么写，她不免在背后偷偷对着先知发出许多亵渎的啧啧声。
//塙有如此漏人，从小到大不知道民族宗教的。

// 3/18 得知李敖去世，想有点感伤又不知在何处，唉

“这样说吧，信道教的不吃狗肉，并非他们挑食，或者怀疑幼儿园的菜肉不洁，来源不安全，而是信仰，你懂了吧？”

没有，完全没有，李梅并不认识任何道士，更没听说道士不能吃狗肉的，所以看上去更加呆头了。

“那你总有亲戚信佛吧？平时吃素斋的。”

这个。。。李梅勉强懂了，她的外婆在生命的最后岁月皈依了佛教，丝毫荦腥不沾。外人看着都觉得不忍，家人更是忧心忡忡。所以，，，李梅从小红旗下长大的唯物主义少女又把食物禁忌理解成**封建迷信**，害人不浅！

呃，没想到讲道理起了反作用，孟任好气好笑，只能求诸擅长的暴力。把电脑屏转动90度，一手揪住李梅的脑袋按桌上，一手在亚马逊图书信息页上指指点点，先吹嘘自己，“看看，像朕这般伟大的君王也懂得学习日新，‘苟日新，日日新，又日新’。哪想到你这小学生倒不学习的，天天捧着十几年前出版的第三版旧书当宝贝，你看看这里，这书去年已经出到第六版，第六版序言有一句，‘除了上述变化，本次修订还添加了民族宗教和少儿心理学内容，这符合社会主义初级阶段生产力与生产关系辩证统一的。。。吧啦吧啦，哼哼哈哈，阿弥托佛嘛咪嘛咪哄，’见鬼，全是咒语？总之，大意你反正了解了，记住，回去第一次事就是去买一本第六版更新一下你的死脑筋，记住了没？”为了帮助李梅回忆，孟任又咚咚咚在她脑壳上凿了三个暴栗，才放手。

李梅早被孟任锤惯，逆来顺受，这时只好委委屈屈先答应下来，但立刻提出了新问题，如果别的家长得知，哪个孩子没有特殊情况，人人要给孩子送饭，那该如何应对？

谁料这问题竟惹了一位未来的英雌排空出世。站在白葭里娓身畔，红衣少女赵思琪早已不耐，天哪，这都什么人啊！不过一件芝麻绿豆大的小事，这伙人唧唧歪歪、唧唧歪歪、唧唧歪歪个不停！冲动之下，脱口而出，“换个说法不就好了？不然还说成开了个专供穆斯林的餐厅，别提家长送饭，全推到宗教局身上，就说他们规定必须要有的。给所有家长两个选项，要么吃园餐，要么吃清真饭。到时候不管几个人，都让大厨按人头送来好了。”
// 排空出世那里还要修饰。赵思琪固然是未来英雌，但她在本书里只零散出现，并非主要人物，如白葭里娓。

李梅听了，缓缓点头琢磨，不提家长送饭，其他家长也不会想到送，加上幼儿园的孩子们也没有奇奇怪怪的信仰，比如佛教，不怕有人乘机要幼儿园再添个素菜馆子，如此看来，这办法也许真的可行？

// 3/19 昨天未见的，今日见了，不见李生久，佯狂真可哀

众人观察孟任的神色，孟任正色道，“又何必骗人？满腹心事，伪饰出来的言辞真以为能欺瞒世人？小店街之人虽笨，可也不都是傻子！这样吧，李梅你明天再来一趟，朕为你写张告示，把事情本末由来一一详明，你贴在大门上，晓谕众生。还有不理解的，让他来找朕。还有，你书上只提到尚同，只想到集体意识，可人生而不同，已不仅仅是宗教；有些孩子体质特殊，吃点豆油都过敏，你们也逼着非要吃定餐？”挥挥手，遣走了李梅。

竟见未被采纳，对于只有十六岁的赵思琪来说本是寻常事，毕竟年龄不到，就像还未长出鬃毛的公狮子，没有哪个母狮会将他放在心上。然而这一次她着实羞红了脸，因为无知的围观群众听了眼前和自己一般大的小女孩胡说，个个露出信服的表情，仿佛听到的是黄钟大吕，金声而玉振。

“啊呸，好恶心。被我抢先了，这小毛丫头才特意换一种说法出风头，保持她在众人眼中的地位。如果一开始我用她的说法，她一定换我的，为了不同而不同，哼哼，就有这种人。”

大厨见事情解决，喜上眉梢，正待告辞，却低估了孟任。“你也知道，李梅收你家娃是出于善意，许多人劝李梅，为你说话也是一份善意。你的孩子现在信仰你们的圣教，因他生来就是你的孩子。等他长成，如果有别的选择，别的信仰，也请你尊重，最少不干涉，看在今日这许许多多在场人士善意的份上。”

大厨呆了，全然想不到还有这么一出，嗫嚅半天，像坏了的闹钟，身子乱颤，戏味十足就是发不出一丝声响。

有个女孩见孟任要打发他，忙窜出来，咬着耳朵密报。愤怒的火星迸发，炸雷在寥廓的屋㝢内来回激荡，

“什么？打孩子？？！！你别走，你给朕讲清楚，为什么事打孩子？”

“小孩子不听话就该打？你还占理了？你那么占理，为什么把他拖到后面的车棚偷偷打？不敢在路边光明正大的‘教育’？要不是你下手太狠，车棚那边的声音也不会给姑娘们听到！”

“下次小孩子不听话，你把他送这里。你不会教育，朕这里最多有耐心的阿姨。你再敢打孩子，别的朕做不到，在小店街上你只怕混不下去！”

见大厨服软，孟任绯颜略霁，“对了，你老婆怎么回事？每天在你店里打杂、炒菜、收银，托人几次，就是不肯登朕的大门？是看不起这里的女孩子还是想学离群索居的商？商也悔于失群，她难道还贤于商？你记得带话，不管疲倦还是XX，都可以来这里休憩，嬉游。就算龙生九种，个个有别。这里人多，必有她能合得来的，总好过天天守着你。贵教的声望被一些极端份子拖累，你们又不出来交际，在旁人眼里，难免觉得神神秘秘，甚至鬼鬼祟祟。就算为了贵教，她也应该来这边教育出身于不毛之地、无知愚昧，连伊斯兰三个字都没听说过的女孩子。她不肯来，莫非是对贵教信心不坚的缘故？”

大厨失魂落魄地走了，得一而失二，总算见识到小店街统治者真正的颜色。

// 3/21 胡适一系学者还是太墨家了，这也许是李敖喜欢中共的原因。

// 3/22 
上午的事情终于完结，见无人瞩目，孟任偷偷伸了个长长懒腰。又想起居然有人胆敢抢在自己前头说话，差点扫了威风，忍不住要把那个捣蛋鬼滴溜出来。

通了激光的目光一旋，立即锁定目标：缩在角落，满肚皮不适，怀疑自己为何生在此处的赵思琪。

“你终于来啦！”噌，孟任窜出，两只爪子啪地握住赵思琪的小手，热情如火，将她拖到屋隅的小沙发上坐了。小沙发四周摆满奇木修萝、博物架作屏障，是个闹中密谈的好地方。

本感到冷落陌生而手足无措的赵思琪被这突如其来的热情打倒，本能地挣扎，却被大擒拿手死死按住。

“你们是怎么招待客人的？看茶，点心！”两个姑娘笑着得令而去。须臾，捧回来热腾腾的焦糖玛奇朵和喷喷香大块头南瓜豆腐慕丝奶酪蛋糕。

赵思琪眼看着会大擒拿手的老师傅使出失传已久的十九式三十七手“狮子搏兔”擒住了一块蛋糕大嚼，渐渐鼓足勇气，怯生生、傻乎乎地微声问道，“我们认识吗？对不起，我。。。我记性不好。。。”

// 3/23
“认识！认识！当然认识！四亿八千万贤劫之前，兜帅天须弥宫药师殿，朕登法烬台为大罗金仙讲解混元道果，你于众仙佛中最先领悟，欣然向朕躬行礼，暗递秋波。”

“再经恒河沙数之无量空劫之后，于昆仑界玄圃閬風山上的穷桑之野，才能与你再次相逢，朕于是为你拈花，对你破颜微笑。之后朕还会为你歌唱，

‘两只老虎，两只老虎，跑滴快，跑滴快，一只没有耳朵，一只没有尾巴。。。’”

@$@#%$^$#!@#^%$!

见赵思琪已然精神错乱，孟任终于感到了一丝丝羞愧，单手摩挲后脑壳枕骨，打着哈哈，“戏言，戏言尔。”

倏地，又突然将脸孔凑到赵思琪鼻梁一寸处，神秘兮兮地眨着左眼，仿佛心照不宣，道，“虽然今日初见，但观这位义士形貌，朕自然了解你的来意。”

哦，赵思琪想起来意，倒觉不好意思，明明是来求人的，哪经得起这番盛情。

见她不语，孟任当成默认，更是高兴。扬起一手，嗷嗷怪叫，“来人！快去买大公鸡，要最雄壮的！雪刀一挥，鸡头咕噜噜乱滚，血溅三丈！对了，还缺一位见证，难得如此高兴，朕就赏太上老君一个天大的面子，差他下界见证盟约！咦，瞧你面露不满，莫非嫌弃李耳老贼不成？那就西王母吧。不妥不妥！西王母还欠朕三个桃子呢，天大的怨毒，怎可让他乘机化解？”

“求求你，求求你了。”赵思琪气若游丝，哭了，“告诉我到底怎么回事，别。。。别买大公鸡了。”

不买大公鸡？孟任皱皱眉头，只办正事的话，乐趣就没有了，看着无头公鸡乱蹦。。。恶狠狠将赵思琪右腕寸关朝上翻，露出尖锐长牙，“没有公鸡的话，朕的血又不能多出，只好委屈你啦。”
// 孟任要杀大公鸡小说之言，别当真了

“别呀，我不是来盟约的。你理解错啦！”

// 3/25
“没错！朕一贯善解人意，你就是来参加‘承天景命XXXXXXX’，如今你这样的义士已然很少了。”

“不对，不对！求求你，饶了我吧。我是来领养猫咪的，你那个鬼盟约听都没听过。啊！你的盟约一点也不鬼，只是我。。。”

“是，你就是！”孟任暴跳如雷，“朕说你是，你就是，不是也是！你全家都是！莫非你胆敢怀疑朕的占卜？？？”

赵思琪吓倒摊缩在沙发一角，考虑是否先答应眼前的暴力问题少女。忽想起一物，连忙将手上的救命稻草摊开，指着其中的一篇报导，“这杂志上说，你们是南京最有名的猫咪咖啡馆，有猫咪给广大爱心市民领养，你们的口号是‘让人人都有猫咪！’看！这张合影里那个美丽温柔的少女不就是你嘛？我先以为是服务员，谁想到来了之后才知道世界上竟有这么年轻有为还美丽的店主。”

哇咔咔，听到**最有名****年轻有为****美丽温柔**，孟任汪汪大笑起来。边上的赵思琪却十二万分的后悔。

中午午休，吃完饭无聊，赵思琪从班上的图书角随意拿起一本天知道猴年马月出版的杂志乱翻，踫巧读到孟任的故事，一贯冲动，思想追不上脚步的她立刻出发过来品尝后悔的苦涩。

很多人几十年如一日做着重要艰辛的工作，做出了杰出的贡献，耗尽无数心血，却默默无闻。而孟任因为长年做视频，结识了不少业内人，加上繁娃在媒体上的关系，猫咪咖啡馆甫一开张，就有记者前来采访，并免费为她大肆吹捧。什么正经的工作还未做，她在南京小动物援助界的声势已远远压过那些辛苦二十年，变卖家产也要救流浪猫狗的**奇人**。思之令人扼腕，然而世上的事本来如此，本应如此，又何足怪哉？

// 3/26 
“这只是刚开业时的报导，”孟任神气得紧，“成绩属于过去，努力才有未来，哇哈哈，朕怕你的消息已经过了保质期。如今猫咪咖啡馆一年可以送出三百只猫咪，三百对孤独的灵魂因此得到慰藉。我们的口号‘让人人都有猫咪！’马上就可以实现了！”数学不及格的帝王小手一挥，划破天际。
// 漏了和盖茨口号对比的一句

于是美滋滋地跑去办公桌捡出一卷纸，又在耳滨插上一支笔，装出小俏皮的模样，犇了回来。

欣欣然笑对赵思琪，刚欲开口，不甘心的眼眸又忍不住翻上来，“真的只是来领养猫咪的？加入盟约很好玩滴，‘凡我盟之人，既盟之日，朝夕虔心诅咒贱婢繁好一百次，咒她屁股生脓疮，疼得死去活来，活蹦乱跳，平地翻跟头打滚。’哈哈哈，好好玩，有没有？你要是怕那贱婢的淫威，以养猫为借口试探，就眨眨左眼，朕自有万全安排。”

见赵思琪不接话，眼皮也不敢眨，打破了吉尼斯世界记录，孟任只好无声叹息，正色道，“领养猫咪需要填些表格，好让我们了解你的基本情况。不是说你，别多心哦，有些人不适合养猫，在网上看到可爱猫猫视频，一时冲动，就养了。结果热情一过，发现还需要承担许许多多责任，既花钱还麻烦，猫咪也不是他想像和需要中的奴才，就偷偷把猫遗弃。让他们自生自。。。”喘着粗气，“**彼哉彼哉！**”

赵思琪刚填完姓名时，孟任还很高兴，“思琪，思琪。”反复咀嚼，“这名字冥冥之中，和朕多少有些联系。”

等她填上十六岁时，孟任大惊小怪，“才十六岁？”忍不住伸手搬她的脸孔，贴上去细细看了，捏捏耳朵，还趴到头壳上，用力嗅了几下髪缝，“原来十六岁是这种味道？朕老是分不大清人类的年龄呢。”

// 3/27 
然而，十六岁？孟任转成严肃，“十六岁还没独立吧。”

赵思琪一凛，这才想起家长，满腔的热情于是缓缓冻结。

“**妈妈都不喜欢毛毛的东西！**”孟任抱着臂笃定道。

“对，对。”赵思琪难为情地低下头。她与母亲的关系谈不上好，至少没有任何把握说服养猫。“她总是这样。永远把我当小孩子看。说我成天不正经，不好好读书，不会讨老师的喜欢，长大了也是个废物。不如不读书，早点打工，还能省钱。再学会钓男人。。。”

“世界上竟然有这样说女儿的妈妈。”赵思琪自怨自艾，心中酸楚，不如为何，骤然向眼前初见的少女倾诉。又准备填下一项，“是否养过任何宠物？”，还在沉吟，突然，哗啦一声，一只手从旁插走卷子。

“行啦，你的情况朕已知道。”屁股离座，尾巴甩都不甩赵思琪，回到桌前，把她晾在一边。又取出修正液，当着所有人的事将赵思琪填过的重新涂白，想来可以节约给下一位领养者使用。

赵思琪全身僵硬，看着这一切，她的灵魂已脱离备受污辱的躯体，周围的一切已不对她影响。才知道不但学习不行，连收养猫咪她也没有资格。

周围的女孩子也有不少露出迷惑痛苦不忍的表情，一时若大的屋舍只余下细密参差的呼吸。

午饭的到来打破了现场的尴尬。孟任打开盒饭盖子，呱呱大嚼，又含着米粒转头吩咐里娓，“带客人参观一下，容朕吃午饭先。”

望着里娓二人步出长门，孟任轻蔑一哼，头脑发热的小姑娘罢了，看了新闻逃课过来，还想领养猫咪？猫咪再贱，也不是生来供你玩到死的！

// 3/28
孟任吃着饭，忽听楼下一片嘈杂，抬眼。两个女孩飞也似地去了，又喘着气回来，“孟姐姐，门口来了四五个街坊，非要马上见你。守门的姐姐说了，今日听讼已毕，请他们后日上午再来。他们不肯，说十万火急，等不得。但这伙人谁都不认识，应该也不是小店街的邻居。”

等这五位男男女女站到孟任身前，众人才得知他们原是小店街隔壁大店街上的住户。也是走投无路，病急乱投医才来此处求见。

原来自古以来，大店街上就有一家街道办中学，就叫“大店街中学”，奇差。以前南京的父母教育孩子常常吼叫“让你不学好！再不学好以后只能上大店街中学！”

这几年国家学美国改制，教育私有化。连大店街中学也迎面撞上了撒金的春梦，改来改去，不知为何与南京师范大学扯上了关系，旧牌子一去，摇身一变成了“南京师范大学第二附属中学”“加拿大留学预科学校”。

这一年暑假开始，为了符合**加拿大**这一响亮洋招牌，好多多创收，，，好多多育人，学校决定将校舍彻底翻新。

大规模的装修难免带来噪音，在人口密度极大的大店街相当于双倍噪音，也许可以发明一个新词“重噪”来形容这种局面。白天时断时续叮叮咣咣，打桩机似的在工地上和居民的脑海中锤炼，除了学生不得不作鸟兽散，想办法逃离，其他人只好用电视机、音响对抗。虽有不满，但考虑到总不能不允许别人装修，默默忍耐。

忍着忍着，渐渐不好了。本来只在工作日白天施工，不移时延长到黎明、午休、黄昏。好吧，继续忍。渐渐的，更加不好了，连双休日，工地也从早到晚咣当不止。有些人忍不了，去找工地，负责人笑着把人送出，大骂工地保安一场，开除了他，换了新人。最近一个星期更加不好了，白天时间不减，夜晚也哐哴哐哴起来，从十一点开始，往往要到凌晨五点，装卸脚手架，浇注搅拌混凝土，偷运建筑垃圾，无所不为。

大店街的居民也混蛋，不理解南京师范大学校领导的善意。他们没有把握机会，没有利用白天黑夜时时萦绕的锤子敲击声，锻打出纯净高尚的情操，深湛的学术思想，反而因为脑子像被敲出来，患上了神经衰弱、失眠，而已经神经衰弱者不免往精神分裂症方向发展。

生无可恋的居民再找工地，可负责人人间蒸发，新来保安一问三不知，什么都不晓得，却晓得关紧厚重铁门。

居民无奈，又求助于报社各大新闻媒体，得到了答复，和康熙皇帝一样的三个字“知道了”。

居民又打投诉电话，城管的，城建的，环保的，市政的，市长的，这些部门也一齐成了康熙皇上。

居民又于今日早上集结，准备去南师大找校长呈情。结果只见到严阵以待的保安，众人猜想用来联络的网上信息小组已被渗透。与保安对峙时，工程负责人在警察簇拥下现身，高举着尚温的“夜间施工许可证”展示。得意之余，不免多嘴，指责居民“如果全国都像你们一样，中国的基础建设就会倒退十年，街上也不会这么多人，如此繁荣！生在福中不知福！”

看着合法吵闹许可证，大部分人只好散去。然而总有自甘堕落、不识大体、不爱国的人类，四五个落后份子，老而不死的老贼凑到一起，眼泪汪汪。一周没睡好，令他们精神恍惚，以至错乱，加上老眼昏花，误以为最近小店街上出了新气象，于是哆嗦蹒跚着向那里进发。

俗话说的好，苍蝇不叮无缝的蛋，落后份子去找孟任，真可谓臭味相投了。

// 3/31
孟任去看居民们拍的夜间施工视频。五人到了这时又忐忑不安，不知道眼前的少女会否帮忙？就算愿意，她又能做到何种程度？

“反了，反了！”孟任拍了桌子，与南京师范大学有仇的她在地上乱蹦，“朕早知道南京稀饭大学混账！谁想他们竟比朕预料的更混蛋！”
// 预期时间要不要加上？实质上托了一年多呢。。。。

“小松鼠！你来！朕命你不管用什么方法，今天下午六点前，把稀饭大学的校长，副校长统统带来这里和大店街的父老开会，讨论解决办法。除非那些校长的老婆孩子正在断气，不准放过一个！反了他们了！一个屁大点的学校就敢这么欺压父老，可想而知。。。！什么，项目负责人？他是什么东西？也配过来？”

“让别人牺牲说的如此理直气壮？稀饭大学的校长如果每天在工地上办公，朕就不问此事！”

靠近长门的黄沙发东头坐着个郁金香似的少女，手中正拿着卷诗集。看到佳绝处，忍不住启颜微笑。

听到孟任的严令，小松鼠把本来枕在那少女大腿面上的脑袋抬起，不确定的四下张望。终于如梦初醒，赶紧趿了鞋子，窜到孟任跟前。

“阎王好见，小鬼难缠。”小鬼本是阎王豢养来隔离群众的。然而孟任说了“不管用什么办法”，又见地板已经跳通。小松鼠明白眼前的君王动了火气。校长们长年宦游，见惯风浪，只要被“请”来，自然不用烦神，但。。。

“你是说，这些大店街的父老反而会出问题？”孟任疑惑地反问。

“陛下。”小松鼠斟酌着，“大店街不像我们这里，是沐浴在现代法治文明下的先进社区。他们没有君长，没有乡贤，没有选举，没有乡约董事，没有宗族，连绅士也无。法律的万丈光芒确保他们无须，也确实不认识紧靠门的邻居，更遑论他人。所以眼前的父老代表不了大店街。就算这里的几人与南师达成协议，其他人未必接受。比如大店街上的五金店、门窗店、小食铺还指着学校的生意，越多越好，越密越好。又有些居民恨不得永不让中学装修，只要吵到他们；有些上夜班，更希望白天停工，诸如此类。群众的意见变化多端，不可预测，也无止境，如天上的白云，时而XX，时而苍狗。说服十名绅士也易于一个暴。。。我们管了此事，只怕两头不落，反而卷入他们的内部争纷。”

“这样啊。”孟任灰灰地木然滑落椅中。许久开口，明显失了锐利，“既如此，朕也无从帮他们多争利益。一切严格按法律条文规定的装修时段办；再叫校长带点小礼物上门慰问那十几家最受影响的。其实校长们早点上门，又怎么会闹得如此不可开交？对了，别忘了顺便带一只大公鸡，好让他们盟誓。”

哈？原来还是要看杀大公鸡呀！边上的一个女孩笑着上来款款相劝，“孟姐姐老让我们读书，昨天看到诗里有一句‘君子屡盟，乱是用长。’可见不诚心的盟约，不管歃血釁鼓，还是刻盘勒石，都不中用。还听人说，春秋贵胥誓，不如就让他们胥誓吧，皇天后土在上，大公鸡可以免了。”

见孟任笑着颔首，众人连连称善。

// 4/2 
这有什么好看的？白葭里娓很奇怪，拉拉赵思琪的衣袂，后者才恋恋不舍地离开。

“这些事很常见，只要放告的日子，小店街上还有附近的居民没完没了的跑来找孟姐姐评理，都是鸡毛蒜皮的小事，可他们才不管孟姐姐有多忙，只顾着胡扯。”

又忍不住安慰赵思琪，“刚才的事别往心里去。孟姐姐很喜欢你，不然不会对你如此严厉。想领养猫咪，我一会儿帮你私下去说。”

“好咧！”赵思琪愉悦地回答，快乐的像小小云雀直冲霄汉。

白葭里娓见赵思琪抛却刚刚的忧郁，也为她欣喜，虽然觉得情绪转变的快了点，并未生疑，尤其没想到她的转变只缘于趴在窗台，偷看孟任处理事务的片刻。

“这边是动物医院。我们有很厉害的喵医生呢。”

// 4/3 玳瑁猫醜醜失踪48小时，甚不安。也许她和她妈妈都有流荡基因，也许她还会回来，也许

所谓的喵医生就是两名从前雷渊宫的宫女，最早在猛氏馆为冥后照顾她心爱的虎群，后来和人类私奔跑了，最近随着孟任回归，立青旗延揽旧部，又不知羞的乱跑了回来。

孟任看她俩还有些特长，花钱送到外面的宠物医院实习，补充落下三千年地球动物医学。因为两人轮流，平时总有一个留在咖啡馆里无证非法行医。

赵思琪透过玻璃门好奇地偷窥医院挂号处。位于二楼西北角上的医院看样子占据了三间房屋，大部分为毛玻璃阻挡，只余下赵思琪驻目的那间。

温暖又不失热情的配色，现代简约的登记台，台后照例挂着廉价的大幅猫咪写真，只不过这只猫咪热衷对着雪山打呵欠，啊，雪豹。

雪豹下方坐着一位三十多的女士，专注地看着手上大八开的专业书，并未留意门外。

照片左边贴着价目表，赵思琪没养过猫狗以及一切宠物，不知深浅。另一面墙挂了四幅画，用木框装裱。赵思琪不看则已，定睛细看，第一幅名曰“猫咪先天经络图”，右一幅“猫咪六脉神剑”，再右一幅“猫咪玉女心经”，最后“猫咪阴阳和合交欢大乐神通”。每画都细细标出穴道、经脉和真气运行方式。如果不是绘画技巧等同于幼儿园大班，也许真有人相信。

白葭里娓只好不无尴尬地表示，“孟姐姐喜欢开玩笑，人很幽默的。又爱看武侠小说，就画了这些当装饰，当然不是真正的秘笈啦。”

愚蠢的人类，整日面对墙上四幅大作，只将它们看成小儿涂鸦，却不知万世君王将她百万年来的绝学XXXX一一画入。有人问，既有神功，为何不正大光明地刊行于世，传播文明呢？愚蠢的人类！没听老子说“玄之又玄，众妙之门？”没听佛祖说“知见障”？所以佛祖要摆出神神叼叼的鬼样子，将正法眼藏，传给大伽叶，可见愈是神仙妙法愈要鬼鬼崇崇、鬼哭狼嚎、鬼使神差，才能满足普罗大众心理的期望。
// 太轻薄？
// 4/4 醜醜的弟弟猢狲今天看着似乎也没食欲的样子。

白葭里娓推门，为喵医生和赵思琪介绍。饶有兴哇看了一会儿志愿者给狗狗洗澡美容。又在喵医生的带领下参观了医院，途经手术室、诊疗室，最后进入住院部，探望不少留院观察的猫猫狗狗。

赵思琪走马观花，笑嘻嘻的与病号打招呼。有只小黄狗得了肠胃炎，经过一周住院，已经痊愈，即将出院，喵医生乘便打开笼子抱出来。

小狗经过这番劫难，精神还萎靡。低声呜鸣撒娇。喵医生安抚一会儿，又递给里娓。里娓笑着接过，抱着小犬乱亲，口中发出含糊不明的激动。

又看到赵思琪跃跃欲试，把狗给她。赵思琪于是也抱了狗一顿亲，又为它拍拍背，捋捋毛，小狗兴奋过度，一时困倦袭来就在她臂弯中沉睡了。

三人又走到隔壁病床/笼子。只见一只大大的肥猫头戴伊利沙白圈委屈地趴着。

“噢噢噢，好肥好可爱的英短蓝猫！看这大圆脸，好想捏！”赵思琪惊喜。

喵医生点头，证实了她的说法，“本地有名猫舍的繁育猫。祖宗三代都有血统证的英短。今天早上过来做绝育，退休。公猫简单，观察到晚上就可以出院了。漂亮到这种程度的英短我也是第一次见。”

“原来这就叫英短啊，我说怎么长得和常见的猫猫不一样呢。可为什么叫蓝猫，明明灰猫呀。”白葭里娓发问。

赵思琪并不知道白葭里娓是“小店街喂猫小组组长”，因此倒未奇怪，抢先回答，“平常垃圾桶里的都是国产土猫，全是杂种，哪能和外国纯种猫相比。纯种猫总是很特别的，有奇异的花纹毛色，富有异国情调。英国民族气质中承载着高贵、优雅和忧郁。他们的国粹猫就叫做英国短毛猫，简称英短。也像英国人的品格呢。它们有大大的脑袋，粗壮的脖子，宽厚的胸部和无比壮硕的身形。虽然体型巨大，但它们性格憨厚平静，粘人亲人，是最好的陪伴猫呢！”

喵医生补充，“学术上应该是灰色的，但在很多人眼里更接近蓝色。是由黑色素在淡化基因位点loc D变异影响下形成的。”

“从我们医院资料看，英短是第一流行的纯种猫，而蓝色又是英短里最流行的颜色。我们都喊它蓝胖子。”

“猫咪果然还是胖一点可爱。”白葭里娓蹲下去捏捏蓝胖子的两腮，精神委顿的猫猫娇声抗议了两下，露出生无可恋的表情，大家看了都笑，心中温暖起来。

白葭里娓于是平生第一次对纯种猫生出了好奇。喵医生拿出手机，找了一些以前住院的照片给二人看。然而喵医生只知道纯种猫常见的遗传病，其它不甚了了。

反而赵思琪懂得更多，能讲出每个猫种的性格特点、生活习性，完全没有辜负宠物猫舍几十年如一日努力传播“知识”所耗废的心血。

// 4/7 五天未见醜醜
白葭里娓对着一只银白虎斑小猫照片紧瞧。赵思琪从旁一见，忙道，“这是美短，美国的国猫。像美国这个民族，独立勇敢、开朗活泼、健实温柔，对外界事物充满了好奇心。听说它们是‘五月花’号第一批乘客，从那时起就守卫着美国人民，所以也是忠诚勤劳勇气的象征。从某种意义上说也是美国的开国之父。历史课上都学过的。

历史课上当然讲过五月花，赵思琪哪里胡编了？猫对于美国的建立，作用只怕不下于**founding fathers**。当然，当它们的数量太多，又乐意食毒而亡，除了死前的那一声哀鸣，不会发出其它响动，惹起勤劳勇敢的美国人民一丝一毫的不快。
// 自然有所指，美国人民杀猫可是使用过生物，化学等多种武器，除了核武器还未试过

里娓如闻仙乐，如痴如醉，频频点头，不由赞叹，“赵思琪，没想到你如此了解猫咪，一看就是爱猫之人。像你这样的爱心人士就是我们一直寻找，可以托付猫咪终生的领养人！”

自从升入现在的高中，父母就对赵思琪学业彻底死心。赵思琪和同学也选择放弃，懒得学。高中的老师更懒得教。为遣永日，赵思琪上课时必打开手机在网上闲逛。渐渐的，被互联网上的猫咪吸引。兴趣是最好的老师，经过半年的坚持不懈，她俨然成为宠物猫专家，甚至同学购买家猫也必先来找她咨询。这一切都很美好，天边唯一一片的乌云是——她没有钱。

“啊啊啊！这是暹罗猫，好可爱！”赵思琪看到另一张照片尖叫，“看这纤细修长体型和楔形头就知道是热带异国品种。它们是大洋洲暹罗国的国猫。以前只生活在皇宫和大型寺庙，是外人只能耳闻、不能目睹的贵族。它们也像暹罗国人一样，性格刚烈好动，机智灵活，探索欲特强，善解人意。是唯一一种可以牵出去溜大街的猫，因此也被称为猫中之狗。有人在网上黑它们，说暹罗嫉妒心最强，容不下另一只猫。其实不是的，嫉妒心强因为它们对主人忠心耿耿，感情深厚，需要主人不断爱抚关心，如果强制与主人分开，则可能抑郁而死。对了，它们在网上还有一个绰号，叫‘挖煤的’。”

“里娓姐请看。这只暹罗猫全身象牙白，只在面孔、耳朵和尾巴尖上显出棕黑色，我们行内的朋友称为海豹色，又叫特点色。是暹罗猫的特质。好像由什么什么基因控制，而这种基因和温度有关，皮肤温度高就是象牙白，温度低的区域如耳朵尾巴就转成巧古力色，越冷越深，直到纯黑。”

“我有一个同学养有暹罗。”只要赵思琪需要就有一个同学从地里长出来还带着一只暹罗和父母双亲，“她嫌猫猫掉毛多，每天打扫麻烦，就给猫猫剃短毛。我劝她，她还不信。谁知两个月后，她老爸从外地出差回来，一进门吓了一跳，我家的宝贝白猫哪去了，怎么一只黑猫迎上来，和我老亲热的？从白猫一转眼变成墨猫，就好像白从出门挖煤，回家成了黑人。所以它们才有了‘挖煤的’雅号。唉，她就是不肯听我的。。。”凭空长出来的同学的在天之灵听到这一声叹息难免流下懊悔的泪水。

里娓哈哈大笑，
// 4/9
突发奇想，“没想到外国的猫咪如此奇异。明年下半年我要陪和总出国，已经定下去美国三次，欧洲一次。本来我还有点怕，现在想到在美国街头就可以看到叫作美短的猫咪，这样讨喜的模样。英国的猫咪原来是英短，大头小胖子。所以说出国长见识真正一点不错。要是运气好，说不定捡到几只美短英短带回来！只不知那大洋洲的暹罗国在哪里，有机会也要去捡猫猫。”

“好主意！”赵思琪娇笑。喵医生和蔼又略带尴尬地陪着天真的里娓和纸上养猫的赵思琪微笑。
// 暗示够多了吧。

听到“和总”二字，忍不住向里娓祝贺。里娓害羞了，“唉，不过是运气好。我又没做过什么了不起的事情，也没学历，竟能被和总错爱，成了她的助理。又不能辜负和总的厚爱，也只好战战兢兢，用尽全力向前。只可惜时间越来越少，来这里越发不容易了。”

是的，上次捉猫，里娓给和曦留下了深刻印象。又一日，和曦想起，到明年夏初，自己目前的私人助理就将完成合同上的五年之期。和曦不是墨子的信徒，除了才能，用人一贯看重**亲、近、贵**，想着现在的助理为自己服务五年，尽心尽力，任带任怨，无论如何也要调剂个好缺给她。

那么谁来填补她的空缺呢？助理这职务太不起眼，很难聘到像样的人士，可这职务对和曦自身却又重要。好像鞋子，卑贱得天天踩在脚下和灰尘污秽亲吻。但如果不合脚，倒霉的一定是鞋子的主人。

想到这里，和曦有意无意向孟任探探口风。孟任闻弦歌而知雅意，上窜下跳，拍胸脯打包票，把里娓吹得天花乱坠，说她人品高标，性格淑均，言行稳重，才能特出，真正天下有、地上希、人间无。仿佛博浪坡缩头的张子房，隆中茅庐里趴着的诸葛孔明！仿佛巨闕太阿隐于匣中，一待清风，便可龙吟！

和曦吓得非轻，不敢用卑微的助理亵渎天下之英。孟任忙转舵，说里娓出身微末，长在泥涂。性本若芝兰，生于幽谷，不因为无人关注，就不吐出芬芳。只可惜天下荤荤，竟令幽兰也生出用世之志。是以她才情愿出仕，待价而沽，屈志折腰，事奉他人，哪怕再不起眼的职位，只要能正天下有道也必甘之若饴。
// 子曰：沽之哉？

和曦于是下了聘书，月俸一万，又替她报名南京最好的英语学习机构，让她在这一年里只做一件事，学好英语。

优厚的待遇加上无事需要操心反而令里娓胆颤心惊，避而不受。和曦更加喜欢她的忠直，特意找事给她。想起上次捉猫时见到的冻干不错，又找了相关领域的咨询公司，研究一番，觉得应该能在高端市场中占据一个位置（niche market)。于是找孟任一起注册了商标品牌，准备生产冻干宠物食品，不求赚钱，只希望增加上市公司的销售，顺便让里娓心安。

// 4/11
胡乱生产喂自家猫是一回事，食品上市（哪怕是饲料）就是另一回事。里娓接手后才了解其中的烦难，又不愿和曦多花钱，事事亲力亲为，查资料，跑政府，和各种牛鬼蛇神打交道，忙了快两个月，勉强搞清楚该如何办理。

所幸和曦不急，只是命她务必把英语学好，所以里娓一周三天在培训机构，一天在和曦公司实习，剩下的用来跑批文，偶尔无事才能过来小店街。

从宠物医院告辞出来，白葭里娓又带赵思琪参观二楼其余机构，什么反骗组，小贷组，隔离室。赵思琪莫名其妙，里娓也不多说。临了是一间小髪廊，几个姑娘坐在椅上，由着另几个姑娘在头上乱搅。这一切立刻吸引住赵思琪，里娓笑着邀请她进去，两人坐了一会儿，也修了修头面，方才满足而去。下到一楼大厅。

走到半路，楼梯拐角处，忽遇上几只白日劫匪。里娓笑着蹲下和喵喵叫的小毛球打招呼，任凭他们在身上蹭，又从兜里掏出几块奶酪，掰开分赠。等这几只毛球疯完，舔好爪子，他们又忽喇喇跑开，跳到墙角游戏机上继续。

原来两人中断了猫猫们的游戏时光。领头的花猫用左爪敲打游戏机上的大红按钮，刺激冲动的电子音乐渐起。群猫得到信号，在餐桌高的台面上分散，背对着好奇的人类，各就各位。

从赵思琪的角度看去，只能见到六个认真的后脑壳和十二只认真的毛耳朵。啊啊啊，这呆呆的认真模样简直就是犯罪！

音乐节奏渐密，伴随一记重音，游戏台上十八个圆洞中突然弹出一只红色塑胶老鼠，得志猖狂，左顾右盼。啪，守着左上角、湛蓝眼睛的白咪子一爪拍在老鼠脑门，吱吱，老鼠惨叫，缩回洞中。
// 白咪子。。。

又一记重音，两只地鼠同时弹出，这一次是花花和白咪子的儿子雪上狸得分。音乐越来越急，密得像夏日午后的暴雨，猫猫们就这样欢快地玩耍，“Combo! Triple Kill! Perfect! Rampage!”怪音不倦地从机器喇叭迸出。

骄傲自豪的里娓转头对呆立僵硬的赵思琪道，“这台地鼠机是和总送给她男朋友的生日礼物呢。”

// 4/12
和曦的男朋友自然是繁西，在小店街，他是废物的代名词，多亏孟任不舍昼夜的宣传。某年，符合社会人际交往规范的和曦精选了这台打地鼠机作为繁西的生日礼物。繁家人以三分钟热度名世，开始的时候，晚饭一结束，全家人都要排队在地鼠机前兴高采烈，还常常为轮次打架。时间不长，不打架了，也就淡了情绪，地鼠机沦为餐厅摆设。繁娃包饺子时很喜欢顺手把一米五直径的大匾摆在上面，高度又好，位置又巧，撒点面粉，包起饺子来有如神助。直到最近的某夜，起床撒尿，迷迷糊糊的孟任绊了一下，一个猛子把头磕到桌角，连累桌上乱摆的十几个快递箱子哗啦啦乱坠，全叠到昏迷不醒的孟任脑壳上。好不容易爬起的少女大怒，准备发动世界大战，讨伐令无上君王出丑的和曦。然而又想起猫咪咖啡馆多亏了和曦的经济援助，勉强放下，眼珠转转，打起了别的主意。

“你说说繁西是不是废物？”里娓得意之下嘴碎，兴奋地传播真理，“他们家人口多，买烤鸭都是论只的。你也知道南京的规矩，烤鸭都得搭没人要的烤鸭脖。孟姐姐让繁西去买晚上吃，你猜猜怎么着，繁西买回一只鸭子搭了两个脖。大家都笑话他，连苏姬都说，‘西哥哥好呆哦，比苏姬还呆。大家都知道，买一只鸭子搭一个脖子，买半只鸭子搭半个，买四分之一最多搭四分之一，除非一只鸭子长了两个脖子！’孟姐姐就骂他，繁西，你果然是个废物，成天魂不守舍！让你买个鸭子都被没魂的摊主欺负。算了，朕早知道，买烤鸭这样的大事你做不了，做点小事罢，去把那台地鼠机调整到适合猫咪的力道，再安一个大红开始按钮，上面还要画个白白的小爪爪！”

谈笑间，地鼠机进入了最高难度——人来疯。天衣无缝的配合终于出现瑕疵，一只牛奶猫误了一只绿地鼠，恼羞成怒，扑向那地鼠消失的穴洞，探头入内，又咬又挠，想彻底解决鼠患，也就是捣毁猫咪下午休闲的宝物。花花见了，照牛奶猫的脑门就是一爪子，像母猫教育小猫。奶牛猫呜呜两下，缩回一角，舔毛去也。

“老实说，养猫之前，我永远也想不到猫咪居然是这样学习礼仪的。”里娓感叹，“我们这生活了几十只猫，大部分对地鼠机百玩不厌。我们也不加干涉，猫儿们玩闹了几天就自动分成几组，各占据了不同时段分享，他们热爱秩序如此！”

“看诗上说，‘相鼠有皮，人而无仪。’唉，谁想到人常常连猫咪也不如，唉。”

哦，赵思琪明白了。眼前的女子虽比自己大几岁，却是个傻蛋，只会以最大的善意理解猫咪的行为。

// 4/15 
终于下到一楼，赵思琪首先吃了一惊，记得来时还显空阔的一楼此时竟快客满，密密麻麻，坐满了各式各样用发型争奇斗艳的女子。

白葭里娓解答了疑惑，“通常这时间人最多啦。饭店服务员忙完中午场就来店里小坐，逗逗猫咪，把午间的不快抛下，到四点五点再回去上班。”

窗边的好位置已经满了，里娓带着来到中央大道旁的长方桌坐下，又起身去志愿者吧台拿茶点饮料。

赵思琪逛了一圈二楼又说了许多话，精神略显倦怠，正好坐着盘桓一下精力，只是。。。心中有一块总觉不妥。

正纳闷间，两个小姑娘唉呀唉呀跑来这一桌。“不好了，一忙就忘，今天大坏猫多关了半小时，等会儿他会不会生气咬人哪！”

赵思琪见那两个姑娘头戴猫耳头环，知道她们是里娓口中的志愿者，便朝他俩微笑。两个姑娘见了，也忙回以微笑。其中一人抽手到桌面之下，不知扣到什么机关，桌子正中三分之一的桌面缓缓弹起，露出了它想隐藏的真相——钢化玻璃制成的箱子，同时也是桌子的支撑腿。另一位姑娘早已戴上厚皮手套在半透明的箱体内寻找，一会儿捞出只枯黄草色的小猫，放桌上。又下去捞，抱出一只小小花豹，像是赵思琪来时见到的那一只。姑娘最后一次探身，出乎赵思琪的意料，掏出一只硕大无朋的白猫，如此之大，若不是他胖胖的圆脸正在生气，时不时徒劳无功地咬在厚皮手套上，赵思琪一定以为抱出来的是狗狗。

“好吼，好吼。不生气。”姑娘拿出营养膏，桌面上趴着的三只猫激动起来，轮流伸长脖子舔。

“我们把这叫社会化笼。”里娓回来后解释，“猫咪长大的前六个月如果没有充分接触，就会终生恐惧人类。猫猫胆小敏感又总以自我为中心，所以一看到人类走近，总以为目标是他们，于是望风而逃。我们给这个特制的玻璃箱子贴了反射膜，使外面很难看清里面，而对里面的猫咪却是透明的，很像汽车上常贴的那种。这样，大厅中央虽然人来人往，但行人不会注意到桌下箱子里还藏有猫，而箱中的猫因为无可回避，只好慢慢体会出人类不可怕，他们的目的也不在自己的道理。当然，每天训练结束后也要用美食安抚，令他们不至生出反感之心。”

赵思琪又问效果，“大部分猫都有效，但偶尔也会激起公猫的领地意识，四处滋尿，那样的话我们也有别的方法。”

里娓啜饮果汁，又道，“看那只枯黄色小猫，是和总点名领养的，一开始抓来的时候，连自己的影子都怕，现在与我们还有和总很亲近了，所以进笼子巩固，估计再有一两个月她连陌生人都可以淡然处之。那时就会举行毕业典礼，将她风风光光地送到未来家中。你若有空也来参加，很热闹的。”

赵思琪想想，难免奇怪，“既然已经与领养人亲近，又何必多此一举，训练她与陌生人的关系？”

里娓神情一窒，旋又失笑，“在这里多呆一些时日也没有坏处，可以同时学习别的技能。再说，毕业标准有这一条，以后去医院什么的也不容易应激。最重要的，猫咪也许可以活二十年，二十年哪。。。会发生很多事，猫咪能接受陌生人也好。。。你懂的。”

赵思琪不懂，又好像懂了，低头装作用心品味咖啡。

// 4/18 
赵思琪又找到新的话题。“你说的是王可可吧？”白葭里娓笑答，“刚来的时候，所有人和你一样，以为是国家一级保护动物——金钱豹。当然也有不少认成猎豹的。。。按说我小时候还见过两次花豹呢。倒是孟姐姐连这个都懂，一眼认出了它。”

是的，随意一瞥，孟任已把王可可看穿。鼻翼两侧直冲脑门的白线，黑耳背上耀眼的白斑，与花豹形似神不似的文理都促使孟任脱口而出——石虎。

那一日是王可可夫妇结婚周年。小夫妻两个早早开车上路，去邻省宿营。孩子已托付给爷爷奶奶，只带着一对狗，既为安全考虑又防止它们在家寂寞。

傍晚将将开到湖边，疲累欲死。刚还在晕车的两狗却撒欢跑的无影无踪。王可可呼唤了几下，不见踪影，只好算了，专心搭帐篷。抓了几只蚊虫的功夫，孟孟狗忽啦啦一声从路边树林钻出，嘴里叼着一只小小的脏毛球，骄傲地硬塞给女主人看。

王可可被小豹子吓了一跳，脑中想的只是“吃人”野兽。她的丈夫倒还冷静，询问小豹子的由来。孟孟狗神气地领着两个感觉迟钝的人类来到土路另一边，乔乔狗守着的灌木丛。两人检查了一番，并没有发现任何线索，见狗子很兴奋并不慌张，又想起孟孟狗十分擅长寻找被弃幼猫，于是认定手上瘦骨嶙嶙的豹子是一只弃儿。

夫妻俩当即放弃露营。连夜返家路上，王可可想起孟任说的幼猫救护要决：保温和供奶。年轻夫妻的车上倒不缺奶粉、奶瓶、奶嘴，只是略高于人体的温度该如何保持是好？

开车的丈夫没有犹豫，接过小猫，塞进胸口贴肉保存。十个小时的旅程于是收获了妻子的敬意和一身跳蚤。

“石虎，又叫亚洲豹猫，山猫什么的，因为是王可可救来的，孟姐姐因她命名。其实到现在我们也没搞清它究竟是弃婴、母亲遇难留下的块肉，还是孟孟狗乘猫妈妈不在时偷的。”

“很好，走私偷猎国家保护动物，真行啊！”赵思琪默默记录。
// 豹猫其实是三有，赵思琪没查过林业部名录，想当然以为是保护动物。

// 4/19 
“成年的石虎比家猫稍大，其实是本土原生猫种。繁西有一次过来说，最近考古在陕西泉护村出土了一批五千多年前的家猫化石，经国外古生物学家鉴定，发现竟然就是王可可们，而非几千年后才留学到中国的家猫。”

繁西偶然说起这些，虽然他的目的，和平时一样，攻击进化生物学家。

“自从泉护村的猫咪证实为石虎之后，”繁西冷笑着，“进化生物学家立刻又发明了一项真理：驯化的石虎是被几千年后跟随西域和尚进口的中东家猫取代的。换句话说，如果没有中东猫，现在在我们大腿上打呼噜、讨摸摸的还是王可可们。他们不但是科学家，还是历史发明家，真不愧是科学教的神棍。证据，给我证据！什么时候起，科学他妈的成了幻想文学？”
// 这段考虑放到之后和曦和陈皮皮那章写。

里娓接着说，“亚洲豹猫几乎在全国都有分布，有趣的是，家猫也在豹猫的餐桌上。也许这是为什么流浪猫在我国不会重新野化成它们长腿祖先的原因。嘻嘻，这话千万不能让繁西听到。”

赵思琪第一次听说这些，觉得新奇。

“说起来王可可也可怜，虽然曾经遍布中国，上世纪政府还鼓励捕杀，好换取外汇。一年可以出口几十万张毛皮。所以如今它们也已难觅。”里娓总结，“他们的美丽是他们的催命符，在江苏已经成为重点保护动物，希望未来别又成为新的‘华南虎’吧。。。”

// 4/22
吃完点心的王可可正舔手回味，刚那两个女孩子过来，小心翼翼地抱起她，送到不远处的一张桌上，十好几个早已等待的女子强行压抑着面部的潮红，轮流爱抚逗弄。

“那也是王可可社会化训练的一部分。”里娓道，“王可可是纯粹的野生动物 。野性终有一天在她心中轰鸣，所以孟姐姐要求在她成长的每一天都充分接触人类，可以说，花在她身上的精力抵得上十只家猫。”是的，孟任是这世界上仅存的两位精通驯养大型猫科猛兽的专家。她与另一位曾经常年拥有三位数的猛虎，像外国人常说的，她遗忘的比全人类知道的还多。

“孟姐姐还不许我们抓猫咪的后颈，说我们不是猫妈妈，不晓得轻重缓急，老去抓，猫咪长大容易变得怕人，也就是那些人口中的养不熟。”

赵思琪点点头，看来这地方训养野猫确实有一套，等等，为什么感觉如此奇怪，甚至不安？她们做的事情好像与网上爱猫论坛的完全无关。。。

赵思琪看着王可可在隔壁桌上淘气，撒娇，在一个个脑袋上跳来跳去，又趴在姑娘肩上，使劲蹭。那姑娘的表情在说话，诉说着爪牙的尖利。赵思琪心说，如果我处于她的位子，也一定像她现在这样傻笑，不敢随便摆动躲避，免得吓到猫咪。

正看得入神，白葭里娓拉了拉她的手臂，指着地上。原来那只大的超乎梦幻的纯白猫咪起身，正往后庭踱去。

// 4/23
前庭还像正常的咖啡馆，后庭就是猫咪的丛林。猫窝猫架猫柱随处都有，五花八门。咚咚咚，三只小猫从两人头顶跑过，赵思琪昂首，原来空中也布满了梁柱，供猫咪高来高去，偷窥下方闯入领地的无知人类。
// 猫的丛林完全不会写，要大修

“这里才是猫咪的世界，想看得来这儿。”里娓自矜地说，“我们这里只有猫咪想找人类玩耍时才会到前面去，这里没有强迫他们出来娱宾的。”
//好难，不是猫的专家，写这章时时卡词

于是二人去看那些心情正好，愿意呆在地面的猫，比如一路跟踪，里娓口中的‘臭繁西’。

“臭繁西每天最重要的工作就是巡视领地。”
“就像现在这样。”里娓笑嬉嬉地咬耳朵，“有时候，我觉得他才是这里的主人，比我们还关心这片土地。”

大白猫左闻右嗅，四处玩耍。一路上的公猫纷纷让路，可母猫并不怕他，时时挥动爪子作势要打，臭繁西嬉皮笑脸地跳开，继续游荡。

大坏猫逛完地面一层，没有发现异常和敌人，老婆们也像往常一样与自己打情骂俏，你侬我侬，不由得朕心甚慰。走到墙角，抬头、凝踞、猛然窜起，前爪在墙面上一蹭，借力转身，直接扒上空中两米多高的猫梁。“好，，，好厉害！”云养猫的赵思琪平生第一次见识猫咪的二段跳，心旌荡漾。

然而上了猫梁的大坏猫变了一个猫，又凶又狠，对着梁下两个跟踪狂哈气嘶嘶、亮爪、吡牙，在想像中扯开了她俩白嫩的喉咙，侧头吸吮新鲜喷涌的热血。

就在此时，一只母猫走出猫树中央的猫窝，叫唤起来，寻找自己的姐妹，幼崽的阿姨。

大坏猫听到，立时止住示威，从墙边溜缝落到地上，不管那母猫，先窜到里娓两腿间乱蹭，要摸摸。

“嗷~~~”嗷呜的里娓完全丧失了思考能力，如果她曾经拥有的话。双膝跪地，两臂延揽大坏猫入怀，在他耳边喃喃，“坏宝贝，坏宝贝。你刚才没认出我吗？那么凶！你都不晓得我有多爱你。”

大坏猫任由里娓亲吻抚摸，终至无可忍耐，嗖的窜出，去找呼唤的母猫。

// 4/26
母猫原也是南京大学流浪着的主人，因为怀孕时后腿骨折才被紧急带回，未久。在这里她养好伤，生下娃，还遇到阔别数年的母亲和妹妹。一家人以这种怪异的方式团圆，如果流浪猫也有团圆一词的话。

四个娃，有橘有白有狸有花，正是最淘气的年龄。连续带娃一个多月的母猫也不堪其忧，出来呼唤自己的妹妹，好去进食进水，眯盹一会儿。然而猫阿姨、猫外婆现在统统失踪，不知道是躲到哪里睡觉，还是跑前厅玩去了。

呜呜叫唤半天没有回音，猫妈妈有点沮丧，这时竟看到自己的老相好翘着尾巴巴巴地赶过来。

大怒！老娘都这样了，还想过来交配？？！！大坏猫吓得小了两个身姿，伏在地面，趴了双耳，在母猫咆哮的间隙小声回话。什么？你来带孩子？母猫疑惑了，然而疲倦战胜了她，最终大坏猫如愿以偿。

里娓见此，掏出手机喊人。两个女孩子扛着各种摄像设备匆匆赶来。毕竟临时起意，人手不足，里娓走去举起一块补光板相助。赵思琪也去拾起一块，站在另一边。里娓见了，忙感激地冲她一笑，赵思琪看似害羞，转过头去，对着自己诡异地咧嘴笑了。

妈妈带孩子千妥万妥，一切安排的井井有条，孩子们干净健康，毛光瓦亮，活泼天真。爸爸带孩子。。。手忙脚乱，东倒西歪，孩子也凄凄惨惨、乌眉皂目、灰头土脸、不成猴子耳朵。母猫在的时候，幼猫互相偎依，相亲相爱。母猫才动身，块头最大的老大老二立刻为了领导地位施展喵喵拳，打得不可开交。老三最老实，呆呆趴着，见无猫注意，偷偷往哥哥尾巴上咬一口，让他们以为遭到对手偷袭，从而战火更炽。最小是只美女，这时候怕起来，啾啾哀鸣，要找妈妈。于是四只小猫一起颠颠的爬出巢穴，哇哇大哭，去找妈妈。
// 这章结构简单，却常有无力驾驭之感，是因为愤怒么？

// 4/27
大坏猫好得意，大大的在女友面前表现了一把，凝望着她消失的方向，幻想无数，准备转身堵住洞口睡一觉，顺便“看”住孩子，何曾想孩子已全跑出来了！

不好，不好！巢穴安在猫树之上，离地一样多高，洞口虽有个平台，也仅容得下两三只成年猫挤成一团睡觉，四只幼猫还不懂事，到处乱爬乱抓，哪里知晓危险？

大坏猫急了，想把孩子们逮回去，可立刻遇到大问题，**孩子们并不认识这个怪叔叔**。相反还显露出凛冽的敌意。老大老二并肩怒吼，如此不起眼的小不点为何发出雄狮怒吼，像雄狮一般吼吓千军万马，声音大的连他们自己也不敢相信。老三不敢对抗，早已溜到平台与连接木柱之间的缝隙，尾巴一折，与环境一体；小花最勇敢，仰卧挺起四爪，前爪撕，后爪蹬，打得大坏猫节节败退。是的，连三十秒都没撑到，大坏猫就输掉了这场只能防守不能还手的战争，呜咽地从平台边缘坠落。

众人哈哈大笑，几个姑娘上前捉了小猫，又按里娓的示意，将他们送到铺有绒绒地毯，设有滑梯秋千的猫咪游乐场。

地毯上扑腾的孩子们再也没有坠落风险，可大坏猫高兴不起来，他也理解之所以失算在于孩子们完全不了解他。勉强打起精神，陪孩子玩。

“虽然现在有八字眉，成年后多半会白化。对，就是那个白的多半是大坏猫的亲崽。”里娓笑对赵思琪说出自己的猜测，“狸花也有可能，狸花像妈妈，也许没有显出父亲的毛色。小三花说不定也是呢。。。”

赵思琪略吃惊，因她从未想过这个问题。

“是的，”里娓抿嘴，透出神秘之微笑，“通常流浪猫一窝幼崽不只一个父亲，毕竟**母猫是拥有两种非凡智慧的强大生物**。”

“第一重智慧：母猫会和聚落里所有公猫交配。你知道的，公猫有杀死非亲生幼子的恶劣本能。说它恶劣当然是站在人类的角度。所以母猫与所有认识的公猫那个那个一次可以保护未来的幼儿。”

“然而母猫又会尽可能、抓住一切机会与最强大的公猫交配，以使她的后代得到最优秀的DNA，这就是令人可敬可畏的第二重智慧了。”

// 4/28
朗朗晴空笼盖四野，
无边红日照临下土。

也照耀着手忙脚乱的父亲。刚抱着小白玩一会儿，谁知小白哇哇大叫，死命挣脱，大坏猫赶紧松爪，一脸困惑，不知自己下口太重，咬疼了孩子。又去接近小橘，可小橘正生气，对他一顿黑虎掏心，转身继续找滑梯上的小白打。小三花好容易爬上塑料桶，困意上来就此趴着睡着。只有小狸和爸爸玩，只要大坏猫提供毛绒绒粗尾巴任他扑咬。

赵思琪看了有趣，问，“都说猫爸爸从不带孩子，没想到竟是谣言。”

里娓点头，“是，不过是成见罢。人类是一种智力低下，以幻想代替证据，想当然的动物。他们的大脑只进化到拥有非黑即白简单化思考的能力。”里娓笑着引用繁西的名言，“最近锂电池红外摄像机的大普及让我们重新认识了猫科动物。印度那边有很多老虎保护区，最近配有AI识别的摄像机陆续传来了虎爸爸与孩子嬉戏，在虎妈妈外出时照看子女的影像。甚至发生过一件奇事，母虎XXXXX因为意外死亡，公虎从此挑起了重担，独力抚养两个女儿，直到她们成年。中途其它母虎百般勾引，都被认真的父亲打跑。”
// 最好找到母虎的名字

里娓又从手机中调出一张图片，赵思琪看到冰天雪地之中一头体型硕大、毛发蓬松的巨虎领头，后面跟着略小一点，同样毛绒巨大的雌虎，再后面三只天真活泼的小老虎亦步亦趋。“这是俄国拍到的东北虎一家五口照片。看虎爸爸多么雄伟强健。。。”

和睦温馨东北虎一家的照片打动了赵思琪，里娓又道，“现在生物学家还认为猫科动物是孤独星人，开个玩笑，我看用不了多久他们就会把猫科动物，至少家猫重描述成社会动物。毕竟人类这种自大动物，一切标准都从身出发。一种动物孤独与否都是按人的标准。按现代社会人类连邻居都不想认识，也不需要认识看，家猫的社会意识已在人类之上。”
// 不达

// 4/29
寒意突然从现场每人脊背升起，上重关，浸入骨骸，带来恐惧战栗，四肢也压制不住抽搐。原来小憩自适一小会的猫妈妈终究放不下，已经无声地归来，立在游乐场的大门之上，居高临下，关注又显出不满。

大坏猫正与小狸花打成一团，享受美好时光。第六感求生本能的强大，令他惊愕抬头，才发现只剩眼前的一小只，其它味道的孩子早已溜得没影子。

母猫从半空跃下，扑通落在公猫脸上，嗷呜长啸，闪电爪六出，大坏猫带着八十多道新鲜惨叫狂奔飞去。

赶跑了只会扯后腿的男朋友，观察已久的母亲自信傲立在场地中央，啧啧啧起来。三个毛脑瓜雨后蘑菇似的从隐藏地冒出，带着喜悦的哭腔，跌跌爬爬蹶着屁股冲向母亲，围着她诉说从怪叔叔那里吃到的苦头。

见到刚离开不久，已经受惊受伤，灰头土脸的幼崽，母亲一阵宠溺，将每一个乱动的小家伙抱入怀中，一阵舔，帮他们清洁，消除爸爸带来的尘土与坏影响。

又一页羽毛落在猫妈妈着陆的地方，未激起任何响动。众人心头巨震，武侠小说中的绝顶轻功也不过如此。定睛细看，只见到场中心立着一个身型矫健，苗条修长的玳瑁母猫。

猫妈妈见了新来者，也是一震，放下淘气的孩子，径直走上前去，与之对视。耳对耳，眼对眼，鼻子顶着鼻子，僵立。赵思琪刚要担心，只见两猫同时发力，鼻翼触碰一起，旋即分开。两猫同时兴奋地嚎起来，确认了味道以后，相拥相抱打了几个滚。哦，原来孩子们的外婆从外面溜达回来了。

有了猫外婆，猫妈妈更觉安心，想想今日活动已经过多，是时候接孩子回家、喂奶、再一起依偎睡眠了。

与母亲一起，只搬运两次，四个小魔头叼回家。正要进窝侧躺，谁知意外迭起。早有预谋的猫外婆抢入窝中，平躺，露出两排粉红粉红，娇嫩娇嫩的乳头，发出吃奶的叫唤。毛孩子们听了，也喵喵回应，拼了命互相推搡上前，抱住乳头，大口吮吸。

猫妈妈急得大叫，可孩子们已进入吃好模式，就算天崩地裂也浑然不知。猫妈妈叫了一阵，无果，只好转头，大大的眼睛，向围观人类求援。

里娓笑着揪出了猫外婆，放到另一个窝里。看到猫妈妈终于开始喂奶，笑着对赵思琪解释，“流浪猫在野外往往结成部落生活，共同守护食物来源，赶走入侵者。同部族的母猫互相哺乳，照顾孩子。本来猫外婆喂孩子也正常，可她去年来这里已做过手术，今年没有奶了。可她老是乘别的妈妈不注意上去喂孩子，左也是捣乱，右也是捣乱，让有奶的妈妈喂不上开着急。想来爱孩子的天性就算绝育也无法泯灭。母猫真是神奇的生命！”

// 5/1
对于自作多情的里娓，赵思琪只好苦笑，心想网上这些垃圾土猫的风评可不太好，更何况你轻描淡写说“共同守护食物来源，赶走入侵者”，仔细想来，又何尝不血腥恐怖、凄惨骇异？

赵思琪还要开口，突然被一道灵光击中，豁然开朗，拤准了自进入咖啡馆以来即占据心尖却又说不清道不明的焦躁不安。

“怪不得，难怪。”她对自己说，呵呵冷笑，“我说怎么有地方免费送猫猫，原来是这种猫猫！从进来这莫名其妙，颇似邪教的场所，也算见到几十只猫，全是土猫，土猫！妈的，这群坏蛋从外面垃圾场里捡些早该全家免费丢火葬场的累赘送给无知愚蠢的好心人！纯粹是坑人！”

作为网上爱猫论坛资深活跃分子，赵思琪早已通过忠诚试炼：即早已通过一次又一次**讨论**得出结论，又与意气相投的志士结成联盟，时时刻刻互相提醒，千万不可一时心软收养土猫。

他们算过帐，表面上看宠物店里的猫咪很贵，稍微沾点品种就要几千上万，但其实像他们这种真正爱猫人士才懂得，猫咪花费的大头在日常饮食开销和医疗上。初始买猫的几千块投资摊薄到猫咪二十年生命里也只一到两块一天，哪里省不出来？两相貌出众、**富有异国情调**的宠物猫所带来的心理满足，尤其在邻居亲戚之前，又岂是养土猫可比的？

坚定了信念的义士们在网上主动出击，传播真理，辟除邪见。看到有人发贴，说猫咪淘气，喜好抓人咬人，他们主动前去教育，土猫生性顽劣，野性难服，哪有不咬人的？再贴心的为伺主算经济帐，告诫不要因一时的妇人之仁，误了终生，与其痛苦二十年，不如早点丢弃为上。当然为了生态环境考虑，不如，，，不如那个，意外一下下。。。经济帐人人都懂，十拿九稳。剩下的如果叫屈，说自己的就是宠物猫。义士们就一窝蜂的顺着网线、路由器、交换机，嗅出图中的猫咪品种不纯，混了野猫的DNA。他们持续攻击，直到伺主羞愧难当，承认自己当初贪了便宜，未去义士们认证的正规猫舍购买；因为自己的贪婪，竟然错怪了纯血猫咪并保证从此将淫乱的野猫当成仇敌。

赵思琪呀赵思琪，她想，妈妈老说你冲动，做事不经脑子，并没有错。你看到什么狗屁杂志，想都没想就跑来，果然没有好结果，还是立刻闪人吧。

刚要编个借口，溜之大吉，想起从那个所谓孟姐姐处受的污辱，嘴角刚健起来，眼光散到远方，带着无法察觉的讽意，格格轻笑。。。很多年后，每当追随者看到这下意识的表情，他们就知道这位坚韧女士已下定决心，继续苦战到底。
//5月1日 散，不佳
// 也是猢狲失踪的那一天，心乱了。

完全放松下来，反正骰子已经掷出；凯撒已迈过卢比孔河；赵思琪已下定决定报复。

一改之前谨小慎微、有求于人的心态，她自觉已经占据心理上的珠穆朗玛，要圆即圆，要方则方，你们这破地方的命运就掌握在我赵思琪的手里，别以为我只是个高中生，哼哼，哈哈，等坐牢时就晓得姑奶奶的手段了！

心中愈怒，脸上更笑，随口与里娓敷衍谈笑，顺便套问孟任的底细，也去看了更多的猫咪，又添上更多疑问：土猫本就够丑了，不知为何这些养在咖啡馆中的猫咪比外面的更加丑？

“因为漂亮的早给人家挑走啦。虽然猫猫生来平等，但。。。”里娓苦笑，“别看这里几十只猫，其实幼猫早已订下，我们在交接前要训练好猫咪，省得给退回来，大体上猫年龄越大，找到家的可能越小。也不知为什么，很多人觉得成年猫永远养不家。虽然是无稽之谈，但现实如此，我们也很无奈。”

“幼猫训练啊？其实和别的地方也没什么两样。只不过我们鼓励领养人在训练期常来这里，和猫咪一起，与其说我们训练猫，倒不如说我们训练对猫咪毫不了解的人类。”

洗脑，洗脑，你们这里就是洗脑基地，你就是个给流浪猫洗脑成弱智的典型，赵思琪想。

“成年猫多是工作猫，晚上各家店主请回去坐镇，早上再送来。还有一些客人对猫过敏，或者怀孕备孕什么的，也把猫儿送来寄着。剩下就是绝不适合家养也不适合放归的，有残疾的，有特别调皮的，还有王可可那种野生动物。”

一起步入后花园，里娓请赵思琪观赏那里的奇花异朝，赵思琪似懂非懂，但觉迥出尘世。里娓取下架子上的丝带，拉着赵思琪在草丛中逗猫儿抓扑，直玩到气喘吁吁，忘却尘世。

里娓姐，那又是什么？赵思琪终于忍不住，询问房屋内显而易见的大象，即后花园中央立着，直破云霄的黄金人像，那人像还托着硕大的金盘。里娓见她仍然不悟，也不多说，轻轻答道，“那叫仙人掌，又叫承露金茎。三千多年前，孟姐姐将它送给西王母玩，谁想那西王母不上路子，居然又把这仙家宝贝转赠给什么什么皇帝，那狗屁不通的凡夫俗子将之立在建章宫柏梁台上日日承接仙露，以亨永年。孟姐姐在梦中得知，动了真火，将这仙人掌化成熖龙，一口吐息把那皇帝几十年来劳民伤财修建的连云宫闕烧成白地。近日后花园建成，缺个雕塑，孟姐姐于是又把它放置在这里，每日凌晨有人采集露水，拌上琬琰，给生病的猫咪吃。”

呃，赵思琪把手背按在额头上，没有发烧啊，不该幻听。

“传说么，”里娓笑笑，“总是夸大其辞的。孟姐姐怎么会烧别人宫室，烧死人怎么办？烧到猫猫狗狗也不行哈。嘻嘻”

算了，这里的人都神神叼叼的，赵思琪也不感兴趣，不再多问。
// 这里写的还好。是我一直追求 的神话与历史与现实自然交织。

忽然心中一动，草丛好像挪动了几下？没错，草丛、短树、竹篱的摆动传染开去，仔细又看，原来一只又一只猫咪不约而同现身，往仙人掌汇合，最显眼的还是身材壮硕，抓眼亮白毛的大坏猫。

里娓笑着点点头，对身边两个女孩说，“差不多是时候了。”二女应命而去，扶起雲梯二部，蹬蹬蹬跃上仙人掌，解开腰间布囊，将里面的谷物撒入金盘。在场的猫儿们肉眼可见的兴奋起来，多半伏低身体，本能地压缩后肢，嘟噜嘟噜低吼。

不一会儿，数片雲朵移来，灰的，白的，还有团团青雲，一群又一群鸟儿降在金盘上，欢快地啄食每日定时的投喂。

下方的猫儿们看的如痴如醉，赵思琪用全力把目光从大坏猫后脑壳上移走，里娓凑过来说，“很多猫猫都喜欢看鸟，是他们最爱的娱乐，可以一整天也不腻。对了，我们最近搞明白大坏猫是如何抓鸟儿的，他可真聪明，孟姐姐说他的智商有160，嘿嘿，反正比我聪明。所以门禁特严，两道门绝不可同时开启，你进来时看到了。”

“你一定想不到，像他那样的白猫，五里外就能看到的白闪光怎么总能逮住鸟，我们也一直想不通，直到最近南大有些老师听说他来了这里，于是带了好吃的过来看他。”

“都是女教师。有一位和我们讲，大坏猫曾经迷恋她，常常下午一点半在办公室门外喵喵，扒门。后来还学会跳到扶手上开门。让他进来后，也没什么事，就趴在沙发椅上呼呼，任女士抚摸亲吻。那老师下午常常有课，见他睡，就关上门离去，下课时大坏猫多半已经吃了点心跑了。女教师就这样日复一日，简单幸福地拥有着办公室情人，每天盼着他的到来，像回到了十六岁。直到某一日发现这一切不过是个甜美的谎言。。。”

见赵思琪眼睛已转成铜铃，里娓话意更炽，“有次女老师无课，见大坏猫来了，陪他玩了一会，见妙鲜包告罄，于是出门买。购物用不了多久，回来时突然听到办公室传来奇怪的响动。”

“你猜什么？。。。鸟鸣。女士大奇，踮了脚通过门板上嵌的玻璃往里看，竟然。。。竟然没有找到宛啭的鸟儿，只有那只大坏猫趴在文件柜顶，盯着一个黑乎乎的洞口看。”

“过了好一会儿，女士才反应过来，那一直鸣唱的鸟儿就是她的小小情人，大坏猫！女士更疑，又等待十多分钟，一道青光闪过，接着一声死前的悲鸣，就见一只蓝雀的脖子已被洞穿折断，脑袋乏力地倒在一旁，血渐渐从伤口渗出，染红了颈羽，身体不正常地仍在最后的抽搐。女士惊疑不定，退后倒走，在外面逛了两小时才拾得勇气回去。大坏猫自然不见，女士站凳子上检查文件柜顶，发现那里早已密密麻麻布满了暗黑的血淤。”

“那个黑洞是以前装分体空调打的墙洞。后来系里统一换中央空调，施工的人马虎，懒得把洞口填上。女士想，原来他躲在室内，隐蔽皮毛和气味，又学会鸟鸣，勾引鸟儿穿洞来寻同伴。女士怜惜鸟儿，后悔于粗枝大叶，自己掏钱，请了工人封住洞口，又打开大坏猫最爱的妙鲜包，可他再也没有回来。”

“还有一个老师，研究清洁能源的，也过来看他，还带玩具零食。她研究风力发电，算是最热门的新能源中的一个分支，在楼顶安装了几架发电机。大坏猫被捉之前常去她的办公室撒娇。老师知道他的目的：楼顶晒太阳，于是取出钥匙带他上去，看着他缩成毛球，在融融暖意中入梦。渐渐的，老师发现与大坏猫的亲密关系并非电视上天天轰炸的青春纯情偶像剧，倒更像勾心斗角的满清宫庭辫子戏。”

大坏猫一伺老师离去，就把睡意抛到脑后，里里外外，层层叠叠将平台翻遍，寻找被气旋卷入，又被高速扇页割头的倒霉鸟儿。老师得知，沉思片刻，轻松许多，明白从此往后再也无需安排自己的研究生上去偷偷扫除残骸。
//洁白优雅的体型要描述一下

赵思琪听完，也惊异大坏猫的智慧，但更加证实了她一直以来愿意相信的。对里娓这帮人说不出的厌恶，有心令她难过，“我就是皇帝新装中的赤子。”她想，“来扒光你的羽衣！”

想着，从袋中掏出手机，一脸请教的样子，给里娓也看她收藏的图片。
（不要喂流浪猫）

里娓扫了一眼，笑了，毕竟已看过无数遍，“切，仿佛喂猫不要钱一样。我们算过，猫要吃饱，健康，全靠投喂的话三元一日，为了养一只流浪猫一年差不多一千块吧。所以，不管社会如何变化，喂猫人永远只是少数中的少数。有些人眼中只有他看到的喂猫人，他看不到世上漠然转身的大多数。就这么几个城市喂猫人，大多已风烛残年，膝下只有流浪猫儿的老人真能对整个中国流浪猫数量产生千分之一的影响？千分之一是什么？热力学的扰动也大过它了。”

“这照片还非常狡猾，精心选用了狸花猫。自然界中，猫科动物毛色花纹稍有改变即不能生存。你知道吗？正常老虎偶尔也会产下白虎，但为何百万年间白虎只是传说呢？无非白虎极难抓到猎物，稍微遇上一点坏运气就只得饿死。大坏猫这么聪明也只能投机捡鸟，他也许永远也不会明白，为什么还没接近就已惊起群鸦。人类凭自己喜好，选育出超乎寻常的白猫，橘猫，然后再污陷所有的流浪猫都擅长捕鸟？”

“就算大部分猫不会捉鸟，也是，现在很多猫老鼠也不会捉了。”赵思琪又掷出网上常见的矛，“但流浪猫不绝育。一年生几窝，一窝四五只，算一下一年扩大几十倍呢，中间只要有几个会抓鸟，那危害就不小了，可以说很大很大了。”

里娓还是笑，“从前有个小姑娘赶集，买了两个鸡蛋顶头上，边走边快乐地想，两个鸡蛋出一对鸡，这对鸡到时候一天可以下一个蛋，两个蛋又可以再出一对鸡，一对鸡又可以每天下一个蛋，子子孙孙无穷尽也。女孩做着金色的发财梦，幻想用不了多久自己就可以拥有上千只鸡。正在陶醉微熏时，啪，头上顶的蛋打了，只留下两滩嫩黄发泡的液体。是的，我们生活在这个可悲的黄他上，不管理想多么美好，不管理论上一只母猫可以生下多少小猫，一定一定会一头撞到墙上，这墙有个无奈的名字，叫**现实**。”

“我看过英国一项研究，说在他们观测点幼猫长到一岁的几率是10%。为什么呢？因为那里的成猫死亡率也是10%，也就是说，不管这年有几只幼猫出生，能活下来的，只是填补了死亡的那只。是的，现实的墙叫本地可供流浪猫生存的资源，更多的猫只会撞上那堵墙，头破血流而死。”

“不用我说，你也可以想像，流浪猫为了活下去会经历怎样的血腥。然而猫咪社会有一优点却是人类社会也无法比拟的。”

她浑身颤抖，“猫咪社会，**绝对绝对绝对**不会出现八只猫拥有的资源等于最贫穷的三十八亿只猫的财产总和这种事情。并且，也绝不会有下流胚孙子，不，经济学家吹捧那八个人，仿佛没有他们，人类就将不复存在一般！所以如果环境中食物富余了，也许本来只有一只幼猫活到成年，现在变成两只三只，仅此而己，也仅仅某年而已！”

// 2018/5/18
这些当然无法击败赵思琪，作为爱猫人士的她时常在互联网上与那些冒昧无知的流浪猫喂养者斗争，握有丰富的实战经验。见因激动而颤抖的里娓，心中不住笑话，决定给她一记重拳，“姐姐说的必是真的，只是，只怕姐姐并未看到全局，我从哪里读过，流浪猫们据外国专家推算，一共参考灭绝了33个物种呢，所以毫无疑问，它们是生态杀手。姐姐，爱心人士自以为有爱的无知行为反而会害了其它生灵，尤其是鸟类。”
// 理性爱猫就是要。。。

“推算，参与，三十三种，呵呵。。。”里娓笑了，稍平静一点，也娴熟地引用起数据，“关于物种灭绝，我听到的，同样经过外国专家的推算，每年大约有两万七千多个物种走向消亡。两万七千种，**每年**，而猫一共**参与**了多少？三十三种，好像并不是每年吧，还是从1600年开始至今。”

“两万七千多物种灭亡，每年，触目惊心，人类造成的占多少？再细细分解那三十三种，又不难发现多是澳洲、新西兰和诸多鸟屿上的物种。澳洲那种新大陆连兔子多了都会造成生态灾难，所以我们中国也要学他们到处灭杀野兔不成？网上那么生态斗士似乎不知澳洲与中国地理，生态圈的区别呢。按澳洲的办法治理中国，或许就是二十一世纪版的守株待兔、刻舟求剑吧。”

“我有个简单、或许可笑的办法来思考流浪猫对中国的影响。按专家的说法，从DNA看，家猫是非洲野猫的驯化后代。所谓非洲野猫并非仅存非洲，也广泛分布在亚洲。家猫何时进入中国还有争议，倒至少可以肯定，至迟到中唐时，必有猫儿了。有猫儿，必然就有了流浪猫。一千五百年了，如果流浪猫能造成生态灾难，那么早就造成了。似乎不必等到今时今日。为什么过去一千四百年，中国仍然充满了野生动物，生态系统大体尚能维持，为什么偏偏最近一百年出现了无数生物灭绝事件，是因为家猫突然进你出超能力？华南虎家猫灭的？白鱀豚家猫捉的？是人的问题，是猫的问题？是猫的问题，是人的问题？”

“说起来，非洲野猫在中国只有一个亚种叫草原斑猫，生活在甘肃高原。我查了很多资料，目前为止并未有专家怀疑它们是家猫游离人类社会重新野化的物种。这说明什么？说明流浪猫不是野生动物，至少在中国的地理环境下没有长久地在野外生存。说明他们是人类社会的一环，当然是人类社会最低贱的一环。既然是人类社会的一部分，流浪猫的地盘是随着人类活动涨落而随之涨落的。当人类无休无止贪婪野蛮地扩张地盘，侵略野生动物的栖息繁衍地，使得它们无可奈何地灭绝，这倒底是流浪猫的问题，还是人类的问题？不解决人类社会的病根，光想着残害流浪猫，这不就是扬汤止沸之术？就算大面积杀掉流浪猫，无非是为新生幼猫留下了存活空间，不需太久猫一样重新平衡到本地资源允许的水平。”

里娓看着赵思琪的侧脸，聊起了轻松一丝的话题，“家猫离人类太远就会死亡，也许是因为中国这块旧大陆上有太多令人生畏的天敌。也许就是被王可可们吃光的。王可可代表的亚洲豹猫才是我国崇山峻岭、深谷严林的主宰。王可可日常训练的一条就是不把家猫当成敌人和。。。食物个。她在咖啡馆长大，是所有猫咪的宝贝，不会对馆中的猫有敌意，但天性难治，不训练难保她长大后不会攻击陌生气味的家猫。”

// 5/21
赵思琪已然知道眼前易激动的女子无可救药，但怀着“知其不可为而强为之”的信念决心再拯救她一回。手机翻出某动物园园长的社交账号，将他过往言论给里娓看，其中一条引用了美国人的研究，估计出流浪猫每年伤害多少鸟类，强烈建议国家、社会立即采取必要手段以抵销对野生动物的影响。这位动物园园长引用完毕，又添上自己的看法，作为专业的野生动物保护者，他同样大声疾呼立即采取措施扼杀流浪猫，并苦口婆心地告诫那些自以为是的流浪猫喂食者即刻停止错误的行为，回归理性。自然语言就是混乱，搞得我们不清楚园长的扼杀是修辞手法还是动词原义呢。
// 改成赵思琪有意反复刺激里娓，一切都掌握在她手中的感觉

“理性，理性！”里娓毫无节制地狂笑，“理性人士开私家车烧汽油时想不起鸟类；建设琼楼玉宇时想不起鸟类；开垦土地时、随意丢弃塑料制品时想不起鸟类；玻璃非要擦到几近透明时还是想不起鸟类。唯有提到流浪猫时，他们忍不住跳出来挥撒对鸟类的良知！我操他妈屄的理性人士！！！他们根本不爱鸟类，他们只是恨流浪猫罢了！！！”

赵思琪并未听过吐雷综合症，对里娓的粗鄙不堪忍受，刚想开口，谁想里娓更加谍谍不休，丧心病狂起来，
// 故事没想好。。。可能让女娲出场

// 5/28
“理性人士不知为何总与那个买鸡蛋小女孩一般**纯真**。流浪猫固然吃鸟，他们也吃老鼠。老鼠不但传播各种疾病，一样擅长偷雏鸟和鸟蛋，甚至啃食婴儿也不算太新鲜的新闻。所以。。。”里娓面部抽搐，控制不住的发抖，“所以，理性人士是准备将鸟儿从猫的手中抢下，送给老鼠？顺便赠送婴儿？当然能被老鼠啃食的必是穷人家的孩子，能被老鼠传染的也必是穷人。穷人家的孩子，黑人，中世纪的单身女子，这些在理性人士眼中也都算不上人类吧！”

里娓也像这个年龄的女孩平日上网消遣。自从喂猫以来，常逛猫咪论坛，然而她很快发现，越是爱猫论坛越仇视流浪猫，越爱宣传对流浪猫的**仁慈**。里娓先是错愕，继续愤怒，天天与人网上辩论，由此可知她的愚昧。里娓以为小店街的准则——讲道理可以通行于世，花了无数时间研究，形成了自己一套看法，自以为可以————————（未想好）。谁知网上的理性人士发觉辩论不利，只需要使出“我从小就看见猫捉鸟”“我家小区来了流浪猫以后就看不到鸟儿，所以必然是流浪猫把鸟吃光了”这种万能回复。
// 好难，

// 5/30
// 这几段的顺序可以调整，流水账是小学生的办法
“专家那么喜欢通过澳洲、新西兰孤岛数据预测，只是不知道他们为何从不估计如果流浪猫没了，凭空多出来的几亿只老鼠对环境生态的影响。生态系统环环相扣，牵一发而动全身。达尔文还是谁说过：猫肥牛壮，————————（解释），其实猫影响的又何止于牛，穷人家孩子的手指足趾就和猫无关了？”

// 6/1
赵思琪恐惧中后缩，躲避怒火中烧的里娓，等待无明业火将她焚烧成坑中寒灰。谁想里娓一变，添了些自失的浅笑，竟讲起故事来。

“我的名字就透露出我并非汉人。出生边陲，三国的国境线从我的村子穿过。所以对于我们村人来说，国家就是个笑。。。模糊、虽然美轮美奂如天上白玉京，却同样虚无飘渺的概念。轮到上学时，父亲去附近镇上打探，说中国的学校不但免学费，还提供住宿加一日三餐，只针对我们村。于是我成了中国人 ，十岁第一次说汉话，父亲说，这叫什么**统战**，反正就是个难懂的咒语啦。”

“会说汉话以后，我渐渐从各种书中发现汉人的上古传说，汉人记载它族的上古传说中有一个故事与我族的如出一辙。”
// 修修修，太多要修

“我族故老相传，在远古时代，有一个奇特风俗。（这一句写的好烂）到每年我族造主女娲娘娘生日的那天，所有家庭都会举行盛大庆祝，亲朋好友齐聚一堂，尽一切可能准备丰盛宴会，载歌载舞热闹一整天，到傍晚时，再给年龄超过六十的老人换上花花绿绿的新衣，在锣鼓阗咽声中送别。那些老人也欢欢喜喜地背负着三天粮食和水上路，乘月前往村前漆黑幽深的孃山，传说中女娲修道之处，回归**自然**。。。”

“这风俗由来已久，大家习以为常，加上没有老人托累，日子过得红火。只是有一年出了岔子。那一年开年就异像重重，冬雷滚滚，竟将娘山上久已干涸的九口泉眼震醒，激流延濑、宛潬膠盭。众人欣喜这下，奔走相告，说这是女娲娘娘重返人间之兆。到了娘娘生日，村举行了有史以来最大规模的庆祝。也将送别最多老人，毕竟人过五十，除了每天出来晒晒太阳等死，也做不了什么事情了。”

// 6/2
“仪式很顺利，直到大家笑嘻嘻分手时，突然一声炸雷平空爆裂，震得每个人魂风魄散，瘫软倒地。狂风疾雨骤至，村周围种的柏树、栗树、槐树被大风一棵棵拨起，在半空盘桓，又笔直被吸入天之裂隙，消失。是的，就连青天也早已裂成几瓣，雲霓悬挂不住，纷纷堕落，就在半空中化成条条青龙（盘曲），发出绵长嘶鸣，那凄厉的声声嘶吼就此永远铭刻在村民脑中，永无消失的一日。地面也在颤抖，原来平整的地方堆积皴裂，原来沟壑山谷早已绽开，灼眼的岩浆从那裂隙中喷涌，一只只凤鸟从火中诞生又翩跹而去。眼前的孃山动了，岩石咔咔作响，土崩瓦解
// 不会写这种场面
// 山岳化为身躯，虎豹作为纹饰，日月眼睛 她皱眉不欢喜

// 6/3
“最有趣的，长大以后，我才发现不止我族，汉人的书上，汉人记载其它文明的书上都有类似的故事。既然那么多不同民族上古传说都有类似故事，也许我们可以推知，上古时期，或者迫于生存压力，或者别的原因，很多社会都曾驱逐过没有生产能力的老人，任他们自生自灭，**回归自然**。”

“虽然我不是经济学家，但我想经济学家总能从纯经济学的角度可以提出，自然化没有任何工作能力的老人、残疾人、流浪汉、吉普赛人、萨米人或者多余的华人一定会对经济产生正向影响，尤其在今日之社会。”

“今日之社会？”赵思琪猜到谈话的方向，下意识僵硬重复。

“对，现代人越活越长，一个老人退休以后常常还可以活二十、三十年。这二、三十年他也许没办法再为社会贡献，却需要天价的医疗账单（这句不对）。每个国家在我们这时候都得面对老龄化社会的危机。一个年轻人工作不旦得养自己一家，还要负担一个社会1/3以上的老人，这是历史从未见过的一幕。所以应对老龄化社会的办法就是**自然化**所有丧失工作能力的老人？”
// 这种纯理性的探讨有个专有名字的，一时记不清了

“纯从经济学的角度，这甚至是最好的办法。老人不旦消耗社会资源，还不爱消费，不愿释放手中的资源。但可能吗？呵呵，人类社会的问题从来不能仅从一个方向考虑。人类历史上并非没有**聪明人**想过试过这方法，从各族传说可知，只不过，只不过那些驱逐老人的垃圾王八蛋畜生社会早就统统完蛋了！不可能存在下去！女娲娘娘显灵当然是鬼话，人性绝不可能长期扭曲，不管利益的诱惑有多大！”

“人类社会错综复杂，牵一发动全身。表面上看驱逐老人可以取得利益，但从驱逐老人的那一刻起，维系一个社会存在的基础就已分崩离析、荡然无存了！社会既已崩溃，作为社会的一个方面，我想问**皮之不存，毛将焉附？**”

“同样，理性人士，专业动保人士，突如其来的爱鸟人士都希望你以为**流浪猫只是一个生态问题**。可。。。可是猫儿的问题绝不只是生态问题！小小猫儿考验的是我们人类社会有没有资格存续下去的问题！”

// 6/6
无知的里娓激动之下竟然攻击起澳大利亚和新西兰，浑然不知这两个国家是“文明世界”的典范，是她这种小店街鄙漏少女不配攻击的对像，“就算在澳洲和新西兰，流浪猫成为生态灾难，我也要用尽全身的力气反对。哼，如今澳大利亚和新西兰是这世界上数得着的富裕国家。因为是封闭岛屿，那里的生态系统与旧大陆截然不同。先是土著居民来了，带来了狗，造成了一次生态灾难，再后来欧洲人来了，几乎自然化了所有土著，欧洲人自己造就了新大陆上的无数生态灾难，如今他们带去的兔子和猫又一次重创树袋熊和袋鼠的家园。当年欧洲人的子孙掌握着巨大财富，并且屡屡用他们的富饶证明举凡社会制度、政治形态的先进。”

“土著人的子孙还算幸运，毕竟他们的父辈给正义和法律弄得差不多干净，使得社会可以像保护稀有野生动物一样保护**稀有**的土著。国家养得起稀有，正如当年汉武帝养得起侏儒倡优。而当年欧洲人带来的兔子和猫的子孙正惨遭屠戮。毕竟不稀有，也不管兔子和猫为昔日欧洲人‘英勇的开拓史’立下多少攻劳。”

“我不是共产主义者，我并不仇恨私人财产。可我永远也想不明白，为什么这两个垃圾国家对于八个人拥有三十八亿人财富熟视无睹，安之若素，一切宽容，却独独容忍不了小小猫儿？为什么如此富裕的国家为解决流浪猫问题只能想出一个**杀**字？为什么这两个国家拥有如此之多的智能之士，这些伟大的头脑里也只有一个**杀**字？”
// 澳洲 杀猫，保护生态，进步。如果不杀猫了，带领人类进入新文明，现代中国人必作如是观。

// 6/16
“疯。。。疯婆子，这女人失心疯了。”赵思琪看了浑身愤慨的里娓得到了正确的结论，又想起猫会传染一种名为弓形虫的寄生虫，“听说流浪猫是弓形虫的终极寄主，他们会到处拉屎传播疾病，老鼠接触到了就会感染，那些虫子就会爬进老鼠的脑子里疯狂啃食，弄得老鼠发狂，不再怕猫，不对！不旦不怕猫，还会疯狂爱上猫，飞蛾扑火一般冲向肮脏的流浪猫，以便死后控制大脑的寄生虫可以重回猫。。。流浪猫体内，让它成为新的猫粪传染机。这就是弓形上的生存智慧。”

“同样，你们这个害人咖啡馆的女人也一定统统感觉了弓形虫，你们脑子也被弓形虫啃了，于是千方百计掩饰第一生态杀手流浪猫，还四处把脏猫送养，企图让更多无辜人类罹患弓形虫。”

 “对了！忽然想起，生物老师上课无聊，随口讲起弓形虫感染属于粪口传播。大家竟来了精神，讨论说世上居然有人不爱干净到这种程度。你多半舔过流浪猫的肛。。。那里才会得病的吧。呃，恶心，想想都觉恶心。”
 // 粪口传播并不像赵思琪感觉的那样困难。

// 6/19
然而赵思琪懂得绝不可以当面得罪疯子的道理，决定哄哄眼前这个被弓形虫吃了一半大脑的偏激少女，“是啊，这就是人类社会的本来面目，人类犯了错，流浪猫负责赔偿。”

“对的。”里娓笑了，炽热似热情的粗糙大手双双握紧了小手，“赵思琪！你说的太对了！我就想不到这样的话。**人类犯错，流浪猫负责赔偿！**我以前说过，猫只需三元一天就可以吃饱吃好，但流浪猫却连一块钱也没有。我常说，如果任何人好奇自己如果一天连三块钱也没有会面对怎样的生活体验，不需想像，只要走出家门，钻入草丛，顶着满脸蚊虫跳蚤，近距离观察一下流浪猫的生活即可。只可惜流浪猫一无所有，除了那一身蜱虫、跳蚤、鲜血、生命。是的，杀死他们很容易，除了临死前那一声哀鸣，不会给理性人士带来一丝障碍。”

“理性人士也不想了解流浪猫。就好像工厂主也不想了解工人，他们需要的只是听话的螺丝钉；政客们不想了解人民，他们需要的是沉默的纳税人和随时可以为国家送死。。。捐躯的爱国者。在他们眼里，流浪猫只是个移动捕鸟器，他们并不认识也不想认识白咪子。我从来没见过像白咪子一样娴静的猫咪，不爱叫，不爱动，从来不捉鸟，事实上每天下午的后院看鸟活动她从未参加。她对鸟儿连呆育的兴趣也没有，很像古代的欧洲人（需要考证一下？）她唯一感兴趣的就是把儿子带大，事无巨细的教他生活的一切。她也不爱玩，除了陪儿子打闹，她就是这样一只安静的猫妈妈，对人对鸟对世界都没有危害。”

“当然，根据理性人士的**科学**论文，她短暂罪恶的一生已杀死了无数珍稀鸟类，两栖类（虽然她从未生活近过水边），啮齿类和有袋类（她的灵魂也许梦到过澳大利亚）保护动物，至于为什么有些物种珍稀，因为人类将他们杀绝了。至于为什么要杀流浪猫？因为它们不珍稀呀，因为它们身上没有财富呀，要有的话，自然会被人类杀到珍稀嘛。欧洲人称之为物竞天择，适者生存呢。当他们握着屠刀向着流浪猫、犹太人、吉普赛人、印第安人、华人时，一定很自豪，通过个人努力，让世界变得更美好！‘这美丽的新世界！’”

“再说花花。我从未见过像她一样亲人的猫咪。还在南大时，她最喜欢趴在游人聚集北大楼草坪晒太阳、打磕睡。有老妈妈打太极拳时，她一定跑到老妈妈跨下两腿间练习她的喵喵拳，嗬嗬啊嘿。过往行人见了无不哈哈大笑。你要是经过那里，喊一声花花，哪怕你是完全的陌生人，她也会凑到你身边，在你腿上蹭来蹭去，撒娇讨摸，仿佛遇到多年老友。花花也热爱和平，如果两只公猫打架，她一定前去劝架，一顿喵喵拳，公猫捂脸狂奔四散，一场大战消弭于无形。”

一想到花花的可爱，里娓忍不住从心底笑出来，只是一个念头不合时宜的浮上来，“像花花这么亲人可爱的猫咪，为什么，为什么每天经过她的行人成百上千，其中就没有一个愿意收养她，给她 一个温暖的家呢？”

// 6/21
里娓强行压下心中泛起的苦涩，开口道，“就说大坏猫吧，虽然它到处逮鸟，但我们已经抓住他，他再也不能捣蛋了，而且。。。而且你知道吗？孟姐姐经常抱着他道歉，抱歉给他起了臭繁西的绰号。孟姐姐说，大坏猫一逮到鸟，就叼去给她的女友，奶孩子的猫妈妈吃。这可比拔屌无。。。”里娓红着脸，捂嘴，“可比提起裤子就不认账的繁西强一亿五千万倍了。繁西就是这么差劲，你以后见了一定小心！最好躲着走！”

“当然理性人士，爱猫人士永远不想了解他们。理性人士只需从群体中挑出个体，然后把个体的缺陷放大到整个群体就可以了。（再重复一遍，流浪猫到华人）中世纪时，永远正确的欧洲人开始了猎巫运动”
// 这段当时因为过了愤怒，没有写下去
// 猎巫可以放到镜子实验那里写

// 6/29
“就在一百年前，排华法案在美国还是政治正确。是的。”带着无法掩饰的轻蔑冷笑，“是呀是呀，美国当然是美国人民的美国，绝不属于之前世世代代在那里生活了一万年的印第安人和之后背井离乡、九死一生横渡太平洋又消亡于铁路枕石的华人。我不是历史学家，也不是法学家，自然想不出洋大人是如何丑化进而立法迫害整个华人群体的。想来与今日的理性人士相同，不想了解认识个体，专从群体中挑出个例来统一化到群体，再通过媒体发动宣传/洗脑攻势，一个群体中人口多了总有淫邪下流，作奸犯科之辈，我猜华人的罪名是**不信万能的天主，懒惰，不卫生，传播疾病，赌博，犯罪，愚昧等等**，总之都是任何人群中只要想找总能找到的**特质**。于是对他们的迫害不旦正当而且刻不容缓。谁能想到抓完了老鼠的流浪猫，修完了铁路的华工竟拥有同样的命运和未来？”

天真的里娓！完全低估了美国人民的创造力，比如以下证词来源于勤劳勇敢受人尊敬的XXXXXX：
// 补上一段某美国人在法庭上的证词

“有人说这事都过去一百年了，现在纠缠也没了意义。确实，我之所以知道这事也不过因为最近报纸上刊登了美国国会就排华法案道歉的**新闻**。出于好奇和学英文的紧迫需要，找原文一看，才发现美国人也没有道歉啊。我学历低，人也笨，但原文明明用的是regret，遗憾。是的，连道歉都舍不得，所以他们到底在遗憾什么？也许最该遗憾只是没把华人弄得精光，像他们弄印第安人一样。”

“很多时候，我偷偷怀疑那些西方人其实是精致的怀疑论教。当需要掠夺时，没有人比他们更信奉达尔文主义。也没有人比他们更信奉秩序、公正、法律和天知道谁定义出来的普世价值，当他们想保住劫掠果实时。”
// 考虑加一句自讽，站一下脚步

呃，赵思琪瞠目结舌，面对着疯子，“你永远也叫不醒一个装睡的人。”默念着网上名言，赵思琪提出时间不早了，还有一堆事、三个地球活生生等着十六岁的少女拯救，告辞。

别，别急。里娓温柔地握住赵思琪又一只小手，打发人去探看孟姐姐现在是否有空。

赵思琪顺势坐下，“哼！果然！让我一试就试出来了。这里就是传销组织。常言道，上贼船容易，下贼船难。千方百计留客有什么道理？无非就是把你们扭曲的世界观、价值观、人生观强灌到上门客人脑子里，等他们认同了你们再把他榨干。一滴油都不剩。哼，我小赵，赵思琪岂是你这等笨蛋吗？”

// 6/30
当赵思琪再次见到她时，她正抱着大坏猫亲昵。上次捉猫，孟任可撂过狠话，要将他捉来阉割，再放回去，让大坏猫丢脸，成为猫咪社团的耻辱，论为人人欺负的对象，好报一箭之仇。然而狠话还没铿锵落地，大坏猫已扑进她的胸口，两只毛绒绒的白爪爪有节奏地直捣，将孟任的胸脯当作母亲的乳房蹂躏，发出吐噜吐噜满足的哼声。

和所有女性一样，孟任成了俘虏，于是需要一枚借口。

“保护鸟类！”她嚎叫、拍桌子、锤穆穆，“将大坏猫拘禁在咖啡馆，据朕**估计**每年可以挽救七百三十九点五六头无辜鸟类的生命。他又野惯了，如果送养，难免伤人，反而坏了名头。所以只好请大家辛苦一点，照顾他一辈子咯，唉，为了鸟类！”

之后的身体检查更帮孟任坚定了信念。X光胶片显示，大坏猫已有八岁，脊椎骨已可看出明显老化。能怪他已不能像去年，一蹦两米多，孟任想。这样的他放回去，用不了两年，就会失去所有王座，成为。。。

正摸得舒服，孟任一凛，吩咐身边的女子，“大门可要看好，大坏猫没事就往门外檐下望，多半想溜出去掏燕子窝，加餐吃点心。”

女子笑着回道，“知道。孟姐姐讲过几遍，现在大家可警觉了。”

“警觉总是好事。时间长了难免松懈。”孟任默默点头，忍不住想起大坏猫来后的大混乱。

// 7/3
众所周知，咖啡馆中常住着几十只猫。这数字大大超过了野外猫咪社团的正常值。所以相比于野外社团，咖啡馆是由几只德高望重的主母联合治理的。

主母的工作繁重。猫咪打架她们要去劝阻。阳光、新鲜空气、喷泉、空调位置也要她们协调，错开时间以供所有猫咪享用。有猫咪病了，她们要去探望抚慰；有猫咪淘气，她们更加勤奋。。。地追着打。

这些也罢了。对于主母来说，最烦重最浪费时间的还是每天竖起尾巴，歪歪屁股，围绕着强大公猫，卖弄点小风情，好使大公猫们以为自己才是统治者。

多亏了她们的努力，咖啡馆才能享有安宁和睦，甚至平静得好像幸福的时光。然而大坏猫的到来打破了这一切。主母不无尴尬地发现大坏猫，这个以前的老情人竟也是其他主母的男朋友。

母猫们都明白自己的男友不单属于自己，也属于族内的姐妹，并且他呆在族内的时间也不长，想来外面。。。还有骚货等着！知道是一回事，看到是另一回事，当主母看到今日信任的合作者竟然就是昔日痛恨入骨的骚货时，嗷呜，和平结束了。。。

// 7/4
主母们扬起白爪，张口犬牙，弓隆脊背，蓬毛炸尾，火急火燎，手忙脚乱，妒火中烧，抛却往日的默契，剑拔弩张，对着昔日盟友。孟任、里娓等人吓坏了，或抱在怀中，或伏倒地毯，或伸颈猫穴，与主母们交心。

战争停熄了。。。一个上午。至下午时，只见主母各自带着领域内的猫咪，欲打群架，国战！

孟任有点急智，猜中问题的关键。震天动地锣鼓来，“超级大坏猫批斗大会”正式落地。孟任蹦上高台，手舞足蹈，厉声疾呼，“将拔屌无情、用感情行骗的犯人，又名臭繁西的超级大坏猫带上来！！！”在众猫睽睽之下，灰头土面，五花大绑，垂头丧气的大坏猫被一脸疾恶如仇、肃杀严霜的里娓推上来，后面还跟着同样棱角与爱憎同样分明的武装卫士。所谓的武装，在众主母眼中，竟是蜡烛、皮鞭、麻药、手术刀。孟任神采飞扬，还在台上滔滔不绝，用血泪控诉，主母们已悄然散去。

热战升为冷战。也不知过了多久，也不知何时起，猫咪又回到吃饭、睡觉、玩耍的循环，不但把冷战忘了，也不再搭理大坏猫了。

// 7/5
想到这里，孟任豁然警醒，扬头对身边女孩子说，“你们快来，快来，仔细瞅瞅，这大坏猫是不是一脸忍隐，有一种卧薪尝胆的样子。朕看他现在越发怨毒，憋着坏，准备狠狠报复呢。”

诸女子见孟任正抱着大坏猫乱揉乱亲，大坏猫避无可避，只好摆出生无可恋、想咬人又不敢的表情，都抿嘴回道，“唉呦，猫咪哪懂报复，哪会卧薪尝胆，大家都说猫咪智商低，脑子只有三十克。嘿，大坏猫生就一副痞痞的模样，才让人见了又恨又爱、爱到发狂的，孟姐姐多心了。”

说笑间，一个女子见机，凑到孟任身边，寒喧几句，又三心二意地摸摸猫咪，装出忽然醒悟的样子，从提包中取出花花绿绿的几件小衣裳。

这个？孟任犹豫，衣服如此之小，肯定是给一、两岁孩子穿的，只是袖子不是空的，里面用白布裹着棉纱，作出两只小手臂，却是为何？
// 要加描述

虽然无知，但万能的君王却胸有成竹，挥挥手，隔壁厢房里走出两名女子，一人手摇波浪鼓，一人抱着个周岁大的娃娃过来。

那奶娃娃正是王可可去年产下的第二子，因近日家中老人返乡，所以托孟任在白天帮忙照看数日。

两位临时保姆看看衣服微现惊讶，也未多想，拿起就往小孩身上套。

“不对！不对！不是给孩子穿的！”人群中又蹦出个少女，诸人定睛一看，还是那个赵思琪。“你们怎么回事，连猫咪搞笑装都不知道？都流行快一年了，这是给他穿的！”赵思琪教训小孩子一样抢白。

那送衣服的女子这时才回过神，连忙道，“是，是。这是给大坏猫买的，不是给王可可家二宝的，我也不知道他在这里呀。不过。。。不过孟姐姐说给谁穿就给谁穿。。。”

// 7/6
孟任老脸一红，打个哈哈，“朕早就知道了，刚才是猫衣服的错误用法演示，朕这样伟岸高峻的君王岂有不知的道理？啊哈哈哈！倒是没想到赵思琪小小小小的一个小姑娘居然也懂。”

又转脸对喂猫组的成员说，“你们成天和流浪猫打交道，不懂正常。要是多去网上的爱猫论坛就能看到。只是去了那里，多看少说，最好别发言，他们和你们不是一路人。”

有新来的女孩子不明白喂猫组和爱猫论坛为何不同，孟任只得解释，“爱猫其实是外国传来的运动，英文本字是 cat fancier，到了中文变成了爱猫，其实更准备的翻译应叫奇猫爱好者，他们当然爱猫，但或许更喜好奇物。他们将一些长相独特的猫挑出，让猫近亲繁殖，强化出那些独特长相，创造出所谓的**品种**，再以高价将异猫卖予同样好奇的大众。他们爱猫的爱与你们爱流浪猫的爱不太相同。比如流浪猫爱好者常说的‘领养代替购买’，就绝了他们财路。不同道的人凑到一起三言两语就要开战。”

“说起来，”孟任突然高兴起来，消声密谈，“朕听说小店街附近藏着一位神通广大的特工，外号间谍孟，一人抵得上一百个007，擅长煽风点火，挑拨离间，阴谋破坏，吃的还少。怎么样？心动了不，你们只要凑点零食，再买几瓶美酒，请他老人家出山，分分钟就把倒头的爱猫论坛搞垮。哼，取得罪。。。”

“不不！不用请他老人家！”孟任身旁的女孩子吓坏了，忙道，“我们已经和爱猫论坛和解。连门口的牌子都换成更和谐更包容的‘领养优先购买’。还是让他老人家归隐山林，安享清福，就算闲出老年痴呆也别出来啦！”

是么？已经和解了。好无聊，孟任打着呵欠，像根面条，软软滑回座椅。

赵思琪见孟任又一次将目光慵懒寄放在猫衣服上，大着胆子上前为大坏猫更衣。送衣服的女子也上来帮忙，环起摁住大坏猫，防他咬人。经历一番努力，二度飙血，三声惊叫，十分干嚎，众人两眼一花，面前竟了了个崭崭新、别别俏、喷喷香，歪戴着帽子的小小猫医生。众人大笑，孟任更笑得肚皮抽筋，只好趴在桌面上指点，“看哦，大坏猫变成。。。哈哈哈。。。一个小小的人儿啰！”

确实，这类猫搞笑服能在互联网大流行的原因正在于此。略微宽松的衣服挡住了猫咪身体的后半就分。两个袖子里的假手相当于小人的双臂。两猫的前腿即是小人的双腿，当有人从正面看去，看到的不再是猫儿，而是个穿着衣服，两腿直立的人类大头小宝宝。

只是大坏猫一扫之前的威风，无助地扭扭捏捏，缩在桌上，罕见地轻声喵喵。“哈哈，你也有今日。”孟任更加喜悦，“朕平时不让你们买这些猫衣服。强行给猫咪打扮不好，会伤害他门的自尊。但大坏猫这种坏蛋不用客气，反正他鲜有廉耻的。”

// 7/10
于是诸人饶有兴趣地给大坏猫换衣，从猫医生到猫博士，再到西部牛仔、粉红小护士、海盗和胸口有大大S的猫咪超人。众人一阵阵轰笑，还掏出手机，关了闪光灯，左右上下前后乱拍。

孟任皱了脸，蜷缩桌上，五脏六腑笑岔了位置，痛苦嗫嚅，“粉红小护士。。。亏她想的出，大。。。大坏猫原来你就是网上说的女装大佬。哈哈哈。。。”

快乐了一会儿，被娱乐的大坏猫趁人不备，撅起穿着白丝护士袜的圆屁股，嗖的一声，窜上墙角猫爬架最深处的木箱内，再也不肯探头。

诸人更笑。谁知他这一窜惊起了猫爬架上的另一位倦客。一对白爪从猫树梢的木门穿出，越伸越长，触到了屋顶，又一声呵欠打来，听众不禁羡慕，也想学呵欠的主人，快活忘情。紧接着，赵思琪揉揉眼睛，一个大大的小脑袋小心翼翼地探出，左顾右盼，忽然发现目标，喵喵两声，三两下从猫树蹦到孟任眼前的桌上。

“大白醒了，大白醒了。”赵思琪对充耳的低语全然不觉，颤抖地盯着眼前的白虎。

众人兴致不减，又讨论了半天猫衣服，最终得出结论，海盗装最适合一身匪气的大坏猫。渐渐地，孟任谈兴淡了，被大白传染，连打了几个呵欠，诸人一见，也慢慢散开，各回座位。只剩下送衣服的女子和帮忙整理的赵思琪。
//飞天神剑断妖盟，银光一闪，妖头滚滚

// 7/10
“说吧。有什么事？”孟任转头看着送衣服的女子，脸上只剩严肃。

赵思琪中心一寒，坠入深渊。刚孟任转盼时，赵思琪不小心被闪到。她不禁想，不管以后个头长到多高，在眼前的女子面前，只怕永远都要低一头。
// 不佳

“嘿嘿，”送衣服的女子知道关节处到了，面露一千朵鲜花，连忙凑到孟任耳边，细声询问，“不知道执委的名单孟姐姐想好了没？”

执委，全称小店街日常事务执行委员。孟任最近构思，希望成立一个委员会管理日常事务。于是召集小店街父老，请他们投票选出十五人，再由她挑选七人成立委员会。至于如此行事的原因？当然因她倦政，早已懒得处理鸡毛蒜皮，吃喝拉撒的小事。

“执委啊？”孟任沉吟，“我记得你倒是上了大名单，不过排名不靠前。”

嘿嘿，女子尴尬地笑笑，确实不靠前，倒数第二。“所以需要孟姐姐一锤定音哪。孟姐姐说过，这十五人的名单也许只是受欢迎的排名，然而用人还需在才、德、望等多方面考虑。所以如果有人达到标准，却不在名单里，孟姐姐也会召集父老，说明情况，最终邀她进去。毕竟，选执委不是选美，不能谁的票多就一定当选。哦，就算选美也不只看票多了，那么什么东西还在鼓吹票多为胜呢？”女子进了个笑话，有点得意。

“然而，这十五人的名单我看过了，小店街父老妥当公允，并无遗漏。”孟任道。

哦哦，女子拼命用耳朵捕捉有用的情报。

“并且，”孟任再次沉吟，斟酌道，“有三个人已经定下了。”

“那。。。我。。。嘿嘿嘿。”女子渴望中延颈。

“嗯，朕不是满清皇帝，做事不靠鬼鬼祟祟，秘密。告诉你也不妨，你不在三人中。”

哦，女子微怔半秒，没事，还有四个坑。于是转了话题，“我听说王可可已经进去了。”

孟任惊讶，点点头，“你的消息倒灵通。这样吧，说说看，如若当选了执委，你会如何？”

这问题过了空泛，但女子内心一阵激动，面试机会啊。仔细想想，虽然空泛，但来之前早已备过。低头，看去沉思，忽然作答，“当然是全心全意为小店街父老服务啦！但怎样才算全心全意？”女子搓搓手，“说起来，我们七人手上这点权力还不是孟姐姐移交来的？一切听孟姐姐的，按孟姐姐的意思办；为孟姐姐分忧分劳，才是执委会成立的意义，也只有这样，才能服务好小店街的父老！”

“**这里是明堂，明堂！**”孟任气糊涂了，以为自己还跪坐在青蒲之上，“你以为明堂是什么地方？明堂。。。明堂！”忽切之下，找不到辞章，只好粗了嗓子，鬼喊鬼叫，“总之，这里不是满清的军机处！不是！！”

这一声吼骚动了屋宇，诸人纷纷瞩目，女子惊呆了，苍白一片，瑟瑟发抖。
// 摔衣服应插此处

孟任意尤未尽，手指点着她的脑门，炸雷破空，“朕明确告诉你，你出局了！别以为朕不晓得，为了当选，你在背后的小动作！拉票也罢了，还撺掇你的老巴子四处诋毁他人！说！有没有这些事！”

女子呜呜哭起来，抽泣不已，良久，“孟姐姐，孟姐姐，你原谅我为了当选一时糊涂。我可是一开始就跟着你打天下，最早的那批人。如今大家四散，剩下也不多了。还记得那次集资，多少人在背后骂，我可是逮谁咬谁，拼命维护你的。”
// 为美少女侦探团作眼

见她哭着认错，孟任已经心软，再加上，“她果然是傻的。”孟任想，“换一个人，你当众提起往日的窘迫，结局只怕不会好。她连这个也不懂啊。”不由又心生怜惜。

“罢了，罢了。”摆摆手，“朕已经忘了，你好好回去吧。”

// 7/13
拉开右手抽屉，在一撂撂报告中翻捡，抽出一本蓝封皮，假装读起来。赵思琪从旁见扉页上写着《南京大学本部北园有毒植物（对人，对猫犬）品种与分步的初步调查报告》。

孟任初时漫不经心 ，翻了两页后，渐入佳境。贪贪读完，长舒一气，口中喃喃，“原来如此！原是朕多心了呀。”

笑着抬脸，却猛吃一惊，“别哭啦，朕以为你走了呢。多大人还哭鼻子。”

女子这才止住啼泣，又不甘心，眼睛研究着地板，口中发出令赵思琪毛骨悚然的撒娇声，“孟姐姐我就是不服气，我这样的老人怎么现在完全没了用处呢？”

“老人，老人！”孟任又不耐烦，强行压住，“是，像你这样的老资格，如今也就王可可那几个了。但执委乃是小店街的公事。你自己说说，小店街组织活动，举凡吃喝玩乐，比如旅游、聚餐、唱K、哪次你不冲在前面。可一遇到出工出力的话，铲雪、扫洒、巡查、值夜、照顾病患孤寡，你又来过几次？哪次你家里不正好有事？”

噢，女子听了，低下头，又嘟着嘴，想了想，“可是王可可比我还差呢。她可是名单上的倒数第一。加上她身子骨金贵，迎风一吹就倒，那些活更看不到她的鬼影子，可遇到玩的事，比我上心。为什么她能。。。能那个的。”

// 7/16
“人不到，钱到了！”孟任道，“小店街有事用钱，哪次不是她头一个捐款？哪次不是她出的最多？有力出力，有钱出钱，事情才好办。老实告诉你，朕怕她不在里边，才预先说下了不见得完全按照名单的话！心理话，朕中心忐忑，还怕她不愿当执委呢。何况，她参与中枢，知道了钱来自哪里，又用到了何处，以后捐款岂不更。。。哈哈，乐意？”

“你说老人们大多星散了。确实，但她们大多有了自己的家庭，自己的孩子，自己的事业，哪怕只是小小的。而你是什么样的人，你自己心里没点数？这许多年，你不爽就辞，换了二十多家老板。一家两家还可以是老板不良，贪财好色，压榨员工，二十多家都不良的嘛？”

女子听了，唯唯否否，惭愧满地。孟任不睬她，低头看报告。突然又想起什么，问道，“你知道朕原来开蛋糕店的门面吧？房东后来把相临的三四家店面合并，租给那什么世界连锁面包店。可小店街风水不好，大店来一个倒一个。如今那块已空了半年。房东现在情愿再把店面拆成小的，虽多了麻烦，毕竟稳定。你不是一直想开奶茶店么？如何？想开的话，朕跟房东打个招呼，给你留最好的。”

// 7/17 
女子听了，明显激动了，略一思索又疑虑重结，心声，“开店赚钱的时候赚钱，赔钱的时候也是真亏钱，像活活从身上割肉一般。再说了，开店的老板哪有服务员开心快活。别的不说，当老板的，工商、税务、卫生、城管、环保、公安、消防、环境布置宣传小组，天知道还有哪个衙门飞出的任何一只苍蝇你敢得罪？任何一位伸手要钱，让你订报纸、订杂志、去学习、买软件你敢推辞？要的钱是不多，可做了老板，必须学会像孙子一样伺候这帮东西。。人，活的还有什么乐趣？”
// 哪怕是党史，计生办，真以为还管不了你？只有他们愿不愿意弄你

“当然这些人已经被孟姐姐当成害民贼赶跑，再不敢在小店街上走。但孟姐姐的娘子军更厉害，不要钱的最可怕！”

女子知道孟任今年有一项重要工作：在小店街推行开放厨房。要求小店街上的饭店达到卫生整洁透明，随时可以邀请食客参观监督的水准。

这一来老板们愁雲密布。孟任却洋洋得意，见人就吹她的“为政之道，一张一驰。”她说把害民贼赶跑是为**驰**，驰之弊在姑息放纵，现在推行开放厨房是为**张**，张之弊在刻削残民云云。。。总之都是些无人听得懂的落后退步反动愚民言论。

那女子初次听说之时，心里暗暗笑话，觉得她异想天开，大家来小店街不就爱吃个苍蝇馆子么？她的运动绝无成功的指望。

// 7/18
没想到孟任激情澎湃地召集民众集会数次，她的娘子军四出，一批又一批，笑盈盈地敲开一道又一道重门，为各家老板陈说利弊，帮他们核算成本，申请资金。到今日今时，最难的几户已经悄无声息地易帜。
// 不佳

孟任见她犹豫，以为和自己一样，时时痛苦于袋中无银。“以你的资格，从小店街创业基金里可以贷出两万，说说手上还有多少？指不定就够了。”

// 小店街创业基金应该会挪到捉猫记中讲。与和曦好名一起。
小店街创业基金是这两年孟任执政的首要成果。仗着宇宙第一厚的脸皮，她向繁好、和曦所在的繁氏公司及她所认识的富户如王可可等人化来一笔七位数的初如资金，以略高于银行贷款的利率放贷给小店街上的创业者，当然，都是女性！按孟任的看法，“男人都是废物，有了钱非赌即嫖。但女人就不一样，只要严格审核她们的创业计划，妥善跟踪资金流向，审慎的按阶段放款，就不会有风险！”

// 7/19
女子缓慢将脑袋沉下。孟任急道，“一丁点也没有？这么多年你就没攒下钱？”

女子再次抬头时，已是涕泪满颐，“孟姐姐，我家的那个不是东西，懒得上班，我有一点钱，都给他弄走，不给就骂，还。。。打。”

孟任炸了，“那你还不分手！留着过年？！朕派人打断他的狗腿，给你解恨！”

女子听了不敢接话，只是呜呜地哭。

孟任无奈，“当年多少人劝你，你就是犟，不听，非要嫁他。现在还念着他的好。罢了，你们俩口子的事朕也难管。以后他再敢打你，有朕给你撑着腰子，随时派人教育他。”


又道，“你有没想过，他这一身毛病多少都是闲出来的！你们夫妻要是有个小小事业，他每天坐店里十几小时照顾，小店街上还有许多姊妹，多少双眼睛，帮你盯着，他哪有精神和闲工夫去赌？好好想想吧！”

女子果然动心，孟任趁热打铁，“你以前与王可可好的恨不能穿一条裤子，现在为什么淡了？无非你看她暴发了，想着睡上下铺的时光，不久前你们还是同一水平，心里面跨不过，不想像旁人一样捧着哄着她。然而你还指望有钱人主动过来俯就你？这样吧，周六晚上朕约了她吃饭，你也屈尊过来，席上说起这事，朕帮你敲边鼓，看在老姊妹的份子，她无论如何也会帮补你，这样就十拿九稳了，所以你来不来？”
// 看王可可家二宝撒尿一事可能放不到本章了

女子内心也炽热起来，猛然燃烧了一会儿，又缓缓熄灭。她忍不住想起小店街上从未有一家成功的奶茶，为什么呢？仔细回想，有些是老板太扣，奶茶本是暴利行，老板却恨不能卖清水把人；有次是老板太阔，小小店面装修加买新机器，花了十几万。更要命的是，卖的奶茶居然真用纯牛奶冲。屁都不懂，听了些外行聒噪，真以为**天然**的奶茶味道自然就好；还有的老板开了一阵子嫌赚钱慢，又去搞别的；剩下的。。。好多店因为自己心情不对，时而对顾客大呼小叫，时而躲帘子后面吹空调不出来，渐渐就乏人问津了。。。忽而想起，一次，高高兴兴拿了遣散费回家，不小心回头看到前任老板吃力拉下卷帘门的身影。当时并不觉得，此时此刻想起，竟忍不住对着那无奈、孤独、萧疏的影子生出丝丝悔意。。。

去哪里盘下家倒闭奶茶店的设备，再使用食品工业试验过无数次，适应广泛口碑好的配方。装修？搞下门头，买节新柜台，后场不装了，用帘子一隔，反正看不见。帘子要买好看的，柜台多安射灯，几千块就够了吧，也许。。。也许真的可以做起来？

“当然！”孟任很开心，“你设计一个配方，要保证小店街上的穷得叮当响但又馋嘴的丫头们也能喝得起。朕发动她们，天天照顾你家生意。做生意当然有风险，但你开奶茶店风险不大，你是内行，顶多不赚钱，只挣下小两口的工资。就算那样，也好过一直漂着，一个赌，一个打零工吧。有了，这一年看看网络订餐起来了，对我们实体小店也是好消息。回头让繁西给你注册一下，每天多做几十单，赚那些连走动都懒的大学生和肥。。。不犯嫌！”

女子千恩万谢，走了，刚跨出两步，又折回来，口袋里倒出之前的几件猫衣服，可怜巴巴地道，“孟姐姐，这些衣服还请收下。我也不养猫，没有用处。大坏猫这么淘气，我心里喜欢的很，为他花钱，心甘情愿。”

孟任不多想，挥挥手，身边人过来收起。

星姒其时已下班，正坐在前排沙发上品茶，见女子已远，觉得有必要补充几句，于是笑着起身，朗声言道，

// 7/21
“陛下，以后这种礼物还是不收为好。**避嫌！**外面多多少少在传，我们流浪猫基金会连个会计都不请，财务不透明。意思是。。。”

孟任惊异地抬头，倒不是为了传闻，“星星果然从来只见小处，和朕一比，差了十万八千光年。”高兴起来，回答，

“避嫌？贤人尚且不为，况圣人乎？星星没想到你是科举考试和现代考试制度的支持者啊。”

“基金会没有会计，所以。。。所以自然财务混乱，资产被侵吞？无非是小人用自己的心测度君子罢了。”
//  这段当然没有完善

“小店街与外面也大不同。外面的所谓领袖不过活在电视机报纸里。民众，不管有没投票权，真的认识他？而朕就活在小店街上，父老日夜可以与朕相处，朕之为人，诸人深知，又哪需避这避那？”

“基金会没有会计，不旦没有会计，也没有警察坐在每个人脑袋上。四处没有警察，这咖啡馆内竟也没有盗窃抢劫，为何？”孟任声音清越宁静，穿透重重屋宇。“因为小店街上每个人都认为盗窃抢劫是错的，他们以此为耻。正因为以此为耻，所以猫咖内也没有警察，否则就算遍布芡实，他们看不到的地方也必充满了罪恶。不相信的，可以去公安局了解下盗窃这种轻罪的破案率。一个人除非他内心不想做，否则任何严刑峻法也阻止不了他，更何况法律的走卒，按小人辈的想法，又如何收买不来？”

“朕一切以诚待人。小店街父老常来这里消解纠纷。他们来这里无非以为朕可以无私，可从来没有人用刀枪逼着他们前来。”

“凡人们醉心设计各种制度来防奸。然而又能防得了什么？上市公司的规矩多不多，严不严？（需具像）防住了和曦没有？一切以股东的利益为先，公司不就是她的钱柜？”

星姒见状，知道已达目的，唯唯诺诺又坐下了。孟任身边的赵思琪想，“果然，群众不满已经不可抑制，当面质疑，可笑你靠大嗓门喊得她败落。我早知道。”

// 7/22
嘿嘿嘿，脱下了面具的赵思琪对着内心阴沉奸笑。想起最近日日可以在街头看到的政府公告，号召居民们告密，不，用现代汉语写出来叫，提供线索。是的，政府又一次英明无比的发动了扫灭黑社会恶势力的政治运动。目的？崇其高哉，当然为了保卫人民群众的生命财产安全，以后也许还可以堂而皇之地把保卫共和国安全这一条添上去。有傻子问，为什么要添这一条，当然是为了保密啊，蠢货！

猜猜有几条可以把你装进去？赵思琪从旁看着孟任，“第二，把持基层政权，操作破坏基层换届选举。。。还有这，‘利用家族宗族势力横行乡里，称霸一方’，哦哦哦，别忘了这边‘插手民间纠纷，充当地下执法队的黑恶势力’，嘎嘎，就算上面的还拿不住，看看最后‘其他涉黑涉恶违法犯罪’，如何？”

“到你五花大绑，惴惴不安，等着上路的时候，我会去看你，够意思吧，亲口告诉你，我举报了你。我最喜欢看你那气急败坏又对我无可奈何的样子。还会告诉你，枪毙的时候，你得跪下，你以为国家这种暴力机器是说着玩的？从旁的记者一定会极尽笔力描写你屎尿齐流的丑态。不如此又怎么显示杀人者的威严呢？不如此又怎样震慑那些敢于使用脑子的人类呢？你躺在地上，屎尿齐流，训练有素的法医会跳上来，手中握有一根棍子，他是那样坚定，浑身散发着法律的荣光，他俯下身，熟练地用木棍从你后脑的破洞中乱捅乱搅，据说这样可以消除万分之一中枪不死的惊喜，省得烧你成灰时再给你补一下，好有趣啊，你说呢？子弹从后脑射入，面孔破出，两个血窟窿，等你爸妈来领尸体时，他们绝对认不出你是哪一个，可现在他们不用付枪毙你的子弹费了，所以你，快活嘛？哈哈哈，我会告诉你，把一切告诉你，在你脑中只剩下‘是不是今天，正常吃了中饭，又稳了吧’的时候。啊哈哈哈~~~”
// 少了群众的欢呼。（群众为自己的死刑欢呼）

//7/23
// 大白淘气与咖啡馆的矛盾也许只能放到捉猫记里说
周围环侍的女子见孟任忙了半日又说了两天的话，眉心尽是倦怠，从猫树上抱下大坏猫和大白两个开心宝/活宝。孟任果然乐了，从抽屉中拾出各式玩具逗他们。

只是正美美打盹的大坏猫不干了，摆出臭脸，翻翻的，不肯玩那些幼稚的猫玩具。

这，孟任默然片刻，有了主意，用眼光细细逡巡，终于找到了合适的对象。。。欺负。

“赵思琪！你来，你来撒！”孟任招手，召唤盯着彩云发痴的赵思琪。

“我？”从灵魂深处惊醒，赵思琪有点迷茫。

“对，就是你！”孟任道，“你看大坏猫都不爱玩，这是危险的信号，时间长了，只怕会得抑郁症，甚至一个想不开，就会寻短见！你就成了杀人凶手！因为只有你能救他！”

“大坏猫一开始也玩的，但等他弄明白这些逗猫棒都是人类控制的，他就拒绝了。所以朕用了很重的重金为他买了对老鼠手套，戴上手套，再藏到毯子下，大坏猫就会误以为有真老鼠，必然开心的逮老鼠了。手套大的比小的贵两块，谁想一时买小了，这里一百个女生朕看了只有你的手小，所以请你无论如何救一救！”

哦，众人恍然大悟，怪不得孟任站着寻找好久。赵思琪更加不好意思，一对小手被大厅中上百双眼睛盯着。她终于鼓起勇气，怪只怪手足太娇小，只好在重重笑眼的注视下，无奈接过DNA赋予她的使命，戴上了紧致的手套。

一边女子赶紧拿来厚毛毯，覆盖住桌上的小手。大坏猫正用爪子洗脸，此时查觉异样的气氛，于是跳上桌凑热闹。等他一见毯子下的隆起，立刻露出凝重的认真。

“快！动几下，猫儿上钩了！”孟任一如既往的瞎指挥。

赵思琪于是动动，又停下，再猛的抽几下，还无师自通的吱吱两声，像极了大老鼠。闻声，大坏猫不再迟疑，窜起一道闪电，落在氍毹之上，对着隆起，抓挠撕咬。孟任欣慰点首，儒子可教也。

正玩闹间，一位志愿者走来，怀中抱着一只幼猫，向孟任报告说它不会自行进水。

“是的，朕早知道了。”孟任又一次早知道，“它是弃儿，所以认孟孟狗作妈妈，狗狗虽好，但喝水与猫完全不同。它学狗饮水，反而呛到，从此再不敢喝，这么大了，硬是离不开奶瓶。”

“这种情况，需要一名人类，扮成猫咪的妈妈，教它正确的饮水方法。”往脚下一扫，用目光牵来水碗，捏住那幼猫的后颈，提起给诸人展示，“看，它已中度脱水，再不教它，又要断送一条猫命，所以。。。”又一次把期许的目光压在赵思琪的肩上，似乎有千钧之重，当场就要将她的四肢压伏倒地。

又一位志愿者跑来，抱着更加幼小的奶猫，“不好了，不好了！孟姐姐，这只小猫还不会自主排便，幸好发现的早。。。”孟任听完，笑咪咪转向赵思琪。意思已经明明白白写在了脸上。

你！你为什么总针对我！赵思琪忍无可忍，泪珠在身前溅落纷纷。我是来领养猫咪的，不是过来给你欺负的！

针对你？哼哼，孟任全然不惧，在面对好欺负的小姑娘时，她的政策恒等于欺负到底。

“对，没错。就是针对你！明明是高中生，不好好上学，逃课过来，还骗大家说下午没课！哼，当面撒谎，朕难道针对不得？”

“第一眼朕已把你看穿！随便逃课，一逃一下午，既说明你的功课一塌糊涂，也表明你的高中也是一塌糊涂，说，朕讲的对不对？你倒是说啊！”

“嘴上说来领养猫咪，一听说是流浪猫，眼神立刻不对了，恨不能立时逃去！说，你是不是爱猫协会派来的细作？看不起流浪猫，就是看不起朕，就是看不起小店街上的姐妹！说！你给朕讲清楚！”

“朕说把你看穿，就是真的把你看穿！朕站在这里就可以遥知你在学校也是孤家寡人一个，没有一个朋友，没有一个真正的朋友！你自视甚高，觉得自己又漂亮又聪明，怎么会流落到那种学校，与那些笨蛋同学为伍？然而在学校，你并不突出，根本没有同学像你预料的那样接近你，亲近你。反而孤立、惧怕你。你自以为的伟大与冰冷的现实冲突矛盾，让你心理失衡，于是就想到收养一只奇异，所以同学都不能拥有的昂贵宠物猫，好天天拍照片发到班级群里，让他们佩服你，爱你，好吸引远离你的同学 ，因为你每时每刻都不能忍受没有人爱的滋味！这才是你内心真实的想法，对不对？！”

胸膛被剖，心肝被揪出，在众人瞩目下，一一罗列。赵思琪再也无法站立，两膝软倒在地板上，撕心裂肺地哭泣起来。在她悲痛不能自已的泣声中，仍站立着大马猴一样的孟任在地上蹦跳，“说啊！怎么哑巴了？你敢说朕有一个字讲错了吗？！”

// 7/24
“你，你不也养了奇异的猫猫，还说我。”赵思琪在抽泣间隙终于反击，指着歪在桌上，叉开两条大白腿，狂舔屁股的大白，“你养老虎，还违法了！”

嘻嘻，孟任就喜欢烈性女子，在自己重压下还能回击的那种。“说的没错！养奇异猫猫的是坏人，养老虎的是罪犯，统统应该砍头！朕就喜欢看脑袋咕溜溜的。。。正义得到伸张。你以为朕成立轰天五雷讨妹盟是出于私心？哈哈，朕乃诸界之主，哪还有半点私心！唉，说起来惭愧，家门不幸，竟出了不孝的逆妹，居然豢养了一只天界白虎。你们哪！不要被大白蠢萌蠢萌的样子欺骗，不要被这软绵绵肉乎乎的大脚瓜蒙蔽，等他长大成年之时，地球上七十多亿人还不够他吃个半饱的！”

“你们以为朕宠溺大白？错了，朕忍辱负重，是为了打入敌人内部，获取第一手情报。朕这样做绝对绝对不是爱大白！”伸手抱起大白，使劲亲亲、抱抱、举高高，摆出胡旋舞姿，单脚踮立，旋转720度，再接以亲亲、抱抱、举高高。
// 大白脸给亲肿了，

里娓在边上好笑，正要上去解劝，袖子却被掩住，又牵动两下。回头看，原来喂猫组的全体已整装待发。

// 7/26
“别看赵思琪现在不理解我们的事业。只要她追随孟姐姐，用不了几年，她又那么漂亮聪明，肯定可以为大家谋幸福，同时成就自己，这简直就是一定的。”

来到门口吧台，从柜子里取出装有猫项圈的大包裹，提了就往南大出发。这批订做的紫色项圈将为仍在流浪的猫咪标记、编号，顺便驱跳蚤、蜱虫。项圈中的fibronil缓释剂大约可以安全保护至冬月。

只是，只是每次喂猫就兴高采烈的白葭里娓今日却怎么也高兴不起来。一切源于早上她向孟任的汇报。不知道为什么，除了日常项，里娓还汇报说，小店街的流浪猫问题已经解决，而南京大学的也终将解决。也许这是里娓最后一次以喂猫组组长的身份报告，孟任与她明显比平常严肃。孟任今日也特别，并未像平时夸奖里娓，反而问了两个问题。两个问题自此萦绕在心头，不能释怀，甚至有点害怕出发。

幸运的是，再一次看到淘气猫猫的喜悦和同伴刻意的开解重新点燃了她的热情，以至于回来的路上，虽仍不知道问题的答案，已不似来时那般惶惑。
// 为什么这种段落语序，当时过于求变？下一段提前语序正常，似乎现在这样很别扭

“朕问你两个问题。其一，虽然小店街和南大解决了流浪猫问题，但此两处与全天下比，不过一粒砂之于整个戈壁，一滴水之于整个东海。而以我们的人力财力绝不可能解决天下的问题，所以倒底有什么办法可以救天下的流浪猫呢？”

第二个更令里娓困惑，“猫是纯肉食动物，意味着为了使他们存活下去，需要牺牲别的动物，可能是鸡鸭，也可能是鱼儿。另外，爱鸟人士也许有一万个不对，但你也不能否认：不管如何小心，散养在外面的流浪猫多多少少还是会危害鸟类，只是也许远没有他们估计的多。所以为什么流浪猫儿的生命就比鸡、鸭、鱼、野生鸟类高贵？为什么要用其他动物的生命维持猫儿的生命？我们所做的事情到底有何意义？对我们有么？对人类社会呢？”

此时的里娓虽仍不知道这两个问题的关键，但她已经意识到孟任绝非无的放矢，也不会同她一样迷茫不晓得答案。所以，里娓咧嘴笑出，“只要围绕在孟姐姐周围，总有弄明白的那一日。”

回到猫咖时，正赶上喂猫组收录新人的仪式。小店街有许多解决奇奇怪怪问题的小组，但只有喂猫组的新人仪式由孟任自己主持。那位没有创意的君王有次从电视上看到英国女王的授勋仪式，于是偷来应用到小店街上。

里娓来时，礼仪正好进行到一半，孟任手持明晃晃的一柄剑啪啪啪拍在一位单膝跪地女子的肩上，赦然就是笑盈盈还带着泪痕的赵思琪。而孟任正在她惯有、冗长、落后、不着边际的演讲之中。

“很多人说，养猫猫喂猫猫不过是件小事。”

// 7/27
确实。然而小事想做好却也不易。随便举个例子，朕经常看到新人在爱猫论坛晒猫猫照片，然而天真的他们常常忘了将那些偶然含有国产猫粮袋的照片剔除。很快，幼稚的他们就会招睐360度全方位攻击，因为国产猫粮在爱猫论坛的别名叫毒粮。猫咪饲主如果露出一丝犹豫，觉得自己只是分享几张可爱猫咪图片，为什么胡扯猫粮，况且那个牌子的猫粮猫咪从小就吃，次次体检也无问题。饲主们立刻会被扣上虐待猫咪的大帽子，再有**热心**围观群众指引饲主去看烈士墙，看看有多少猫咪被国产毒粮害死。

所谓烈士墙是爱猫论坛的一个板块。隔三差五的总有饲主发贴悼念逝去的爱宠，而观众中总有一拨人会追着贴主询问猫粮牌子。如果不幸是某个国产货，这个话题就将永恒的加入烈士墙，与日月同寿。除非饲主后来澄清猫是摔死的。
// 哈哈，我被自己逗笑了

“恐怖远比真理好卖。”孟任道。

“爱猫论坛的板主们从不提供科学证据，只怕也没有，但他们只须将疑虑悄悄注入爱猫心切的饲主，就可以获得每年七位数的生意，贩卖他们的进口无谷天然粮。”

“有趣的是，爱猫论坛言必谈**科学**喂养，也许这是人类历史上李耳的**天然**第一次等同于**科学**，也许天然食物拥有神秘的魔力，哦，不，**科学**神力保证猫咪拥抱健康活力的生命。至于什么是天然？人类养殖的动植物是否天然？猫粮这种人类加工出来的产品为什么也属天然？哦，板主们很忙，没空理你。你只需一看到**天然**二字：心中就浮现出（各种自然美景），潜意识里将天然与美好划上等号。”

“爱猫论坛虽然不堪，”孟任环顾四下，见群众已露出对爱猫论坛的不屑，却突然抽出回马枪，“他们选择举例的办法也许用心险恶，却也并不能证明国产猫粮就有的安全。所以应该怎样做，是抱着宁可信其有的态度屈从于网络暴民，还是抱着敌人反对的我们就支持的态度？”
// 迷信的态度（我已不知当天加上这评论是什么意思了）

“不！”孟任指指堆在桌上的半米高资料，“破解迷雾唯一的方法只有学！至少猫粮这个科学就足以解决的问题。朕为了猫粮，翻阅至少一百种文献，终于形成了自己的见解，朕也不敢讲朕的意见100%正确，但至少比网络暴民从论坛板主那里学到的要高明不少。而现代科学文献又几乎全用英语写成，朕天天要你们学英语，你们就是懒，畏难，不肯学！”

“朕此次来到人间，见人人都在奢谈自由，仿佛自由是生命不可缺少的养料。可奇怪啊，朕没见有几个人愿意学习的，不懂英语，看不了文献，商人的谎言都识破不了。朕也不知道，连明目张胆，毫不掩饰的谎言的奴役都无法摆脱，人类又有何资格奢谈**自由**？”
// 很难写，这段考虑改写成300字的描述而非对话，原来1000字多点

// 7/28
神清气爽，在又一次嘲笑人类社会之后，孟任继续漫谈，“养猫猫固然小事一桩，然而它能完善你们的人格。有些姑娘也喜欢猫，就是顾虑太多。又担心猫咪淘气，或者长大了不亲人，又有洁癖担心猫咪跳上床或者传播跳蚤，又听说猫毛会引起过敏，又害怕猫咪乱尿乱排泄，又觉得自己收入不够，买不起进口天然无谷粮，反而害了猫儿，所以她永远也养不了猫。只是某一日，她忽然听到道畔草丛窠中传来微弱但声嘶力竭的叫声，她有不详的预感，但仍伸头查看，看见一只或两只幼猫，可能连眼睛都未打开。她离开了，几个小时后又折回来，幼猫仍在，只是奄奄一息。她内心总要挣扎一下，但她的良知轻松取胜。她对自己说，在猫儿眼中，我即是神明，拥有无穷的力量与资源，所以我不能像其他人一样漠然掉头。从那一刻起，她的所有顾虑烟消云散，在她脑中只有一件事，立刻行动，一秒钟也不能浪费。相反的，有些姑娘太莽撞，喜欢猫咪见猫就捡，直到经济崩溃、家人勃谿才如梦初醒。为了保住家庭，也为了猫儿身心健康，不得不来这里，含泪送养一部分。”

“所以养猫虽只是小事，但它可以让犹豫的人变得果决，可以何鲁莽的变得慎重，可以使三分钟热度患者变得持之以恒，可以使单纯的人变成复杂，可以使复杂的人重返天真，可以让嗜欲者变得节制，又可以让节制简敛者变得宽容。”

“养猫虽小，但养好不易。猫养得好，就可以试着养狗狗。狗狗养得好，也许就可以把孩子养好，让他们拥有高贵卓尔的心灵。”

不，不对！星姒惊觉，对着小店街的女孩子演讲，让她们的孩子拥有高贵卓尔的心灵反倒戕害了他们！临危忘身，星姒硬着头皮起来打岔，挤眉弄眼，鬼形鬼相，终于让忘情的帝王醒悟，脸皮一老，又转了话题。

“然而不管饲主多么认真，了解多少科学饲养的方法，猫咪终究是种脆弱的小动物，又不会说话，身体不适不但说不出来，还常常依靠惊人的忍痛能力装出健康的模样。是以，等饲主察觉，往往已步入无法医疗的不治状态。”

“有很多人不愿养猫也正因此，他们一想起终有一日要与心爱之物死别就心生恐惧，不敢面对，毕竟这是一个软弱等同于仁慈，残暴即是勇敢的时代。”

“所以，养猫猫可以令你直面死亡，这个连神明也无法摆脱的结局。终有一天早上，你醒来会发现心爱的毛孩子已变成僵硬寒冷的尸体。可以想像你处于旁人无法想像的痛苦中，但你明白仍有一件事必须尽快完成——处理尸体。所以该怎么办？扒皮吃了？丢垃圾堆，让他与成千上万种垃圾一同慢慢腐烂？‘见其生不忍闻其死’，你会举行葬礼，想办法至少挖个坑将之埋葬。有人会笑话，唯物主义者会告诉你并无灵魂的存在，死亡就是终结，你做的是无用功。道家的信徒会鼓盆而歌，庆祝宠物的死亡，还会觉得你愚不可及，为什么要将好肉从鹰犬的口中抢下送给土中的蝼蚁。你不同他们争辩，因为你懂得，对人类来说，看到或看不到心爱之人腐烂是有区别的，天壤之别。这就是人性之所在。你是人类而非禽兽。”

“经历了这一切，也许有一天你就能想到葬礼也就是**礼之本**，因为葬礼区别了人与禽兽，甚至有时你觉得在人群中有无数披着人皮的禽兽而禽兽中有很多灵魂被困的人类。”

“经历了这一切，你渐渐学会如何面对死亡，如何面对父母、配偶、甚至子女的死亡。当然，最重要的，如何面对自己的死亡。哦，人类的一切荒唐愚蠢都能在这面镜中折射。迫使你去思考你的人生价值，社会、国家、家庭与你的关系。”

侃侃而谈的孟任忽感腹中空空，不好又饿了，还是。。。快点结束废话吧。

“养猫猫当然只是小事。然而朕敢在这里放言，你们这些小店街上的女孩子一辈子也遇不上什么大事！”

“不但你们遇不到，剩余人类也遇不到。按繁娃的说法，华夏五千年历史，兆亿之人类也不过经历过一件大事，那件事还办错了。”

“大事稀罕难遇，小事却天天可见。小事虽小，办好并不易，真能把小事办妥，你们就可以做到日日新，又日新，积累能力，等大事来临，也许不至于手足无措了。”

“也许繁娃是对的，但就算两千多年前的那件事办得差池了，只要这文明的每个人把手头的小事做好，日积月累，聚沙成塔，又何尝不能抵销那件大事带来的坏影响，又何至于发生日后种种不忍言之事。”

“是以，二三子，其勉之乎？勉之勉之！”
// 少了父母感受，少了中年出任CEO

// 7/29
月半中天，和曦醒来，窗外月光注满花园，将那里变成池塘。和曦并无情思欣赏，口渴偏头痛。她知道这是紧张与焦虑留下的痕迹，是她CEO生涯初期的密友。

然而这一次，却因为猫儿。和曦站在落地窗前，向前方看，眼神却是空的。明天晚上，在南大校园见到的小可怜就要永远的来到这个家庭，本应该喜悦的，对不对？

和曦又一次遍历了准备工作。买了五六个猫砂贫放在小楼各个角落，主卧的浴室里就有两个，美国买来最新全自动盆和她之前用惯的传统盆。猫粮？早已备下，实在不行，冰箱里别的不多，海鲜牛排管够。卧室稍差一点，只是简单的重装，加了猫树，猫洞，都买的现成品，不上档次，也与装修风格不合。但猫玩具买了不少，把卧室堆到气闷咳喘。按说应该没有遗漏啦。阿多也和猫儿见了几次，喜欢的不成样子，反而令猫儿有些拘谨，但猫咖的人都说不要紧，再多处处就好。仙林几家二十四小时宠物医院也记下了地址电话，最近的那家昨天还顺便做了拜访。唉，为何我如此不安？
// 少了拥人加钱

转身，想去倒杯水，就见月光不知何时爬上了床幔，苏姬正四仰八叉，肚皮朝天酣睡。嘻嘻，这姿势好像昨天猫儿甜睡的样子。和曦抽过一条薄被为她裹上小腹。

调皮心忽起，要去梳妆台拿口红，给苏姬的胸口绘上大猪头。结果立时遭了报应，被繁西的臭跑鞋绊了，差点摔倒。咒骂着将鞋子和繁西的臭裤头踢到床下，和曦突然找到了心结——是啊，自己明日就将多一个孩子，for better or for worse，生命必将彻底改变。

“花儿对着我微笑、死亡。”双文听吴城念外国诗，正好看见繁好转身，向两人止步的小树林走来，连忙上去迎接。

沉雲密布。。。仗着平日的宠爱，双文忍不住问道，“陛下，大黄小黄真的给人接走收养了？我怎么不晓得？”

繁好狠狠瞪了她一眼，闷声从其身边疾步掠过。喔，双文把委屈、可怜、无助按比例调配成表情，嘟着嘴，低头跟随。

繁好却突然停下，手玩左鬓，缓缓抬头，像是寻找太阳的方位。然而水杉树长的太高太密，树冠遮天蔽日，树下也只好布满喜阴植物。繁好点点头，心中已对大黄小黄的消失有了七成把握，再举玉趾，向前踏出。伴随她的前行，葱莲、石蒜、兰草被她踩倒，用肉眼可见的速度枯萎，又向四方蔓延。

双文吓得直吐舌头，向吴城使眼色，又捧心口，又指指嘴角。吴城胜利地笑了，加紧两步，赶上将家猫带给人间的女神，“陛下，大黄小黄可讨喜了，奴婢也想知道他们的下落。”

呵呵呵，繁好驻了，带着冷笑，“当然被那愚婆害死了。你真以为有人会捡流浪猫家去？更何况他们小时正可爱时不捡，成年反有人捡？”

啊，吴城双文呆立。吴城忍住泪水，“那愚婆如此爱猫，怎么会是凶手？”

繁好答，“虽不是她亲手杀的，但猫儿因她而死！她老把食物放在这树林的边缘，大黄小黄也就在趴在草丛里等她。那里有条路，人来人往的，见惯了人，大黄小黄不再怕人，甚至渐渐亲人，哼，可不就是她害死了！”

“亲人不好吗？”哭泣的双文打断，问道。

繁好白了她一脸，“原来你连这个都不懂。告诉你，

**亲人的流浪猫活不久！**”

// 2018/9/2 晚上又忍不住去白咪子那里，一年过去了，发生了很多事，但我忘了和她说。因我想摘点石蒜给她，可附近没有。我想，也许今年的气候与去年不同。不知道是开过了，还是未开。突然想起，去年这里也没有石蒜，我也是在离这里十几，二十米的小树林另一端摘的。是啊，她倒下的地方并没有这种毒物。于是已经下的结论又动摇了。

// 9/6 前些时候特别苦恼，总觉得在写场景切换时，用的是电视剧的手法，可能从小看电视，身染。昨天偶然重读左传，则如此手法历历在目，由来已久矣。

// 摔角不知放哪里。。。
// 城市里的流浪猫从垃圾桶翻出食物比捉鸟可靠多了
// 孟任最后一节发言少了中年出任公司CEO那一小段