= 猫咪咖啡馆

:docdate: 2018年/2月/15日

“猫咪咖啡馆？猫咪咖啡馆？在哪呢？”赵思琪攥着杂志，立在路的尽头，东张西望。不会地址印错了吧？

路已至尽头，这条街也没听说有岔路，难道错过了？赵思琪扭转脚踝，面向来路。

右手是路面，左手是一处深深庭院，南京随处可见的民国小楼，掩在藤萝爬满的栅栏后。街上行人不多，倒是运处有数个工人搭起塔架粉刷墙壁。另一些人忙着铺排马赛克转，钉设线条。嘻嘻，这么一搞，这些八九十年代的老破楼还挺好看的，真没想到，赵思琪想，仅仅靠刷上两种鲜明互补的颜色，竟意外的抓眼。
// 不满，另赵的想法不能使用过多的文学词汇

又见街对面有两个丫头在跳皮筋，丢沙包，赵思琪望了一会儿，呆呆吐出一口气，一时间仿佛与儿时的自己在这旧巷斜阳里不期而遇。只可惜那时的自己早已遗失，连模糊的影子都无可寻觅。

右手遮住太阳，笑着穿过道路，走向两个小娃儿，“嗨！你们两个！知道猫咪咖啡馆怎么走么？”

“不晓得！孟姐姐说了，问人要讲礼貌，方方最乖的。”胖丫头扭过去，不看赵思琪，弯腰去拾毽子。

扎小辫的胖丫头抱着皮球，迎了来，“圆圆知道。孟姐姐说回答别人也要礼貌的。姐姐你刚才站的地方就是，只不过咖啡馆在院子里，被树挡了。姐姐还请别大声喊，这时间孟姐姐多半在午睡哩。”

好笑！我赵思琪还需要听两个矮冬瓜教训？回头望望来处，果然院子里有个招牌，一行字透出盘屈XX的枝叶。“爪白白咖啡馆？”赵思琪多少疑惑。

方方也走了来，“孟姐姐说了，一个东西有两个名字很正常。就像方方是个乖孩子，又叫方方一样。爪白白咖啡馆就是猫咪咖啡馆，猫咪咖啡馆也叫爪白白。不信看招牌上还有许许多白小爪子呢。”

笑嘻嘻谢过两个丫头，赵思琪咚咚咚跑过街，穿过院门，边跑边想，“此间人为什么全都傻傻的？”

// 2/28
果然好多白爪子，笑了，又见一朵朵白爪爪渐渐从半空中的招牌上延蔓汇聚至紧闭大门的右侧。倾身，只见一个没有标识的圆形按钮被三个跃跃欲试的猫爪簇拥。呃？难不成？赵思琪忍不住学着猫爪的暗示按下电锯。大门发出嘎嘎响声，慢慢顺着轨道挪开。

赵思琪于是走了进去，愣住。谁能想到，大门之后竟是另一道大门。

这。。。忽听右手有响动，转头，只见两个姑娘站在吧台对自己笑。其中一个红朴朴脸的女孩子对自己点头，“才到啊！等你好久了！”
//不畅

// 3/4
连续两天未睡午觉的孟任很暴躁，想咬人。看看面前啰啰嗦嗦争讼的两个人，有心打断，又觉得失礼，只好强忍住，想昨天的事情。

昨天的事更头大。自从将小店街道路封闭，改成步行街之后，孟任中心始终难安。打造步行街固然有一千种好处，一万种必要，但肆意破坏城市交通这一条在她心中挥之不去。
// 小店街特殊交通问题，和街道收费问题放到领地巡视一章

集思广益之下，孟任自以为找到了最佳方案：地下隧道。

小店街地理环境特殊，整条街位于一座小小丘陵之上，所以有人提议从小店街所有的广州路的山脚处开挖一条隧道，直接穿到金银街/北京西路的某处，一劳永逸地解决小店街过于狭窄逼仄，行人与机动车永恒的恶斗。

于是昨日清晨，孟任召集了小店街所有商家，住户代表以及热心公益的活跃份子开会，探讨这个方案的最大挑战，当然也是任何项目的天敌——*钱从哪里来？*

那些家伙有意气朕！孟任拍了桌子！眼前的两个吓了一跳，惊疑不定。抱歉，抱歉！不是说你们。好几年没听过如此精妙绝伦的辩论了，你们请继续。孟任不无尴尬地编成一团，耳朵趴下，让自己看上去不仅小小的，还很可爱哩。

那么多问题可以讨论，就算不谈钱，那么谈谈如何估计预算，如何勘探地理水文，如何满足法律法规要求，对了，他们说挖一切洞穴都归什么倒头人防管，也不知是不是。

就算讨论一下隧道两端出入口具体地点的选择也好哇，如果直接与道路连接，那么需要与交通部门沟通，若是借用已经挖有地下停车场的大单位现成出口，那得找这些口子上的负责人。。。吧。谁能想到昨天早上的讨论从一开始就跑偏了。。。直到太阳西下。

// 3/5
奇怪了，奇怪了！那人为何还未到？

昨日一定撞了太岁，诸事不谐。所以今日特地早起，打了一卦，大吉！今日有吉士相访。打卦就是这样，藏起来，不轻动，偶尔算上一卦没有不准的。这位传说中的佳士多半是来共襄义举，XX革命的。

昨天刚揭晓计划的时候，倒博得了满场赞誉。立刻有人跟上提议：既然挖山建隧道，不如乘势，再修建个地下停车场，供居民、商家使用。

任何大工程开工的成本很高，但顺便多挖个停车场也许只需用到预算的十分之一、五分之一，十分划算，性价比高，停车场车位按居民户数100%配比好了。以后小店街人车彻底分离，居住环境自然水涨船高。

言之有理。孟任听了总要矜持一会儿，摆出凝重的姿态，再点头，像平时一样。所以被人抢了先。又一个女子站了出来，反对。

她说，在城市中心本不必要开车，尤其南京这种公共交通发达的都市。她说，居民中只有5%有车，都是王可可那样的有钱人也说明了这一点。她说，有钱人为了自己方便，却把别人置于危险的境地，我们不能助长这种行为。她说，95%的小店街居民可以无需汽车好好地活着，有钱人就算没有车难道活得还能比常人更艰难？你如果喜欢开车乱晃，何不在郊区买别墅，大路朝天，随便开，又何必非要屈尊挤到小店街上来？她说，其它地方她管不了，但小店街上还可以听到穷人的心声。她说小店街上的人可不像外面的，从小被阔佬请的理论家洗脑，把拥有私人汽车当成天赋人权！她对着所有在场的母亲哭诉，询问她们一生之中，是否常常担心满地乱跑玩耍的孩子被各路无法无天的驾驶者撞倒？她不问她们是否注意到了，许多司机的驾驶习惯是冲着人群，狂按喇叭，知道行人会像四下躲闪的蟑螂一样在最后一刻跳开！

这一番话治愈了全场的嘈杂，只留下凄厉的余韵在会场上空往返周旋。幸好，被点名的王可可蹦了出来。谁都知道，钱包鼓涨的速度可赶不上她脾气的增长。她与她家的三台车完全不能忍受别人的任何指点。而自从王可可发家后以来，她在很多人心中也成了正确的化身，支持者甚众。

王可可和她的支持者，攻击那女子分裂人群，暴露了搞阶级斗争的野心，她们还数落那女人愚蠢，建地下车库正是为了让母亲们不用担心淘气的孩子。她们指出人类的正常欲望是无法强行抑制的，有钱了，让生活更舒适便利正属于此。强行压抑只会适得其反，与其堵不如疏，小店街属于大家，决策万万不能被某些空谈正义之辈裹挟。。。

于是议题偏离了路线，争吵持续了整整一天，幸好孟任始终在场，不然只怕会发生流血事件。最终舆论渐渐向意见极端者倾斜，如同大多数群众运动。。。

孟任头大如斗。

“想不到你这么年轻，还怪漂亮的。”白葭里娓又瞄了赵思琪一眼，“还在上学吧。对了我叫白葭里娓，白葭是姓。不是你们汉人。你要是嫌啰嗦，不妨喊我里娓好了。”

“今天，，，今天下午没课。”赵思琪可以控制嘴巴，可管不住不断涨红的腮红。

白葭里娓善意地笑了，拉着她的手问东问西。得知她的学校是个编号七十多的高中时，更笑，“那里去不去倒也无大碍。”

// 3/6
说着，白葭里娓往墙上一按，赵思琪进来的第一道大门应声缓缓关闭。就在此时，一只白白爪子从门外伸进来，啪的拍在门上，自动门于是改变了方向，又哗哗敞开大口。白爪子的主人随即雄纠纠，气昂昂的挺着胸脯子跑进大门，竖着骄傲的卷尾巴，分明是一只纯白大公狗。

接下来的一幕令赵思琪刻骨难忘。喵喵喵、喵喵喵，毫无纪律的乱叫着，一只又一只毛绒绒的小猫咪跟着打头的大狗鱼贯进入前厅，而为这支杂乱无章队伍殿后的又一只纯白母狗也摇着尾巴进来。

哦哦哦哦哦～，被毛绒绒几吨可爱击中，赵思琪差点晕过去，“牧猫犬？？？”她不禁想。刚要开口，就见里娓蹲下去，嘻嘻嘻笑，伸手去摸，“乔乔，今天又贪玩了，现在才回来呀。”

那领头的大公狗一见里娓，疯了似的就扑过来，在她怀里乱蹭、温存、打滚、舔手，嘴里不停呜呜长啸。

哪知殿后的母狗不开心了，汪汪凶吼，正撒娇的乔乔狗听了，只得离开，前往第二道门口，坐下排队。

赵思琪努力托着下巴看一只又一只小猫咪在母狗的号令下东摇西倒的勉强排成一线。

白葭里娓抿嘴偷笑，“孟孟，你也忒认真了，依我看，不用点，一只都没少。”

母狗回头，不服气，低沉地吼叫。里娓于是与她议论了一会儿，终被且长且短的犬吠声打败，笑着让步，“好好好，只是请你带快点，有客人等着进去呢。”

名为“孟孟”的母狗一愣，似乎忘记了之前的计数，迟疑片刻，只好又凑到公狗旁蹭蹭闻闻，再凑到小猫身上闻闻蹭蹭，从头点数。将小猫一一点毕，母狗凝神回忆，忽然汪汪大叫，一道烟奔了出去。

“抱歉呀，最后**臭繁西**老想逃跑，所以门禁电脑设定的特别严，大门不关上，二门就不会开。看样子只是王可可又溜了，孟孟很快就会将她抓回来。”白葭里娓转身对赵思琪解释。呵呵，呵呵，完全不知道臭繁西、王可可为何物的赵思琪只好干干地陪笑。

孟孟狗奔出去之后，乔乔复活了，先是撩拨身后的猫孩子，可猫咪们已安静下来，乖乖趴在地砖上等妈妈，守纪律。乔乔只好钻进里娓的长裙，围着她的脚趾舔，把她逗得格格直笑。忽然，乔乔发现了新人，想起自己的工作，一路小跑到吧台后，叼着一块木牌子出来。
//里娓的服饰别忘记补上

摇尾巴，昂着头，尽全力将牌子举高，奔来。赵思琪凑近一看，庆幸自己从不戴眼镜。谁能想到那木牌子上的竟是广告：一家小火锅店和一家**正宗**的南京菜馆。

赵思琪立刻像正常路人一样，无法抗拒。弯腰摸摸乔乔的耳朵，抱着他一顿亲，告诉他一定会去他们家的饭店拜访。然而任凭赵思琪如何努力，乔乔总不肯放下牌子。赵思琪不得法，只得保持弯腰的姿势看向白葭里娓，向她求援。里娓指指牌子上的二维码，赵思琪于是省悟，掏出手机扫码，地图立时弹出，标出了两家店的位置和前往路线。赵思琪看看，原来也在这街上，很近，街头到巷尾的距离。

乔乔满意了，放下牌子，伸出爪爪。赵思琪嗷嗷两声，赶忙与他握爪。

孟孟狗这时也回来了，嘴里叼着只小小花豹。花。。。花豹？金钱豹？赵思琪一日之内惊吓太过，能够惊诧的神经暂时疲惫，对不断输入的刺激不再敏感，只余下疑惑重重。

好了，人齐了，大家直起身等待大门关闭。不料乔乔鼻尖又耸，不顾孟孟的反对，重新叼上广告板，冲出大门，拦住了门外经过的数个韩国女留学生。

小店街毗临南京大学留学生宿舍，这里韩国女留学生从不稀奇。稀奇的是，人们总能一眼就将她们分辨出来。

韩国女子也像一切人类，长有一对美丽的眼睛，只奇怪她们的眼睛并非为了寻找世间的美而生。小店街上的韩国女留学生，不分来历背景，燕瘦环肥，统统摒弃自然母亲赐予她们的天然风姿，只向同一种美伏首：商人广告狂轰滥炸之下的大一统容貌。这种标准的商人美要求女性戴上面具，皮肤像死尸一样惨白。至于嘴唇也一定要像恐怖片中的死尸鲜艳的红。据说如此浓妆会显得精神百倍。只是“精神百倍”这种东西如果发现在死尸脸上。。。总之，喊出**“古来万事贵天生”**的李白定不会欣赏她们。

孟孟狗等的不耐，坐到大门门线上，放下口中挣扎不休，鬼叫连连的小花豹，用一只爪子拍牢，再汪汪催促。然而，招揽顾客是乔乔唯一敢于违抗孟孟的时刻。

孟孟无奈，又见猫娃个个抓耳挠腮，知道时间大了，于是再次清声发令，驱走了规矩。轰的一声，树倒猢狲散，几只猫儿化身橙色、青色、白色的闪电，在小小门厅左突右蹙。剩下的打呵欠、磨爪爪、敲脑袋、闻屁股、捉尾巴不一而足。赵思琪也学里娓，蹲下来，与小猫咪一一招呼，抚摸。

// 3/8 

// 3/17
后来她在的店铺倒闭，像每天路边大多数小店一样。经同乡介绍，去了家私立幼儿园打杂，就此别离了小店街。好容易逃离魔窑，冥顽不灵的她仍把孟任平日的胡言乱语当成真理。想起孟任成天挂在嘴边当招牌的**学**与**日新**，也硬着头皮学起了幼儿教育。两年之后，居然混到了幼教资格证，转成了正经的**执证**教师。

谁都知道，中国人最舍得在孩子身上花钱。她的幼儿园赶上了城市化的浪潮，新近又弄来一笔巨额投资，所以像任何企业一样决心大大扩张。十家新建的幼儿园就有一家在小店街，集团还专门任命李梅出任园长，自然是希望和小店街大头头孟任搞好关系，至少不开罪她。

然而李梅一切都好，就是缺乏商人的灵活/油滑。她左手一本幼儿园规章制度，右手一本《幼儿教育》，做任何事情，都要先以查黄历请菩萨式的虔诚在书中寻找依据。别说与书上写的有一个字的差别，就算差一个标点符号，她也必然不行。与她龃龉的男子是小店街上新疆餐厅新聘来的青海大厨，小娃儿长到可以送幼儿园的年龄，本想着就此可以轻松一半，哪知一头撞上李梅的死脑筋，生疼。

已经很不耐烦的孟任，抓住这个空隙，对二人扬唇，“朕也听了半天了。”装出一付剧烈思考、脑海冒泡的模样，良久，“大厨也不足，李梅也过了，都有错。”

见二人呆呆凝望自己，孟任心底得意，得意成抓耳挠腮的猴子王，“先说你，宗教局的人也说，无论小学大学，上学的问题都可以为你出面，就是幼儿园没办法，可见李梅他们没有违反政策嘛。”

又指李梅，“你的死脑筋又犯了，比牛还犟。大厨又不要你专门为他家孩子开餐厅，他自己每天送饭，你为何就不肯行个方便呢？”

李梅急了，“不是不肯行个方便。”把右手的《幼儿教育》摊开，哗哗翻到一页，“孟姐姐请看，这里写着的，写着的！‘幼儿在园中必须按规定吃园餐，这是他们人生第一次参加集体活动，可以潜移默化地培养他们尊重社会、学校以及公众的行为规范的意识，并且纠正由于家长溺爱形成的挑食的坏习惯和唯我独尊的小皇帝、小公主思想。’我们园的规章制度也禁止家长送饭，我马上翻给你看。”
// 有意把引文写成啰嗦的长句。

“够了够了，”孟任摆摆小手，自认很潇洒，“朕怕你根本不懂什么叫民族宗教吧。”

李梅怔住，出身寒鄙的她见过的第一位回族人就是眼前的大厨，还是从他的口中第一次听到**伊斯兰法**四个字。等搞清楚这四字怎么写，她不免在背后偷偷对着先知发出许多亵渎的啧啧声。
//塙有如此漏人，从小到大不知道民族宗教的。

// 3/18 得知李敖去世，想有点感伤又不知在何处，唉

“这样说吧，信道教的不吃狗肉，并非他们挑食，或者怀疑幼儿园的菜肉不洁，来源不安全，而是信仰，你懂了吧？”

没有，完全没有，李梅并不认识任何道士，更没听说道士不能吃狗肉的，所以看上去更加呆头了。

“那你总有亲戚信佛吧？平时吃素斋的。”

这个。。。李梅勉强懂了，她的外婆在生命的最后岁月皈依了佛教，丝毫荦腥不沾。外人看着都觉得不忍，家人更是忧心忡忡。所以，，，李梅从小红旗下长大的唯物主义少女又把食物禁忌理解成**封建迷信**，害人不浅！

呃，没想到讲道理起了反作用，孟任好气好笑，只能求诸擅长的暴力。把电脑屏转动90度，一手揪住李梅的脑袋按桌上，一手在亚马逊图书信息页上指指点点，先吹嘘自己，“看看，像朕这般伟大的君王也懂得学习日新，‘苟日新，日日新，又日新’。哪想到你这小学生倒不学习的，天天捧着十几年前出版的第三版旧书当宝贝，你看看这里，这书去年已经出到第六版，第六版序言有一句，‘除了上述变化，本次修订还添加了民族宗教和少儿心理学内容，这符合社会主义初级阶段生产力与生产关系辩证统一的。。。吧啦吧啦，哼哼哈哈，阿弥托佛嘛咪嘛咪哄，’见鬼，全是咒语？总之，大意你反正了解了，记住，回去第一次事就是去买一本第六版更新一下你的死脑筋，记住了没？”为了帮助李梅回忆，孟任又咚咚咚在她脑壳上凿了三个暴栗，才放手。

李梅早被孟任锤惯，逆来顺受，这时只好委委屈屈先答应下来，但立刻提出了新问题，如果别的家长得知，哪个孩子没有特殊情况，人人要给孩子送饭，那该如何应对？

谁料这问题竟惹了一位未来的英雌排空出世。站在白葭里娓身畔，红衣少女赵思琪早已不耐，天哪，这都什么人啊！不过一件芝麻绿豆大的小事，这伙人唧唧歪歪、唧唧歪歪、唧唧歪歪个不停！冲动之下，脱口而出，“换个说法不就好了？不然还说成开了个专供穆斯林的餐厅，别提家长送饭，全推到宗教局身上，就说他们规定必须要有的。给所有家长两个选项，要么吃园餐，要么吃清真饭。到时候不管几个人，都让大厨按人头送来好了。”
// 排空出世那里还要修饰。赵思琪固然是未来英雌，但她在本书里只零散出现，并非主要人物，如白葭里娓。

李梅听了，缓缓点头琢磨，不提家长送饭，其他家长也不会想到送，加上幼儿园的孩子们也没有奇奇怪怪的信仰，比如佛教，不怕有人乘机要幼儿园再添个素菜馆子，如此看来，这办法也许真的可行？

// 3/19 昨天未见的，今日见了，不见李生久，佯狂真可哀

众人观察孟任的神色，孟任正色道，“又何必骗人？满腹心事，伪饰出来的言辞真以为能欺瞒世人？小店街之人虽笨，可也不都是傻子！这样吧，李梅你明天再来一趟，朕为你写张告示，把事情本末由来一一详明，你贴在大门上，晓谕众生。还有不理解的，让他来找朕。还有，你书上只提到尚同，只想到集体意识，可人生而不同，已不仅仅是宗教；有些孩子体质特殊，吃点豆油都过敏，你们也逼着非要吃定餐？”挥挥手，遣走了李梅。

竟见未被采纳，对于只有十六岁的赵思琪来说本是寻常事，毕竟年龄不到，就像还未长出鬃毛的公狮子，没有哪个母狮会将他放在心上。然而这一次她着实羞红了脸，因为无知的围观群众听了眼前和自己一般大的小女孩胡说，个个露出信服的表情，仿佛听到的是黄钟大吕，金声而玉振。

“啊呸，好恶心。被我抢先了，这小毛丫头才特意换一种说法出风头，保持她在众人眼中的地位。如果一开始我用她的说法，她一定换我的，为了不同而不同，哼哼，就有这种人。”

大厨见事情解决，喜上眉梢，正待告辞，却低估了孟任。“你也知道，李梅收你家娃是出于善意，许多人劝李梅，为你说话也是一份善意。你的孩子现在信仰你们的圣教，因他生来就是你的孩子。等他长成，如果有别的选择，别的信仰，也请你尊重，最少不干涉，看在今日这许许多多在场人士善意的份上。”

大厨呆了，全然想不到还有这么一出，嗫嚅半天，像坏了的闹钟，身子乱颤，戏味十足就是发不出一丝声响。

有个女孩见孟任要打发他，忙窜出来，咬着耳朵密报。愤怒的火星迸发，炸雷在寥廓的屋㝢内来回激荡，

“什么？打孩子？？！！你别走，你给朕讲清楚，为什么事打孩子？”

“小孩子不听话就该打？你还占理了？你那么占理，为什么把他拖到后面的车棚偷偷打？不敢在路边光明正大的‘教育’？要不是你下手太狠，车棚那边的声音也不会给姑娘们听到！”

“下次小孩子不听话，你把他送这里。你不会教育，朕这里最多有耐心的阿姨。你再敢打孩子，别的朕做不到，在小店街上你只怕混不下去！”

见大厨服软，孟任绯颜略霁，“对了，你老婆怎么回事？每天在你店里打杂、炒菜、收银，托人几次，就是不肯登朕的大门？是看不起这里的女孩子还是想学离群索居的商？商也悔于失群，她难道还贤于商？你记得带话，不管疲倦还是XX，都可以来这里休憩，嬉游。就算龙生九种，个个有别。这里人多，必有她能合得来的，总好过天天守着你。贵教的声望被一些极端份子拖累，你们又不出来交际，在旁人眼里，难免觉得神神秘秘，甚至鬼鬼祟祟。就算为了贵教，她也应该来这边教育出身于不毛之地、无知愚昧，连伊斯兰三个字都没听说过的女孩子。她不肯来，莫非是对贵教信心不坚的缘故？”

大厨失魂落魄地走了，得一而失二，总算见识到小店街统治者真正的颜色。

// 3/21 胡适一系学者还是太墨家了，这也许是李敖喜欢中共的原因。

// 3/22 
上午的事情终于完结，见无人瞩目，孟任偷偷伸了个长长懒腰。又想起居然有人胆敢抢在自己前头说话，差点扫了威风，忍不住要把那个捣蛋鬼滴溜出来。

通了激光的目光一旋，立即锁定目标：缩在角落，满肚皮不适，怀疑自己为何生在此处的赵思琪。

“你终于来啦！”噌，孟任窜出，两只爪子啪地握住赵思琪的小手，热情如火，将她拖到屋隅的小沙发上坐了。小沙发四周摆满奇木休萝、博物架作屏障，是个闹中密谈的好地方。

本感到冷落陌生而手足无措的赵思琪被这突如其来的热情打倒，本能地挣扎，却被大擒拿手死死按住。

“你们是怎么招待客人的？看茶，点心！”两个姑娘笑着得令而去。须臾，捧回来热腾腾的焦糖玛奇朵和喷喷香大块头南瓜豆腐慕丝奶酪蛋糕。

赵思琪眼看着会大擒拿手的老师傅使出失传已久的十九式三十七手“狮子搏兔”擒住了一块蛋糕大嚼，渐渐鼓足勇气，怯生生、傻乎乎地微声问道，“我们认识吗？对不起，我。。。我记性不好。。。”

// 3/23
“认识！认识！当然认识！四亿八千万贤劫之前，兜帅天须弥宫药师殿，朕登法烬台为大罗金仙讲解混元道果，你于众仙佛之中最先领悟，欣然向朕躬行礼，暗递秋波。”

“再经恒河沙数之无量空劫之后，于昆仑界玄圃閬風山上的穷桑之野，才能与你再次相逢，朕于是为你拈花，对你破颜微笑。之后朕还会为你歌唱，

‘两只老虎，两只老虎，跑滴快，跑滴快，一只没有耳朵，一只没有尾巴。。。’”

@$@#%$^$#!@#^%$!

见赵思琪已然精神错乱，孟任终于感到了一丝丝羞愧，单手摩挲后脑壳枕骨，打着哈哈，“戏言，戏言尔。”

倏地，又突然将脸孔凑到赵思琪鼻梁一寸处，神秘兮兮地眨着左眼，仿佛心照不宣，道，“虽然今日初见，但观这位义士形貌，朕自然了解你的来意。”

哦，赵思琪想起来意，倒觉不好意思，明明是来求人的，哪经得起这番盛情。

见她默认，孟任更是高兴，抬起一手，嗷嗷怪叫，“来人！快去买大公鸡，要最雄壮的！雪刀一挥，鸡头咕噜噜乱滚，血溅三丈！对了，还缺一位见证，难得如此高兴，朕就赏太上老君一个天大的面子，差他下界见证盟约！咦，瞧你面露不满，莫非嫌弃李耳老贼不成？那就西王母吧。不妥不妥！西王母还欠朕三个桃子呢，天大的怨毒，怎可让他乘机化解？”

“求求你，求求你了。”赵思琪气若游丝，哭了，“告诉我到底怎么回事，别。。。别买大公鸡了。”

不买大公鸡？孟任皱皱眉头，只办正事的话，乐趣就没有了，看着无头公鸡乱蹦。。。恶狠狠将赵思琪右腕寸关朝上翻，露出尖锐长牙，“没有公鸡的话，朕的血又不能多出，只好委屈你啦。”
// 孟任要杀大公鸡小说之言，别当真了

“不对，我不是来参加盟约的。你理解错啦！”

// 4/3 玳瑁猫醜醜失踪48小时，甚不安。也许她和她妈妈都有流荡基因，也许她还会回来，也许

所谓的喵医生就是两名从前雷渊宫的宫女，最早在猛氏馆为冥后照顾她心爱的虎群，后来和人类私奔跑了，最近随着孟任回归，立青旗延揽旧部，又不和羞地乱跑了回来。

孟任看她俩有些特长，就花钱送二人到外面的宠物医院实习，补充落下三千年地球动物医学。因为两人轮流，平时总有一个留在咖啡馆里无证非法行医。

赵思琪透过玻璃门好奇地偷窥医院挂号处。位于二楼西北角上的医院看样子占据了三间房屋，大部分为毛玻璃阻挡，只余下赵思琪驻目的那间。

温暖又不失热情的配色，现代简约的登记台，台后照例挂着廉价的大幅猫咪写真，只不过这只猫咪热衷对着雪山打呵欠，啊，雪豹。

雪豹下方坐着一位三十多的女士，专注地看着手上大八开的专业书，并未留意门外。

照片左边贴着价目表，赵思琪没养过猫狗以及一切宠物，不知深浅。另一面墙挂了四幅画，用木框装裱。赵思琪不看则已，定睛细看，第一幅名曰“猫咪先天经络图”，右一幅“猫咪六脉神剑”，再右一幅“猫咪玉女心经”，最后“猫咪阴阳和合交欢大乐神通”。每画都细细标出穴道、经脉和真气运行方式。如果不是绘画技巧等同于幼儿园大班，也许真有人相信。

白葭里娓只好不无尴尬地表示，“孟姐姐喜欢开玩笑，人很幽默的。又爱看武侠小说，就画了这些当装饰，当然不是真正的秘笈啦。”

// 4/4 醜醜的弟弟猢狲今天看着似乎也没食欲的样子。

// 4/15 
终于下到一楼，赵思琪首先吃了一惊，记得来时还显空阔的一楼此时竟快客满，密密麻麻，坐满了各式各样用发型争奇斗艳的女子。

白葭里娓解答了疑惑，“通常这时间人最多啦。饭店服务员忙完中午场就来店里小坐，逗逗猫咪，把午间的不快抛下，到四点五点再回去上班。”

窗边的好位置已经满了，里娓带着来到中央大道旁的长方桌坐下，又起身去志愿者吧台拿茶点饮料。

赵思琪逛了一圈二楼又说了许多话，精神略显倦怠，正好坐着盘桓一下精力，只是。。。心中有一块总觉不妥。

正纳闷间，两个小姑娘唉呀唉呀跑来这一桌。“不好了，一忙就忘，今天大坏猫多关了半小时，等会儿他会不会生气咬人哪！”

赵思琪见那两个姑娘头戴猫耳头环，知道她们是里娓口中的志愿者，便朝他俩微笑。两个姑娘见了，也忙回以微笑。其中一人抽手到桌面之下，不知扣到什么机关，桌子正中三分之一的桌面缓缓弹起，露出了它想隐藏的真相——钢化玻璃制成的箱子，同时也是桌子的支撑腿。另一位姑娘早已戴上厚皮手套在半透明的箱体内寻找，一会儿捞出只枯黄草色的小猫，放桌上。又下去捞，抱出一只小小花豹，像是赵思琪来时见到的那一只。姑娘最后一次探身，出乎赵思琪的意料，掏出一只硕大无朋的白猫，如此之大，若不是他胖胖的圆脸正在生气，时不时徒劳无功地咬在厚皮手套上，赵思琪一定以为抱出来的是狗狗。

“好吼，好吼。不生气。”姑娘拿出营养膏，桌面上趴着的三只猫激动起来，轮流伸长脖子舔。

“我们把这叫社会化笼。”里娓回来后解释，“猫咪长大的前六个月如果没有充分接触，就会终生恐惧人类。猫猫胆小敏感又总以自我为中心，所以一旦看到人类走近，总以为我们的目标是他们，于是望风而逃。我们给这个特制的玻璃箱子贴了反射膜，使外面很难看清里面，而对里面的猫咪却是透明的，很像汽车上常贴的那种。这样，大厅中央虽然人来人往，但行人不会注意到桌下箱子里还藏有猫，而箱中的猫因为无可回避，只好慢慢体会出人类不可怕，他们的目的也不在自己的道理。当然，每次训练结束后也要用美食安抚，令他们不至生出反感之心。”

赵思琪又问效果，“大部分猫都有效，但偶尔也会激起公猫的领地意识，四处滋尿，那样的话我们也有别的方法。”