= 猫咪咖啡馆

:docdate: 2018年/2月/15日

“猫咪咖啡馆？猫咪咖啡馆？在哪呢？”赵思琪攥着杂志，立在路的尽头，东张西望。不会地址印错了吧？

路已至尽头，这条街也没听说有岔路，难道错过了？赵思琪扭转脚踝，面向来路。

右手是路面，左手是一处深深庭院，南京随处可见的民国小楼，掩在藤萝爬满的栅栏后。街上行人不多，倒是运处有数个工人搭起塔架粉刷墙壁。另一些人忙着铺排马赛克转，钉设线条。嘻嘻，这么一搞，这些八九十年代的老破楼还挺好看的，真没想到，赵思琪想，仅仅靠刷上两种鲜明互补的颜色，竟意外的抓眼。
// 不满，另赵的想法不能使用过多的文学词汇

又见街对面有两个丫头在跳皮筋，丢沙包，赵思琪望了一会儿，呆呆吐出一口气，一时间仿佛与儿时的自己在这旧巷斜阳里不期而遇。只可惜那时的自己早已遗失，连模糊的影子都无可寻觅。

右手遮住太阳，笑着穿过道路，走向两个小娃儿，“嗨！你们两个！知道猫咪咖啡馆怎么走么？”

“不晓得！孟姐姐说了，问人要讲礼貌，方方最乖的。”胖丫头扭过去，不看赵思琪，弯腰去拾毽子。

扎小辫的胖丫头抱着皮球，迎了来，“圆圆知道。孟姐姐说回答别人也要礼貌的。姐姐你刚才站的地方就是，只不过咖啡馆在院子里，被树挡了。姐姐还请别大声喊，这时间孟姐姐多半在午睡哩。”

好笑！我赵思琪还需要听两个矮冬瓜教训？回头望望来处，果然院子里有个招牌，一行字透出盘屈XX的枝叶。“爪白白咖啡馆？”赵思琪多少疑惑。

方方也走了来，“孟姐姐说了，一个东西有两个名字很正常。就像方方是个乖孩子，又叫方方一样。爪白白咖啡馆就是猫咪咖啡馆，猫咪咖啡馆也叫爪白白。不信看招牌上还有许许多白小爪子呢。”

笑嘻嘻谢过两个丫头，赵思琪咚咚咚跑过街，穿过院门，边跑边想，“此间人为什么全都傻傻的？”

// 2/28
果然好多白爪子，笑了，又见一朵朵白爪爪渐渐从半空中的招牌上延蔓汇聚至紧闭大门的右侧。倾身，只见一个没有标识的圆形按钮被三个跃跃欲试的猫爪簇拥。呃？难不成？赵思琪忍不住学着猫爪的暗示按下电锯。大门发出嘎嘎响声，慢慢顺着轨道挪开。

赵思琪于是走了进去，愣住。谁能想到，大门之后竟是另一道大门。

这。。。忽听右手有响动，转头，只见两个姑娘站在吧台对自己笑。其中一个红朴朴脸的女孩子对自己点头，“才到啊！等你好久了！”
//不畅

// 3/4
连续两天未睡午觉的孟任很暴躁，想咬人。看看面前啰啰嗦嗦争讼的两个人，有心打断，又觉得失礼，只好强忍住，想昨天的事情。

昨天的事更头大。自从将小店街道路封闭，改成步行街之后，孟任中心始终难安。打造步行街固然有一千种好处，一万种必要，但肆意破坏城市交通这一条在她心中挥之不去。
// 小店街特殊交通问题，和街道收费问题放到领地巡视一章

集思广益之下，孟任自以为找到了最佳方案：地下隧道。

小店街地理环境特殊，整条街位于一座小小丘陵之上，所以有人提议从小店街所有的广州路的山脚处开挖一条隧道，直接穿到金银街/北京西路的某处，一劳永逸地解决小店街过于狭窄逼仄，行人与机动车永恒的恶斗。

于是昨日清晨，孟任召集了小店街所有商家，住户代表以及热心公益的活跃份子开会，探讨这个方案的最大挑战，当然也是任何项目的天敌——*钱从哪里来？*

那些家伙有意气朕！孟任拍了桌子！眼前的两个吓了一跳，惊疑不定。抱歉，抱歉！不是说你们。好几年没听过如此精妙绝伦的辩论了，你们请继续。孟任不无尴尬地编成一团，耳朵趴下，让自己看上去不仅小小的，还很可爱哩。

那么多问题可以讨论，就算不谈钱，那么谈谈如何估计预算，如何勘探地理水文，如何满足法律法规要求，对了，他们说挖一切洞穴都归什么倒头人防管，也不知是不是。

就算讨论一下隧道两端出入口具体地点的选择也好哇，如果直接与道路连接，那么需要与交通部门沟通，若是借用已经挖有地下停车场的大单位现成出口，那得找这些口子上的负责人。。。吧。谁能想到昨天早上的讨论从一开始就跑偏了。。。直到太阳西下。

// 3/5
奇怪了，奇怪了！那人为何还未到？

昨日一定撞了太岁，诸事不谐。所以今日特地早起，打了一卦，大吉！今日有吉士相访。打卦就是这样，藏起来，不轻动，偶尔算上一卦没有不准的。这位传说中的佳士多半是来共襄义举，XX革命的。

昨天刚揭晓计划的时候，倒博得了满场赞誉。立刻有人跟上提议：既然挖山建隧道，不如乘势，再修建个地下停车场，供居民、商家使用。

任何大工程开工的成本很高，但顺便多挖个停车场也许只需用到预算的十分之一、五分之一，十分划算，性价比高，停车场车位按居民户数100%配比好了。以后小店街人车彻底分离，居住环境自然水涨船高。

言之有理。孟任听了总要矜持一会儿，摆出凝重的姿态，再点头，像平时一样。所以被人抢了先。又一个女子站了出来，反对。

她说，在城市中心本不必要开车，尤其南京这种公共交通发达的都市。她说，居民中只有5%有车，都是王可可那样的有钱人也说明了这一点。她说，有钱人为了自己方便，却把别人置于危险的境地，我们不能助长这种行为。她说，95%的小店街居民可以无需汽车好好地活着，有钱人就算没有车难道活得还能比常人更艰难？你如果喜欢开车乱晃，何不在郊区买别墅，大路朝天，随便开，又何必非要屈尊挤到小店街上来？她说，其它地方她管不了，但小店街上还可以听到穷人的心声。她说小店街上的人可不像外面的，从小被阔佬请的理论家洗脑，把拥有私人汽车当成天赋人权！她对着所有在场的母亲哭诉，询问她们一生之中，是否常常担心满地乱跑玩耍的孩子被各路无法无天的驾驶者撞倒？她不问她们是否注意到了，许多司机的驾驶习惯是冲着人群，狂按喇叭，知道行人会像四下躲闪的蟑螂一样在最后一刻跳开！

这一番话治愈了全场的嘈杂，只留下凄厉的余韵在会场上空往返周旋。幸好，被点名的王可可蹦了出来。谁都知道，钱包鼓涨的速度可赶不上她脾气的增长。她与她家的三台车完全不能忍受别人的任何指点。而自从王可可发家后以来，她在很多人心中也成了正确的化身，支持者甚众。

王可可和她的支持者，攻击那女子分裂人群，暴露了搞阶级斗争的野心，她们还数落那女人愚蠢，建地下车库正是为了让母亲们不用担心淘气的孩子。她们指出人类的正常欲望是无法强行抑制的，有钱了，让生活更舒适便利正属于此。强行压抑只会适得其反，与其堵不如疏，小店街属于大家，决策万万不能被某些空谈正义之辈裹挟。。。

于是议题偏离了路线，争吵持续了整整一天，幸好孟任始终在场，不然只怕会发生流血事件。最终舆论渐渐向意见极端者倾斜，如同大多数群众运动。。。

孟任头大如斗。

“想不到你这么年轻，还怪漂亮的。”白葭里娓又瞄了赵思琪一眼，“还在上学吧。对了我叫白葭里娓，白葭是姓。不是你们汉人。你要是嫌啰嗦，不妨喊我里娓好了。”

“今天，，，今天下午没课。”赵思琪可以控制嘴巴，可管不住不断涨红的腮红。

白葭里娓善意地笑了，拉着她的手问东问西。得知她的学校是个编号七十多的高中时，更笑，“那里去不去倒也无大碍。”

// 3/6
说着，白葭里娓往墙上一按，赵思琪进来的第一道大门应声缓缓关闭。就在此时，一只白白爪子从门外伸进来，啪的拍在门上，自动门于是改变了方向，又哗哗敞开大口。白爪子的主人随即雄纠纠，气昂昂的挺着胸脯子跑进大门，竖着骄傲的卷尾巴，分明是一只纯白大公狗。

接下来的一幕令赵思琪刻骨难忘。喵喵喵、喵喵喵，毫无纪律的乱叫着，一只又一只毛绒绒的小猫咪跟着打头的大狗鱼贯进入前厅，而为这支杂乱无章队伍殿后的又一只纯白母狗也摇着尾巴进来。

哦哦哦哦哦～，被毛绒绒几吨可爱击中，赵思琪差点晕过去，“牧猫犬？？？”她不禁想。刚要开口，就见里娓蹲下去，嘻嘻嘻笑，伸手去摸，“乔乔，今天又贪玩了，现在才回来呀。”

那领头的大公狗一见里娓，疯了似的就扑过来，在她怀里乱蹭、温存、打滚、舔手，嘴里不停呜呜长啸。

哪知殿后的母狗不开心了，汪汪凶吼，正撒娇的乔乔狗听了，只得离开，前往第二道门口，坐下排队。

赵思琪努力托着下巴看一只又一只小猫咪在母狗的号令下东摇西倒的勉强排成一线。

白葭里娓抿嘴偷笑，“孟孟，你也忒认真了，依我看，不用点，一只都没少。”

母狗回头，不服气，低沉地吼叫。里娓于是与她议论了一会儿，终被且长且短的犬吠声打败，笑着让步，“好好好，只是请你带快点，有客人等着进去呢。”

名为“孟孟”的母狗一愣，似乎忘记了之前的计数，迟疑片刻，只好又凑到公狗旁蹭蹭闻闻，再凑到小猫身上闻闻蹭蹭，从头点数。将小猫一一点毕，母狗凝神回忆，忽然汪汪大叫，一道烟奔了出去。

“抱歉呀，最后**臭繁西**老想逃跑，所以门禁电脑设定的特别严，大门不关上，二门就不会开。看样子只是王可可又溜了，孟孟很快就会将她抓回来。”白葭里娓转身对赵思琪解释。呵呵，呵呵，完全不知道臭繁西、王可可为何物的赵思琪只好干干地陪笑。

孟孟狗奔出去之后，乔乔复活了，先是撩拨身后的猫孩子，可猫咪们已安静下来，乖乖趴在地砖上等妈妈，守纪律。乔乔只好钻进里娓的长裙，围着她的脚趾舔，把她逗得格格直笑。忽然，乔乔发现了新人，想起自己的工作，一路小跑到吧台后，叼着一块木牌子出来。
//里娓的服饰别忘记补上

摇尾巴，昂着头，尽全力将牌子举高，奔来。赵思琪凑近一看，庆幸自己从不戴眼镜。谁能想到那木牌子上的竟是广告：一家小火锅店和一家**正宗**的南京菜馆。

赵思琪立刻像正常路人一样，无法抗拒。弯腰摸摸乔乔的耳朵，抱着他一顿亲，告诉他一定会去他们家的饭店拜访。然而任凭赵思琪如何努力，乔乔总不肯放下牌子。赵思琪不得法，只得保持弯腰的姿势看向白葭里娓，向她求援。里娓指指牌子上的二维码，赵思琪于是省悟，掏出手机扫码，地图立时弹出，标出了两家店的位置和前往路线。赵思琪看看，原来也在这街上，很近，街头到巷尾的距离。

乔乔满意了，放下牌子，伸出爪爪。赵思琪嗷嗷两声，赶忙与他握爪。

孟孟狗这时也回来了，嘴里叼着只小小花豹。花。。。花豹？金钱豹？赵思琪一日之内惊吓太过，能够惊诧的神经暂时疲惫，对不断输入的刺激不再敏感，只余下疑惑重重。

好了，人齐了，大家直起身等待大门关闭。不料乔乔鼻尖又耸，不顾孟孟的反对，重新叼上广告板，冲出大门，拦住了门外经过的数个韩国女留学生。

小店街毗临南京大学留学生宿舍，这里韩国女留学生从不稀奇。稀奇的是，人们总能一眼就将她们分辨出来。

韩国女子也像一切人类，长有一对美丽的眼睛，只奇怪她们的眼睛并非为了寻找世间的美而生。小店街上的韩国女留学生，不分来历背景，燕瘦环肥，统统摒弃自然母亲赐予她们的天然风姿，只向同一种美伏首：商人广告狂轰滥炸之下的大一统容貌。这种标准的商人美要求女性戴上面具，皮肤像死尸一样惨白。至于嘴唇也一定要像恐怖片中的死尸鲜艳的红。据说如此浓妆会显得精神百倍。只是“精神百倍”这种东西如果发现在死尸脸上。。。总之，喊出**“古来万事贵天生”**的李白定不会欣赏她们。

孟孟狗等的不耐，坐到大门门线上，放下口中挣扎不休，鬼叫连连的小花豹，用一只爪子拍牢，再汪汪催促。然而，招揽顾客是乔乔唯一敢于违抗孟孟的时刻。

孟孟无奈，又见猫娃儿个个抓耳挠腮，知道时间大了，于是再次清声发令，驱走了规矩。轰的一声，树倒猢狲散，几只猫儿化身橙色、青色、白色的闪电，在小小门厅左突右蹙。剩下的打呵欠、磨爪爪、敲脑袋、闻屁股、捉尾巴不一而足。赵思琪也学里娓，蹲下来，与小猫咪一一招呼，爱抚。

// 3/8 
抚摸小猫，心神宁定，一切都变得似水晶般清澈透明。门外鸟儿的鸣唱，囧窗间泥土青草的芬芳纤毫可辨。一阵又一阵时而兴奋激动时而低昂压抑的声浪传来，隐隐可知是外国话。

赵思琪然而脸红，从那些外国女人的表现上看，自己刚才也多半失态的不行。“好恶心，这些外国女人，一点不矜持，没见过世面，不就是狗叼广告牌嘛。。。鬼喊鬼叫的，像做那。。。那什么一样，呸！”批评完韩国人，赵思琪心下稍愈。又见乔乔伸出爪子，留学生嗷嗷的上去握，“哼，那狗爪子不知道踩过多少泥，多少痰，扒过多少屎尿，你们还真不讲究，对了，我好像也。。。”

此时白葭里娓又侧过来，不无羡慕地道，“这对狗是王可可家的，从小孟姐姐训练出来，有两个本事。一是搜寻流浪猫狗弃养的幼崽，将之带大。狗妈妈教出的猫咪也像狗狗一样听话。二是招徕顾客，王可可家两爿饭店靠这两位天天爆满，翻台几趟呢，小店街上就数她家首富。”

事实上，这对狗，公狗乔乔母狗孟孟是王可可的新婚礼物。

新婚的时候，王可可的丈夫见她眉宇间只有强装出来的喜悦，思来想去，忽然记起她初来小店街时的事情。

那一日深夜，还不适应机器人生活的服务员王可可披着寒冷的清光返回拥有八九个舍友的集体宿舍。此时的漫天星光只愿意照见她心中酸楚无限。经过垃圾箱时，意外看到一团灰黑色的肉块蠕动，定睛细看，原来是只狗仔，一只眼流脓，身上随处斑秃疤痕。

很多年后，王可可每次回忆都认定这是被人用烟头一个又一个缓缓烫出的。世界上最贫穷的人，体验过极度艰难的人类常常有最大的爱心，王可可只犹豫了三秒，毅然地将小狗带回。

花光了预支的薪水，小狗不旦活了下来，眼睛也好了，毛光光皮实实，十分活泼可爱，最意外的是，他竟然是只纯白的狗子。

又一日，王可可又一次工作到深夜，宿友忘了关门，小狗溜出来找妈妈。等发现时，他已变成路中央冰冷僵硬的尸体。

王可可崩溃了，扶着尸体，三天三夜未下床。最后还多亏了孟任，成立起“王可可帮助小组。”小组的头一件事——孟任自任组内的唯一领导小组长。然后小组长发令，动员素来与王可可亲爱的女服务员轮班日夜陪伴，陪她说话，陪她家务，逼她工作，让她没有任何时间独处思考悲哀。如此戚戚哀哀半年，她才恢复常态。

新婚的丈夫想起此事，决定送两只纯白的狗给妻子。所以花了一万多托朋友购买。是的，在中国，花钱最快的办法永远是托朋友代购。这朋友如此可靠，真的送来一对纯白无一根杂毛的小狗，绝对不是市场上常见骗新手的染色病狗。

王可可倒不在乎狗的品种 ，如她丈夫所料，爱死了这一对。想起孟任，于是给其中的母狗取名孟孟，又抱着公狗半天，不避任何人的目光，命名为乔乔。

然而小饭店的老板娘注定没有每日溜狗的闲暇。

// 3/9
所以几年来这对狗每日上午随王可可夫妇出门，自行跑到孟任处，再领着一队他俩带大的小猫到小店街荒弃的后山玩，日中返回，吃肉梳洗睡觉，下午再出门四处招揽顾客。到四、五点时，王可可家的饭店就可以爆满。两只狗于是卸下职责，趴在饭店外的木架上对着小店街望呆，大嚼王可可买来的进口带骨牛肉。

为家庭努力工作，得到进口牛肉的回报，这一切看上去完美。只可惜不久前，有些外国留学生过来拍了视频传到youtube上，大部分观众哈哈一乐，可总有正义感特强，习惯告奸的正义人士传言：广告牌是用钉子钉在狗嘴上的。

外国人里总有一部分被伟大的基督精神感召，他们一生不做任何事情，除了证明自己比别人圣洁。所以有几个在宁的外国人，突然成为了世上顶顶的爱狗人士，专程跑来小店街。等他们发现任何正常智力的人类都可以推断出的事实：广告牌并非钉在狗的牙床之上，他们娴熟地切换了抗议姿势，转而举着牌子在饭店门口静坐，牌子上还写有神奇的外国大字：**Work or Wok?**
// 这一段源于真实事件

可怜小店街上民众教育程度太低，竟无法领会外国大爷精妙无双的Pun。孟任苦苦翻烂手边的英文字典也不得要领，只好请教和曦。和曦看了，哈哈大笑，愉快地吊起了书袋，“Wok是粤语的镬，就是锅子啦，啊，这你也知道？广东人跑到美国开饭店，早年常常按粤语将镬拼成英文写在招牌上。那个结尾的K想来就是粤语表现入声的舌塞音，同样的还有白菜bok choy。这些都不是正经的英语，所以很多字典不收。但美国人只要看到Wok就知道是中餐馆，所以现在墨西哥人开中餐也会写上这个Wok。真正的中国人为了与他们区别，反而不再用了。”见孟任的眼睛已经晕迷，更乐，“说起来那外国佬挺有才，意思是这些狗如不**工作**就会给炖到**锅**里去。骂王可可逼狗劳作，顺便骂中国人吃狗肉。”

// 3/12
谁都知道孟任最敬畏外国人，听了和曦的解释，倒想劝王可可。只是王可可已非吴下阿蒙，像所有无辜单纯的人遭遇诬陷时一样，她火冒三丈，指着抗议者一顿骂，说她最爱狗，一辈子从未起过，哪怕一次吃狗肉的念头。难道有人吃狗就代表所有中国人都吃狗肉？中国人吃狗，你跑我家抗议，美国人吃牛肉，你怎么不跑白宫抗议？越骂越气，当即指挥两条狗出去咬人。

一阵鸡飞狗跳之后，两狗欢乐地舔拭爪子，毫不内疚地品尝趾间的血液。天哪！多么无知且狼心狗肺的畜生，这些血液属于把全部身心血肉都为狗狗着想的犬中圣马丁、玻利瓦尔啊！

// 3/16
进了二门，赵思琪倒吸一口凉气，“好宽敞。”在外面看不出，进来方知这家咖啡馆以回字型设计，几乎占据了整个院落
//不知怎么描写，这牵涉到开头对这里的印象。
// 旧房子和玻璃新的阳光房融为一体
// 违建
“来了，来了！”一群女孩子笑嘻嘻跑出来，有的牵狗，有的抓猫，顺便扭头与白葭里娓打招呼，更有两位笑着说，“直接把客人领上去吧，孟姐姐一会功夫催问几遍了。”

于是又来到二楼，穿过架在半空长长的木甬道。一时间，阳光搅起树影，挥洒陪伴她们。赵思琪伸出小手去捉，暖风从她指间蜿蜒游走，只余下醺醺的二人。

于是进了东北的角屋。靠门的地方，横七竖八躺着八九张沙发，符合最近流行灰冷色调的“北欧风”。又是一群女孩子或坐或卧，有的看书翻杂志，有的吃零食，有些对着小镜子补妆，更多的捧着手机消磨。

沙发区后，靠近北窗，有一男一女，也不从面前的凳子，站在那里指手划脚，动了意气。这两个身前对着张木桌，也是现在流行的时尚，漆成白橡木色。桌子后坐着个小姑娘，满脸的不耐烦，一看就不是个正经的女姑娘。
// 少服饰

“哎哟，你们两位还在争哪！”白葭里娓不客气地打断，笑道，“我下去的时候是你们二位，谁想到回来还是你们二位。李梅姐你也是老前辈了，怎么还不知道每天多少起人来找孟姐姐？照你们这样争下去，孟姐姐不要吃饭啦！”

男子闻言回头，赵思琪这才发现他深目高眉，不似中原人。只见他无奈地搔头，“不怪我，是园长太顽固，也不懂我们的民族习惯，明明从小学到大学都设有回民餐厅，她的幼儿园倒敢违抗国家政策，不收我的孩子。”

三十多岁的女子听了，越发不忿，不经意间高了音调，“我们违反了什么国家政策？！上次和你一起去宗教局，你也亲耳听到了，宗教局的领导说私立幼儿园有权自行录取，也没规定一定要有回民餐厅。里娓，害得孟姐姐吃不上饭是我的不对，但道理总要讲清楚。你儿子完全可以送来我们园，但吃饭不能特殊，别人说什么你家娃也得吃什么。并没有不收你的孩子，你自己不把他送来，专和我歪缠有什么用！”

说话的女子叫李梅，呆、笨、认死理，早先在小店街做服务员，所以很早就跟着孟任鬼混。

// 3/17
后来她在的店铺倒闭，像每天路边大多数小店一样。经同乡介绍，去了家私立幼儿园打杂，就此别离了小店街。好容易逃离魔窑，冥顽不灵的她仍把孟任平日的胡言乱语当成真理。想起孟任成天挂在嘴边当招牌的**学**与**日新**，也硬着头皮学起了幼儿教育。两年之后，居然混到了幼教资格证，转成了正经的**执证**教师。

谁都知道，中国人最舍得在孩子身上花钱。她的幼儿园赶上了城市化的浪潮，新近又弄来一笔巨额投资，所以像任何企业一样决心大大扩张。十家新建的幼儿园就有一家在小店街，集团还专门任命李梅出任园长，自然是希望和小店街大头头孟任搞好关系，至少不开罪她。

然而李梅一切都好，就是缺乏商人的灵活/油滑。她左手一本幼儿园规章制度，右手一本《幼儿教育》，做任何事情，都要先以查黄历请菩萨式的虔诚在书中寻找依据。别说与书上写的有一个字的差别，就算差一个标点符号，她也必然不行。与她龃龉的男子是小店街上新疆餐厅新聘来的青海大厨，小娃儿长到可以送幼儿园的年龄，本想着就此可以轻松一半，哪知一头撞上李梅的死脑筋，生疼。

已经很不耐烦的孟任，抓住这个空隙，对二人扬唇，“朕也听了半天了。”装出一付剧烈思考、脑海冒泡的模样，良久，“大厨也不足，李梅也过了，都有错。”

见二人呆呆凝望自己，孟任心底得意，得意成抓耳挠腮的猴子王，“先说你，宗教局的人也说，无论小学大学，上学的问题都可以为你出面，就是幼儿园没办法，可见李梅他们没有违反政策嘛。”

又指李梅，“你的死脑筋又犯了，比牛还犟。大厨又不要你专门为他家孩子开餐厅，他自己每天送饭，你为何就不肯行个方便呢？”

李梅急了，“不是不肯行个方便。”把右手的《幼儿教育》摊开，哗哗翻到一页，“孟姐姐请看，这里写着的，写着的！‘幼儿在园中必须按规定吃园餐，这是他们人生第一次参加集体活动，可以潜移默化地培养他们尊重社会、学校以及公众的行为规范的意识，并且纠正由于家长溺爱形成的挑食的坏习惯和唯我独尊的小皇帝、小公主思想。’我们园的规章制度也禁止家长送饭，我马上翻给你看。”
// 有意把引文写成啰嗦的长句。

“够了够了，”孟任摆摆小手，自认很潇洒，“朕怕你根本不懂什么叫民族宗教吧。”

李梅怔住，出身寒鄙的她见过的第一位回族人就是眼前的大厨，还是从他的口中第一次听到**伊斯兰法**四个字。等搞清楚这四字怎么写，她不免在背后偷偷对着先知发出许多亵渎的啧啧声。
//塙有如此漏人，从小到大不知道民族宗教的。

// 3/18 得知李敖去世，想有点感伤又不知在何处，唉

“这样说吧，信道教的不吃狗肉，并非他们挑食，或者怀疑幼儿园的菜肉不洁，来源不安全，而是信仰，你懂了吧？”

没有，完全没有，李梅并不认识任何道士，更没听说道士不能吃狗肉的，所以看上去更加呆头了。

“那你总有亲戚信佛吧？平时吃素斋的。”

这个。。。李梅勉强懂了，她的外婆在生命的最后岁月皈依了佛教，丝毫荦腥不沾。外人看着都觉得不忍，家人更是忧心忡忡。所以，，，李梅从小红旗下长大的唯物主义少女又把食物禁忌理解成**封建迷信**，害人不浅！

呃，没想到讲道理起了反作用，孟任好气好笑，只能求诸擅长的暴力。把电脑屏转动90度，一手揪住李梅的脑袋按桌上，一手在亚马逊图书信息页上指指点点，先吹嘘自己，“看看，像朕这般伟大的君王也懂得学习日新，‘苟日新，日日新，又日新’。哪想到你这小学生倒不学习的，天天捧着十几年前出版的第三版旧书当宝贝，你看看这里，这书去年已经出到第六版，第六版序言有一句，‘除了上述变化，本次修订还添加了民族宗教和少儿心理学内容，这符合社会主义初级阶段生产力与生产关系辩证统一的。。。吧啦吧啦，哼哼哈哈，阿弥托佛嘛咪嘛咪哄，’见鬼，全是咒语？总之，大意你反正了解了，记住，回去第一次事就是去买一本第六版更新一下你的死脑筋，记住了没？”为了帮助李梅回忆，孟任又咚咚咚在她脑壳上凿了三个暴栗，才放手。

李梅早被孟任锤惯，逆来顺受，这时只好委委屈屈先答应下来，但立刻提出了新问题，如果别的家长得知，哪个孩子没有特殊情况，人人要给孩子送饭，那该如何应对？

谁料这问题竟惹了一位未来的英雌排空出世。站在白葭里娓身畔，红衣少女赵思琪早已不耐，天哪，这都什么人啊！不过一件芝麻绿豆大的小事，这伙人唧唧歪歪、唧唧歪歪、唧唧歪歪个不停！冲动之下，脱口而出，“换个说法不就好了？不然还说成开了个专供穆斯林的餐厅，别提家长送饭，全推到宗教局身上，就说他们规定必须要有的。给所有家长两个选项，要么吃园餐，要么吃清真饭。到时候不管几个人，都让大厨按人头送来好了。”
// 排空出世那里还要修饰。赵思琪固然是未来英雌，但她在本书里只零散出现，并非主要人物，如白葭里娓。

李梅听了，缓缓点头琢磨，不提家长送饭，其他家长也不会想到送，加上幼儿园的孩子们也没有奇奇怪怪的信仰，比如佛教，不怕有人乘机要幼儿园再添个素菜馆子，如此看来，这办法也许真的可行？

// 3/19 昨天未见的，今日见了，不见李生久，佯狂真可哀

众人观察孟任的神色，孟任正色道，“又何必骗人？满腹心事，伪饰出来的言辞真以为能欺瞒世人？小店街之人虽笨，可也不都是傻子！这样吧，李梅你明天再来一趟，朕为你写张告示，把事情本末由来一一详明，你贴在大门上，晓谕众生。还有不理解的，让他来找朕。还有，你书上只提到尚同，只想到集体意识，可人生而不同，已不仅仅是宗教；有些孩子体质特殊，吃点豆油都过敏，你们也逼着非要吃定餐？”挥挥手，遣走了李梅。

竟见未被采纳，对于只有十六岁的赵思琪来说本是寻常事，毕竟年龄不到，就像还未长出鬃毛的公狮子，没有哪个母狮会将他放在心上。然而这一次她着实羞红了脸，因为无知的围观群众听了眼前和自己一般大的小女孩胡说，个个露出信服的表情，仿佛听到的是黄钟大吕，金声而玉振。

“啊呸，好恶心。被我抢先了，这小毛丫头才特意换一种说法出风头，保持她在众人眼中的地位。如果一开始我用她的说法，她一定换我的，为了不同而不同，哼哼，就有这种人。”

大厨见事情解决，喜上眉梢，正待告辞，却低估了孟任。“你也知道，李梅收你家娃是出于善意，许多人劝李梅，为你说话也是一份善意。你的孩子现在信仰你们的圣教，因他生来就是你的孩子。等他长成，如果有别的选择，别的信仰，也请你尊重，最少不干涉，看在今日这许许多多在场人士善意的份上。”

大厨呆了，全然想不到还有这么一出，嗫嚅半天，像坏了的闹钟，身子乱颤，戏味十足就是发不出一丝声响。

有个女孩见孟任要打发他，忙窜出来，咬着耳朵密报。愤怒的火星迸发，炸雷在寥廓的屋㝢内来回激荡，

“什么？打孩子？？！！你别走，你给朕讲清楚，为什么事打孩子？”

“小孩子不听话就该打？你还占理了？你那么占理，为什么把他拖到后面的车棚偷偷打？不敢在路边光明正大的‘教育’？要不是你下手太狠，车棚那边的声音也不会给姑娘们听到！”

“下次小孩子不听话，你把他送这里。你不会教育，朕这里最多有耐心的阿姨。你再敢打孩子，别的朕做不到，在小店街上你只怕混不下去！”

见大厨服软，孟任绯颜略霁，“对了，你老婆怎么回事？每天在你店里打杂、炒菜、收银，托人几次，就是不肯登朕的大门？是看不起这里的女孩子还是想学离群索居的商？商也悔于失群，她难道还贤于商？你记得带话，不管疲倦还是XX，都可以来这里休憩，嬉游。就算龙生九种，个个有别。这里人多，必有她能合得来的，总好过天天守着你。贵教的声望被一些极端份子拖累，你们又不出来交际，在旁人眼里，难免觉得神神秘秘，甚至鬼鬼祟祟。就算为了贵教，她也应该来这边教育出身于不毛之地、无知愚昧，连伊斯兰三个字都没听说过的女孩子。她不肯来，莫非是对贵教信心不坚的缘故？”

大厨失魂落魄地走了，得一而失二，总算见识到小店街统治者真正的颜色。

// 3/21 胡适一系学者还是太墨家了，这也许是李敖喜欢中共的原因。

// 3/22 
上午的事情终于完结，见无人瞩目，孟任偷偷伸了个长长懒腰。又想起居然有人胆敢抢在自己前头说话，差点扫了威风，忍不住要把那个捣蛋鬼滴溜出来。

通了激光的目光一旋，立即锁定目标：缩在角落，满肚皮不适，怀疑自己为何生在此处的赵思琪。

“你终于来啦！”噌，孟任窜出，两只爪子啪地握住赵思琪的小手，热情如火，将她拖到屋隅的小沙发上坐了。小沙发四周摆满奇木修萝、博物架作屏障，是个闹中密谈的好地方。

本感到冷落陌生而手足无措的赵思琪被这突如其来的热情打倒，本能地挣扎，却被大擒拿手死死按住。

“你们是怎么招待客人的？看茶，点心！”两个姑娘笑着得令而去。须臾，捧回来热腾腾的焦糖玛奇朵和喷喷香大块头南瓜豆腐慕丝奶酪蛋糕。

赵思琪眼看着会大擒拿手的老师傅使出失传已久的十九式三十七手“狮子搏兔”擒住了一块蛋糕大嚼，渐渐鼓足勇气，怯生生、傻乎乎地微声问道，“我们认识吗？对不起，我。。。我记性不好。。。”

// 3/23
“认识！认识！当然认识！四亿八千万贤劫之前，兜帅天须弥宫药师殿，朕登法烬台为大罗金仙讲解混元道果，你于众仙佛中最先领悟，欣然向朕躬行礼，暗递秋波。”

“再经恒河沙数之无量空劫之后，于昆仑界玄圃閬風山上的穷桑之野，才能与你再次相逢，朕于是为你拈花，对你破颜微笑。之后朕还会为你歌唱，

‘两只老虎，两只老虎，跑滴快，跑滴快，一只没有耳朵，一只没有尾巴。。。’”

@$@#%$^$#!@#^%$!

见赵思琪已然精神错乱，孟任终于感到了一丝丝羞愧，单手摩挲后脑壳枕骨，打着哈哈，“戏言，戏言尔。”

倏地，又突然将脸孔凑到赵思琪鼻梁一寸处，神秘兮兮地眨着左眼，仿佛心照不宣，道，“虽然今日初见，但观这位义士形貌，朕自然了解你的来意。”

哦，赵思琪想起来意，倒觉不好意思，明明是来求人的，哪经得起这番盛情。

见她不语，孟任当成默认，更是高兴。扬起一手，嗷嗷怪叫，“来人！快去买大公鸡，要最雄壮的！雪刀一挥，鸡头咕噜噜乱滚，血溅三丈！对了，还缺一位见证，难得如此高兴，朕就赏太上老君一个天大的面子，差他下界见证盟约！咦，瞧你面露不满，莫非嫌弃李耳老贼不成？那就西王母吧。不妥不妥！西王母还欠朕三个桃子呢，天大的怨毒，怎可让他乘机化解？”

“求求你，求求你了。”赵思琪气若游丝，哭了，“告诉我到底怎么回事，别。。。别买大公鸡了。”

不买大公鸡？孟任皱皱眉头，只办正事的话，乐趣就没有了，看着无头公鸡乱蹦。。。恶狠狠将赵思琪右腕寸关朝上翻，露出尖锐长牙，“没有公鸡的话，朕的血又不能多出，只好委屈你啦。”
// 孟任要杀大公鸡小说之言，别当真了

“别呀，我不是来盟约的。你理解错啦！”

// 3/25
“没错！朕一贯善解人意，你就是来参加‘承天景命XXXXXXX’，如今你这样的义士已然很少了。”

“不对，不对！求求你，饶了我吧。我是来领养猫咪的，你那个鬼盟约听都没听过。啊！你的盟约一点也不鬼，只是我。。。”

“是，你就是！”孟任暴跳如雷，“朕说你是，你就是，不是也是！你全家都是！莫非你胆敢怀疑朕的占卜？？？”

赵思琪吓倒摊缩在沙发一角，考虑是否先答应眼前的暴力问题少女。忽想起一物，连忙将手上的救命稻草摊开，指着其中的一篇报导，“这杂志上说，你们是南京最有名的猫咪咖啡馆，有猫咪给广大爱心市民领养，你们的口号是‘让人人都有猫咪！’看！这张合影里那个美丽温柔的少女不就是你嘛？我先以为是服务员，谁想到来了之后才知道世界上竟有这么年轻有为还美丽的店主。”

哇咔咔，听到**最有名****年轻有为****美丽温柔**，孟任汪汪大笑起来。边上的赵思琪却十二万分的后悔。

中午午休，吃完饭无聊，赵思琪从班上的图书角随意拿起一本天知道猴年马月出版的杂志乱翻，踫巧读到孟任的故事，一贯冲动，思想追不上脚步的她立刻出发过来品尝后悔的苦涩。

很多人几十年如一日做着重要艰辛的工作，做出了杰出的贡献，耗尽无数心血，却默默无闻。而孟任因为长年做视频，结识了不少业内人，加上繁娃在媒体上的关系，猫咪咖啡馆甫一开张，就有记者前来采访，并免费为她大肆吹捧。什么正经的工作还未做，她在南京小动物援助界的声势已远远压过那些辛苦二十年，变卖家产也要救流浪猫狗的**奇人**。思之令人扼腕，然而世上的事本来如此，本应如此，又何足怪哉？

// 3/26 
“这只是刚开业时的报导，”孟任神气得紧，“成绩属于过去，努力才有未来，哇哈哈，朕怕你的消息已经过了保质期。如今猫咪咖啡馆一年可以送出三百只猫咪，三百对孤独的灵魂因此得到慰藉。我们的口号‘让人人都有猫咪！’马上就可以实现了！”数学不及格的帝王小手一挥，划破天际。
// 漏了和盖茨口号对比的一句

于是美滋滋地跑去办公桌捡出一卷纸，又在耳滨插上一支笔，装出小俏皮的模样，犇了回来。

欣欣然笑对赵思琪，刚欲开口，不甘心的眼眸又忍不住翻上来，“真的只是来领养猫咪的？加入盟约很好玩滴，‘凡我盟之人，既盟之日，朝夕虔心诅咒贱婢繁好一百次，咒她屁股生脓疮，疼得死去活来，活蹦乱跳，平地翻跟头打滚。’哈哈哈，好好玩，有没有？你要是怕那贱婢的淫威，以养猫为借口试探，就眨眨左眼，朕自有万全安排。”

见赵思琪不接话，眼皮也不敢眨，打破了吉尼斯世界记录，孟任只好无声叹息，正色道，“领养猫咪需要填些表格，好让我们了解你的基本情况。不是说你，别多心哦，有些人不适合养猫，在网上看到可爱猫猫视频，一时冲动，就养了。结果热情一过，发现还需要承担许许多多责任，既花钱还麻烦，猫咪也不是他想像和需要中的奴才，就偷偷把猫遗弃。让他们自生自。。。”喘着粗气，“**彼哉彼哉！**”

赵思琪刚填完姓名时，孟任还很高兴，“思琪，思琪。”反复咀嚼，“这名字冥冥之中，和朕多少有些联系。”

等她填上十六岁时，孟任大惊小怪，“才十六岁？”忍不住伸手搬她的脸孔，贴上去细细看了，捏捏耳朵，还趴到头壳上，用力嗅了几下髪缝，“原来十六岁是这种味道？朕老是分不大清人类的年龄呢。”

// 3/27 
然而，十六岁？孟任转成严肃，“十六岁还没独立吧。”

赵思琪一凛，这才想起家长，满腔的热情于是缓缓冻结。

“**妈妈都不喜欢毛毛的东西！**”孟任抱着臂笃定道。

“对，对。”赵思琪难为情地低下头。她与母亲的关系谈不上好，至少没有任何把握说服养猫。“她总是这样。永远把我当小孩子看。说我成天不正经，不好好读书，不会讨老师的喜欢，长大了也是个废物。不如不读书，早点打工，还能省钱。再学会钓男人。。。”

“世界上竟然有这样说女儿的妈妈。”赵思琪自怨自艾，心中酸楚，不如为何，骤然向眼前初见的少女倾诉。又准备填下一项，“是否养过任何宠物？”，还在沉吟，突然，哗啦一声，一只手从旁插走卷子。

“行啦，你的情况朕已知道。”屁股离座，尾巴甩都不甩赵思琪，回到桌前，把她晾在一边。又取出修正液，当着所有人的事将赵思琪填过的重新涂白，想来可以节约给下一位领养者使用。

赵思琪全身僵硬，看着这一切，她的灵魂已脱离备受污辱的躯体，周围的一切已不对她影响。才知道不但学习不行，连收养猫咪她也没有资格。

周围的女孩子也有不少露出迷惑痛苦不忍的表情，一时若大的屋舍只余下细密参差的呼吸。

午饭的到来打破了现场的尴尬。孟任打开盒饭盖子，呱呱大嚼，又含着米粒转头吩咐里娓，“带客人参观一下，容朕吃午饭先。”

望着里娓二人步出长门，孟任轻蔑一哼，头脑发热的小姑娘罢了，看了新闻逃课过来，还想领养猫咪？猫咪再贱，也不是生来供你玩到死的！

// 3/28
孟任吃着饭，忽听楼下一片嘈杂，抬眼。两个女孩飞也似地去了，又喘着气回来，“孟姐姐，门口来了四五个街坊，非要马上见你。守门的姐姐说了，今日听讼已毕，请他们后日上午再来。他们不肯，说十万火急，等不得。但这伙人谁都不认识，应该也不是小店街的邻居。”

等这五位男男女女站到孟任身前，众人才得知他们原是小店街隔壁大店街上的住户。也是走投无路，病急乱投医才来此处求见。

原来自古以来，大店街上就有一家街道办中学，就叫“大店街中学”，奇差。以前南京的父母教育孩子常常吼叫“让你不学好！再不学好以后只能上大店街中学！”

这几年国家学美国改制，教育私有化。连大店街中学也迎面撞上了撒金的春梦，改来改去，不知为何与南京师范大学扯上了关系，旧牌子一去，摇身一变成了“南京师范大学第二附属中学”“加拿大留学预科学校”。

这一年暑假开始，为了符合**加拿大**这一响亮洋招牌，好多多创收，，，好多多育人，学校决定将校舍彻底翻新。

大规模的装修难免带来噪音，在人口密度极大的大店街相当于双倍噪音，也许可以发明一个新词“重噪”来形容这种局面。白天时断时续叮叮咣咣，打桩机似的在工地上和居民的脑海中锤炼，除了学生不得不作鸟兽散，想办法逃离，其他人只好用电视机、音响对抗。虽有不满，但考虑到总不能不允许别人装修，默默忍耐。

忍着忍着，渐渐不好了。本来只在工作日白天施工，不移时延长到黎明、午休、黄昏。好吧，继续忍。渐渐的，更加不好了，连双休日，工地也从早到晚咣当不止。有些人忍不了，去找工地，负责人笑着把人送出，大骂工地保安一场，开除了他，换了新人。最近一个星期更加不好了，白天时间不减，夜晚也哐哴哐哴起来，从十一点开始，往往要到凌晨五点，装卸脚手架，浇注搅拌混凝土，偷运建筑垃圾，无所不为。

大店街的居民也混蛋，不理解南京师范大学校领导的善意。他们没有把握机会，没有利用白天黑夜时时萦绕的锤子敲击声，锻打出纯净高尚的情操，深湛的学术思想，反而因为脑子像被敲出来，患上了神经衰弱、失眠，而已经神经衰弱者不免往精神分裂症方向发展。

生无可恋的居民再找工地，可负责人人间蒸发，新来保安一问三不知，什么都不晓得，却晓得关紧厚重铁门。

居民无奈，又求助于报社各大新闻媒体，得到了答复，和康熙皇帝一样的三个字“知道了”。

居民又打投诉电话，城管的，城建的，环保的，市政的，市长的，这些部门也一齐成了康熙皇上。

居民又于今日早上集结，准备去南师大找校长呈情。结果只见到严阵以待的保安，众人猜想用来联络的网上信息小组已被渗透。与保安对峙时，工程负责人在警察簇拥下现身，高举着尚温的“夜间施工许可证”展示。得意之余，不免多嘴，指责居民“如果全国都像你们一样，中国的基础建设就会倒退十年，街上也不会这么多人，如此繁荣！生在福中不知福！”

看着合法吵闹许可证，大部分人只好散去。然而总有自甘堕落、不识大体、不爱国的人类，四五个落后份子，老而不死的老贼凑到一起，眼泪汪汪。一周没睡好，令他们精神恍惚，以至错乱，加上老眼昏花，误以为最近小店街上出了新气象，于是哆嗦蹒跚着向那里进发。

俗话说的好，苍蝇不叮无缝的蛋，落后份子去找孟任，真可谓臭味相投了。

// 3/31
孟任去看居民们拍的夜间施工视频。五人到了这时又忐忑不安，不知道眼前的少女会否帮忙？就算愿意，她又能做到何种程度？

“反了，反了！”孟任拍了桌子，与南京师范大学有仇的她在地上乱蹦，“朕早知道南京稀饭大学混账！谁想他们竟比朕预料的更混蛋！”
// 预期时间要不要加上？实质上托了一年多呢。。。。

“小松鼠！你来！朕命你不管用什么方法，今天下午六点前，把稀饭大学的校长，副校长统统带来这里和大店街的父老开会，讨论解决办法。除非那些校长的老婆孩子正在断气，不准放过一个！反了他们了！一个屁大点的学校就敢这么欺压父老，可想而知。。。！什么，项目负责人？他是什么东西？也配过来？”

“让别人牺牲说的如此理直气壮？稀饭大学的校长如果每天在工地上办公，朕就不问此事！”

靠近长门的黄沙发东头坐着个郁金香似的少女，手中正拿着卷诗集。看到佳绝处，忍不住启颜微笑。

听到孟任的严令，小松鼠把本来枕在那少女大腿面上的脑袋抬起，不确定的四下张望。终于如梦初醒，赶紧趿了鞋子，窜到孟任跟前。

“阎王好见，小鬼难缠。”小鬼本是阎王豢养来隔离群众的。然而孟任说了“不管用什么办法”，又见地板已经跳通。小松鼠明白眼前的君王动了火气。校长们长年宦游，见惯风浪，只要被“请”来，自然不用烦神，但。。。

“你是说，这些大店街的父老反而会出问题？”孟任疑惑地反问。

“陛下。”小松鼠斟酌着，“大店街不像我们这里，是沐浴在现代法治文明下的先进社区。他们没有君长，没有乡贤，没有选举，没有乡约董事，没有宗族，连绅士也无。法律的万丈光芒确保他们无须，也确实不认识紧靠门的邻居，更遑论他人。所以眼前的父老代表不了大店街。就算这里的几人与南师达成协议，其他人未必接受。比如大店街上的五金店、门窗店、小食铺还指着学校的生意，越多越好，越密越好。又有些居民恨不得永不让中学装修，只要吵到他们；有些上夜班，更希望白天停工，诸如此类。群众的意见变化多端，不可预测，也无止境，如天上的白云，时而XX，时而苍狗。说服十名绅士也易于一个暴。。。我们管了此事，只怕两头不落，反而卷入他们的内部争纷。”

“这样啊。”孟任灰灰地木然滑落椅中。许久开口，明显失了锐利，“既如此，朕也无从帮他们多争利益。一切严格按法律条文规定的装修时段办；再叫校长带点小礼物上门慰问那十几家最受影响的。其实校长们早点上门，又怎么会闹得如此不可开交？对了，别忘了顺便带一只大公鸡，好让他们盟誓。”

哈？原来还是要看杀大公鸡呀！边上的一个女孩笑着上来款款相劝，“孟姐姐老让我们读书，昨天看到诗里有一句‘君子屡盟，乱是用长。’可见不诚心的盟约，不管歃血釁鼓，还是刻盘勒石，都不中用。还听人说，春秋贵胥誓，不如就让他们胥誓吧，皇天后土在上，大公鸡可以免了。”

见孟任笑着颔首，众人连连称善。

// 4/2 
这有什么好看的？白葭里娓很奇怪，拉拉赵思琪的衣袂，后者才恋恋不舍地离开。

“这些事很常见，只要放告的日子，小店街上还有附近的居民没完没了的跑来找孟姐姐评理，都是鸡毛蒜皮的小事，可他们才不管孟姐姐有多忙，只顾着胡扯。”

又忍不住安慰赵思琪，“刚才的事别往心里去。孟姐姐很喜欢你，不然不会对你如此严厉。想领养猫咪，我一会儿帮你私下去说。”

“好咧！”赵思琪愉悦地回答，快乐的像小小云雀直冲霄汉。

白葭里娓见赵思琪抛却刚刚的忧郁，也为她欣喜，虽然觉得情绪转变的快了点，并未生疑，尤其没想到她的转变只缘于趴在窗台，偷看孟任处理事务的片刻。

“这边是动物医院。我们有很厉害的喵医生呢。”

// 4/3 玳瑁猫醜醜失踪48小时，甚不安。也许她和她妈妈都有流荡基因，也许她还会回来，也许

所谓的喵医生就是两名从前雷渊宫的宫女，最早在猛氏馆为冥后照顾她心爱的虎群，后来和人类私奔跑了，最近随着孟任回归，立青旗延揽旧部，又不知羞的乱跑了回来。

孟任看她俩还有些特长，花钱送到外面的宠物医院实习，补充落下三千年地球动物医学。因为两人轮流，平时总有一个留在咖啡馆里无证非法行医。

赵思琪透过玻璃门好奇地偷窥医院挂号处。位于二楼西北角上的医院看样子占据了三间房屋，大部分为毛玻璃阻挡，只余下赵思琪驻目的那间。

温暖又不失热情的配色，现代简约的登记台，台后照例挂着廉价的大幅猫咪写真，只不过这只猫咪热衷对着雪山打呵欠，啊，雪豹。

雪豹下方坐着一位三十多的女士，专注地看着手上大八开的专业书，并未留意门外。

照片左边贴着价目表，赵思琪没养过猫狗以及一切宠物，不知深浅。另一面墙挂了四幅画，用木框装裱。赵思琪不看则已，定睛细看，第一幅名曰“猫咪先天经络图”，右一幅“猫咪六脉神剑”，再右一幅“猫咪玉女心经”，最后“猫咪阴阳和合交欢大乐神通”。每画都细细标出穴道、经脉和真气运行方式。如果不是绘画技巧等同于幼儿园大班，也许真有人相信。

白葭里娓只好不无尴尬地表示，“孟姐姐喜欢开玩笑，人很幽默的。又爱看武侠小说，就画了这些当装饰，当然不是真正的秘笈啦。”

愚蠢的人类，整日面对墙上四幅大作，只将它们看成小儿涂鸦，却不知万世君王将她百万年来的绝学XXXX一一画入。有人问，既有神功，为何不正大光明地刊行于世，传播文明呢？愚蠢的人类！没听老子说“玄之又玄，众妙之门？”没听佛祖说“知见障”？所以佛祖要摆出神神叼叼的鬼样子，将正法眼藏，传给大伽叶，可见愈是神仙妙法愈要鬼鬼崇崇、鬼哭狼嚎、鬼使神差，才能满足普罗大众心理的期望。
// 太轻薄？
// 4/4 醜醜的弟弟猢狲今天看着似乎也没食欲的样子。

白葭里娓推门，为喵医生和赵思琪介绍。饶有兴哇看了一会儿志愿者给狗狗洗澡美容。又在喵医生的带领下参观了医院，途经手术室、诊疗室，最后进入住院部，探望不少留院观察的猫猫狗狗。

赵思琪走马观花，笑嘻嘻的与病号打招呼。有只小黄狗得了肠胃炎，经过一周住院，已经痊愈，即将出院，喵医生乘便打开笼子抱出来。

小狗经过这番劫难，精神还萎靡。低声呜鸣撒娇。喵医生安抚一会儿，又递给里娓。里娓笑着接过，抱着小犬乱亲，口中发出含糊不明的激动。

又看到赵思琪跃跃欲试，把狗给她。赵思琪于是也抱了狗一顿亲，又为它拍拍背，捋捋毛，小狗兴奋过度，一时困倦袭来就在她臂弯中沉睡了。

三人又走到隔壁病床/笼子。只见一只大大的肥猫头戴伊利沙白圈委屈地趴着。

“噢噢噢，好肥好可爱的英短蓝猫！看这大圆脸，好想捏！”赵思琪惊喜。

喵医生点头，证实了她的说法，“本地有名猫舍的繁育猫。祖宗三代都有血统证的英短。今天早上过来做绝育，退休。公猫简单，观察到晚上就可以出院了。漂亮到这种程度的英短我也是第一次见。”

“原来这就叫英短啊，我说怎么长得和常见的猫猫不一样呢。可为什么叫蓝猫，明明灰猫呀。”白葭里娓发问。

赵思琪并不知道白葭里娓是“小店街喂猫小组组长”，因此倒未奇怪，抢先回答，“平常垃圾桶里的都是国产土猫，全是杂种，哪能和外国纯种猫相比。纯种猫总是很特别的，有奇异的花纹毛色，富有异国情调。英国民族气质中承载着高贵、优雅和忧郁。他们的国粹猫就叫做英国短毛猫，简称英短。也像英国人的品格呢。它们有大大的脑袋，粗壮的脖子，宽厚的胸部和无比壮硕的身形。虽然体型巨大，但它们性格憨厚平静，粘人亲人，是最好的陪伴猫呢！”

喵医生补充，“学术上应该是灰色的，但在很多人眼里更接近蓝色。是由黑色素在淡化基因位点loc D变异影响下形成的。”

“从我们医院资料看，英短是第一流行的纯种猫，而蓝色又是英短里最流行的颜色。我们都喊它蓝胖子。”

“猫咪果然还是胖一点可爱。”白葭里娓蹲下去捏捏蓝胖子的两腮，精神委顿的猫猫娇声抗议了两下，露出生无可恋的表情，大家看了都笑，心中温暖起来。

白葭里娓于是平生第一次对纯种猫生出了好奇。喵医生拿出手机，找了一些以前住院的照片给二人看。然而喵医生只知道纯种猫常见的遗传病，其它不甚了了。

反而赵思琪懂得更多，能讲出每个猫种的性格特点、生活习性，完全没有辜负宠物猫舍几十年如一日努力传播“知识”所耗废的心血。

// 4/7 五天未见醜醜
白葭里娓对着一只银白虎斑小猫照片紧瞧。赵思琪从旁一见，忙道，“这是美短，美国的国猫。像美国这个民族，独立勇敢、开朗活泼、健实温柔，对外界事物充满了好奇心。听说它们是‘五月花’号第一批乘客，从那时起就守卫着美国人民，所以也是忠诚勤劳勇气的象征。从某种意义上说也是美国的开国之父。历史课上都学过的。

历史课上当然讲过五月花，赵思琪哪里胡编了？猫对于美国的建立，作用只怕不下于**founding fathers**。当然，当它们的数量太多，又乐意食毒而亡，除了死前的那一声哀鸣，不会发出其它响动，惹起勤劳勇敢的美国人民一丝一毫的不快。
// 自然有所指，美国人民杀猫可是使用过生物，化学等多种武器，除了核武器还未试过

里娓如闻仙乐，如痴如醉，频频点头，不由赞叹，“赵思琪，没想到你如此了解猫咪，一看就是爱猫之人。像你这样的爱心人士就是我们一直寻找，可以托付猫咪终生的领养人！”

自从升入现在的高中，父母就对赵思琪学业彻底死心。赵思琪和同学也选择放弃，懒得学。高中的老师更懒得教。为遣永日，赵思琪上课时必打开手机在网上闲逛。渐渐的，被互联网上的猫咪吸引。兴趣是最好的老师，经过半年的坚持不懈，她俨然成为宠物猫专家，甚至同学购买家猫也必先来找她咨询。这一切都很美好，天边唯一一片的乌云是——她没有钱。

“啊啊啊！这是暹罗猫，好可爱！”赵思琪看到另一张照片尖叫，“看这纤细修长体型和楔形头就知道是热带异国品种。它们是大洋洲暹罗国的国猫。以前只生活在皇宫和大型寺庙，是外人只能耳闻、不能目睹的贵族。它们也像暹罗国人一样，性格刚烈好动，机智灵活，探索欲特强，善解人意。是唯一一种可以牵出去溜大街的猫，因此也被称为猫中之狗。有人在网上黑它们，说暹罗嫉妒心最强，容不下另一只猫。其实不是的，嫉妒心强因为它们对主人忠心耿耿，感情深厚，需要主人不断爱抚关心，如果强制与主人分开，则可能抑郁而死。对了，它们在网上还有一个绰号，叫‘挖煤的’。”

“里娓姐请看。这只暹罗猫全身象牙白，只在面孔、耳朵和尾巴尖上显出棕黑色，我们行内的朋友称为海豹色，又叫特点色。是暹罗猫的特质。好像由什么什么基因控制，而这种基因和温度有关，皮肤温度高就是象牙白，温度低的区域如耳朵尾巴就转成巧古力色，越冷越深，直到纯黑。”

“我有一个同学养有暹罗。”只要赵思琪需要就有一个同学从地里长出来还带着一只暹罗和父母双亲，“她嫌猫猫掉毛多，每天打扫麻烦，就给猫猫剃短毛。我劝她，她还不信。谁知两个月后，她老爸从外地出差回来，一进门吓了一跳，我家的宝贝白猫哪去了，怎么一只黑猫迎上来，和我老亲热的？从白猫一转眼变成墨猫，就好像白从出门挖煤，回家成了黑人。所以它们才有了‘挖煤的’雅号。唉，她就是不肯听我的。。。”凭空长出来的同学的在天之灵听到这一声叹息难免流下懊悔的泪水。

里娓哈哈大笑，
// 4/9
突发奇想，“没想到外国的猫咪如此奇异。明年下半年我要陪和总出国，已经定下去美国三次，欧洲一次。本来我还有点怕，现在想到在美国街头就可以看到叫作美短的猫咪，这样讨喜的模样。英国的猫咪原来是英短，大头小胖子。所以说出国长见识真正一点不错。要是运气好，说不定捡到几只美短英短带回来！只不知那大洋洲的暹罗国在哪里，有机会也要去捡猫猫。”

“好主意！”赵思琪娇笑。喵医生和蔼又略带尴尬地陪着天真的里娓和纸上养猫的赵思琪微笑。
// 暗示够多了吧。

听到“和总”二字，忍不住向里娓祝贺。里娓害羞了，“唉，不过是运气好。我又没做过什么了不起的事情，也没学历，竟能被和总错爱，成了她的助理。又不能辜负和总的厚爱，也只好战战兢兢，用尽全力向前。只可惜时间越来越少，来这里越发不容易了。”

是的，上次捉猫，里娓给和曦留下了深刻印象。又一日，和曦想起，到明年夏初，自己目前的私人助理就将完成合同上的五年之期。和曦不是墨子的信徒，除了才能，用人一贯看重**亲、近、贵**，想着现在的助理为自己服务五年，尽心尽力，任带任怨，无论如何也要调剂个好缺给她。

那么谁来填补她的空缺呢？助理这职务太不起眼，很难聘到像样的人士，可这职务对和曦自身却又重要。好像鞋子，卑贱得天天踩在脚下和灰尘污秽亲吻。但如果不合脚，倒霉的一定是鞋子的主人。

想到这里，和曦有意无意向孟任探探口风。孟任闻弦歌而知雅意，上窜下跳，拍胸脯打包票，把里娓吹得天花乱坠，说她人品高标，性格淑均，言行稳重，才能特出，真正天下有、地上希、人间无。仿佛博浪坡缩头的张子房，隆中茅庐里趴着的诸葛孔明！仿佛巨闕太阿隐于匣中，一待清风，便可龙吟！

和曦吓得非轻，不敢用卑微的助理亵渎天下之英。孟任忙转舵，说里娓出身微末，长在泥涂。性本若芝兰，生于幽谷，不因为无人关注，就不吐出芬芳。只可惜天下荤荤，竟令幽兰也生出用世之志。是以她才情愿出仕，待价而沽，屈志折腰，事奉他人，哪怕再不起眼的职位，只要能正天下有道也必甘之若饴。
// 子曰：沽之哉？

和曦于是下了聘书，月俸一万，又替她报名南京最好的英语学习机构，让她在这一年里只做一件事，学好英语。

优厚的待遇加上无事需要操心反而令里娓胆颤心惊，避而不受。和曦更加喜欢她的忠直，特意找事给她。想起上次捉猫时见到的冻干不错，又找了相关领域的咨询公司，研究一番，觉得应该能在高端市场中占据一个位置（niche market)。于是找孟任一起注册了商标品牌，准备生产冻干宠物食品，不求赚钱，只希望增加上市公司的销售，顺便让里娓心安。

// 4/11
胡乱生产喂自家猫是一回事，食品上市（哪怕是饲料）就是另一回事。里娓接手后才了解其中的烦难，又不愿和曦多花钱，事事亲力亲为，查资料，跑政府，和各种牛鬼蛇神打交道，忙了快两个月，勉强搞清楚该如何办理。

所幸和曦不急，只是命她务必把英语学好，所以里娓一周三天在培训机构，一天在和曦公司实习，剩下的用来跑批文，偶尔无事才能过来小店街。

从宠物医院告辞出来，白葭里娓又带赵思琪参观二楼其余机构，什么反骗组，小贷组，隔离室。赵思琪莫名其妙，里娓也不多说。临了是一间小髪廊，几个姑娘坐在椅上，由着另几个姑娘在头上乱搅。这一切立刻吸引住赵思琪，里娓笑着邀请她进去，两人坐了一会儿，也修了修头面，方才满足而去。下到一楼大厅。

走到半路，楼梯拐角处，忽遇上几只白日劫匪。里娓笑着蹲下和喵喵叫的小毛球打招呼，任凭他们在身上蹭，又从兜里掏出几块奶酪，掰开分赠。等这几只毛球疯完，舔好爪子，他们又忽喇喇跑开，跳到墙角游戏机上继续。

原来两人中断了猫猫们的游戏时光。领头的花猫用左爪敲打游戏机上的大红按钮，刺激冲动的电子音乐渐起。群猫得到信号，在餐桌高的台面上分散，背对着好奇的人类，各就各位。

从赵思琪的角度看去，只能见到六个认真的后脑壳和十二只认真的毛耳朵。啊啊啊，这呆呆的认真模样简直就是犯罪！

音乐节奏渐密，伴随一记重音，游戏台上十八个圆洞中突然弹出一只红色塑胶老鼠，得志猖狂，左顾右盼。啪，守着左上角、湛蓝眼睛的白咪子一爪拍在老鼠脑门，吱吱，老鼠惨叫，缩回洞中。
// 白咪子。。。

又一记重音，两只地鼠同时弹出，这一次是花花和白咪子的儿子雪上狸得分。音乐越来越急，密得像夏日午后的暴雨，猫猫们就这样欢快地玩耍，“Combo! Triple Kill! Perfect! Rampage!”怪音不倦地从机器喇叭迸出。

骄傲自豪的里娓转头对呆立僵硬的赵思琪道，“这台地鼠机是和总送给她男朋友的生日礼物呢。”

// 4/12
和曦的男朋友自然是繁西，在小店街，他是废物的代名词，多亏孟任不舍昼夜的宣传。某年，符合社会人际交往规范的和曦精选了这台打地鼠机作为繁西的生日礼物。繁家人以三分钟热度名世，开始的时候，晚饭一结束，全家人都要排队在地鼠机前兴高采烈，还常常为轮次打架。时间不长，不打架了，也就淡了情绪，地鼠机沦为餐厅摆设。繁娃包饺子时很喜欢顺手把一米五直径的大匾摆在上面，高度又好，位置又巧，撒点面粉，包起饺子来有如神助。直到最近的某夜，起床撒尿，迷迷糊糊的孟任绊了一下，一个猛子把头磕到桌角，连累桌上乱摆的十几个快递箱子哗啦啦乱坠，全叠到昏迷不醒的孟任脑壳上。好不容易爬起的少女大怒，准备发动世界大战，讨伐令无上君王出丑的和曦。然而又想起猫咪咖啡馆多亏了和曦的经济援助，勉强放下，眼珠转转，打起了别的主意。

“你说说繁西是不是废物？”里娓得意之下嘴碎，兴奋地传播真理，“他们家人口多，买烤鸭都是论只的。你也知道南京的规矩，烤鸭都得搭没人要的烤鸭脖。孟姐姐让繁西去买晚上吃，你猜猜怎么着，繁西买回一只鸭子搭了两个脖。大家都笑话他，连苏姬都说，‘西哥哥好呆哦，比苏姬还呆。大家都知道，买一只鸭子搭一个脖子，买半只鸭子搭半个，买四分之一最多搭四分之一，除非一只鸭子长了两个脖子！’孟姐姐就骂他，繁西，你果然是个废物，成天魂不守舍！让你买个鸭子都被没魂的摊主欺负。算了，朕早知道，买烤鸭这样的大事你做不了，做点小事罢，去把那台地鼠机调整到适合猫咪的力道，再安一个大红开始按钮，上面还要画个白白的小爪爪！”

谈笑间，地鼠机进入了最高难度——人来疯。天衣无缝的配合终于出现瑕疵，一只牛奶猫误了一只绿地鼠，恼羞成怒，扑向那地鼠消失的穴洞，探头入内，又咬又挠，想彻底解决鼠患，也就是捣毁猫咪下午休闲的宝物。花花见了，照牛奶猫的脑门就是一爪子，像母猫教育小猫。奶牛猫呜呜两下，缩回一角，舔毛去也。

“老实说，养猫之前，我永远也想不到猫咪居然是这样学习礼仪的。”里娓感叹，“我们这生活了几十只猫，大部分对地鼠机百玩不厌。我们也不加干涉，猫儿们玩闹了几天就自动分成几组，各占据了不同时段分享，他们热爱秩序如此！”

“看诗上说，‘相鼠有皮，人而无仪。’唉，谁想到人常常连猫咪也不如，唉。”

哦，赵思琪明白了。眼前的女子虽比自己大几岁，却是个傻蛋，只会以最大的善意理解猫咪的行为。

// 4/15 
终于下到一楼，赵思琪首先吃了一惊，记得来时还显空阔的一楼此时竟快客满，密密麻麻，坐满了各式各样用发型争奇斗艳的女子。

白葭里娓解答了疑惑，“通常这时间人最多啦。饭店服务员忙完中午场就来店里小坐，逗逗猫咪，把午间的不快抛下，到四点五点再回去上班。”

窗边的好位置已经满了，里娓带着来到中央大道旁的长方桌坐下，又起身去志愿者吧台拿茶点饮料。

赵思琪逛了一圈二楼又说了许多话，精神略显倦怠，正好坐着盘桓一下精力，只是。。。心中有一块总觉不妥。

正纳闷间，两个小姑娘唉呀唉呀跑来这一桌。“不好了，一忙就忘，今天大坏猫多关了半小时，等会儿他会不会生气咬人哪！”

赵思琪见那两个姑娘头戴猫耳头环，知道她们是里娓口中的志愿者，便朝他俩微笑。两个姑娘见了，也忙回以微笑。其中一人抽手到桌面之下，不知扣到什么机关，桌子正中三分之一的桌面缓缓弹起，露出了它想隐藏的真相——钢化玻璃制成的箱子，同时也是桌子的支撑腿。另一位姑娘早已戴上厚皮手套在半透明的箱体内寻找，一会儿捞出只枯黄草色的小猫，放桌上。又下去捞，抱出一只小小花豹，像是赵思琪来时见到的那一只。姑娘最后一次探身，出乎赵思琪的意料，掏出一只硕大无朋的白猫，如此之大，若不是他胖胖的圆脸正在生气，时不时徒劳无功地咬在厚皮手套上，赵思琪一定以为抱出来的是狗狗。

“好吼，好吼。不生气。”姑娘拿出营养膏，桌面上趴着的三只猫激动起来，轮流伸长脖子舔。

“我们把这叫社会化笼。”里娓回来后解释，“猫咪长大的前六个月如果没有充分接触，就会终生恐惧人类。猫猫胆小敏感又总以自我为中心，所以一看到人类走近，总以为目标是他们，于是望风而逃。我们给这个特制的玻璃箱子贴了反射膜，使外面很难看清里面，而对里面的猫咪却是透明的，很像汽车上常贴的那种。这样，大厅中央虽然人来人往，但行人不会注意到桌下箱子里还藏有猫，而箱中的猫因为无可回避，只好慢慢体会出人类不可怕，他们的目的也不在自己的道理。当然，每天训练结束后也要用美食安抚，令他们不至生出反感之心。”

赵思琪又问效果，“大部分猫都有效，但偶尔也会激起公猫的领地意识，四处滋尿，那样的话我们也有别的方法。”

里娓啜饮果汁，又道，“看那只枯黄色小猫，是和总点名领养的，一开始抓来的时候，连自己的影子都怕，现在与我们还有和总很亲近了，所以进笼子巩固，估计再有一两个月她连陌生人都可以淡然处之。那时就会举行毕业典礼，将她风风光光地送到未来家中。你若有空也来参加，很热闹的。”

赵思琪想想，难免奇怪，“既然已经与领养人亲近，又何必多此一举，训练她与陌生人的关系？”

里娓神情一窒，旋又失笑，“在这里多呆一些时日也没有坏处，可以同时学习别的技能。再说，毕业标准有这一条，以后去医院什么的也不容易应激。最重要的，猫咪也许可以活二十年，二十年哪。。。会发生很多事，猫咪能接受陌生人也好。。。你懂的。”

赵思琪不懂，又好像懂了，低头装作用心品味咖啡。

// 4/18 
赵思琪又找到新的话题。“你说的是王可可吧？”白葭里娓笑答，“刚来的时候，所有人和你一样，以为是国家一级保护动物——金钱豹。当然也有不少认成猎豹的。。。按说我小时候还见过两次花豹呢。倒是孟姐姐连这个都懂，一眼认出了它。”

是的，随意一瞥，孟任已把王可可看穿。鼻翼两侧直冲脑门的白线，黑耳背上耀眼的白斑，与花豹形似神不似的文理都促使孟任脱口而出——石虎。

那一日是王可可夫妇结婚周年。小夫妻两个早早开车上路，去邻省宿营。孩子已托付给爷爷奶奶，只带着一对狗，既为安全考虑又防止它们在家寂寞。

傍晚将将开到湖边，疲累欲死。刚还在晕车的两狗却撒欢跑的无影无踪。王可可呼唤了几下，不见踪影，只好算了，专心搭帐篷。抓了几只蚊虫的功夫，孟孟狗忽啦啦一声从路边树林钻出，嘴里叼着一只小小的脏毛球，骄傲地硬塞给女主人看。

王可可被小豹子吓了一跳，脑中想的只是“吃人”野兽。她的丈夫倒还冷静，询问小豹子的由来。孟孟狗神气地领着两个感觉迟钝的人类来到土路另一边，乔乔狗守着的灌木丛。两人检查了一番，并没有发现任何线索，见狗子很兴奋并不慌张，又想起孟孟狗十分擅长寻找被弃幼猫，于是认定手上瘦骨嶙嶙的豹子是一只弃儿。

夫妻俩当即放弃露营。连夜返家路上，王可可想起孟任说的幼猫救护要决：保温和供奶。年轻夫妻的车上倒不缺奶粉、奶瓶、奶嘴，只是略高于人体的温度该如何保持是好？

开车的丈夫没有犹豫，接过小猫，塞进胸口贴肉保存。十个小时的旅程于是收获了妻子的敬意和一身跳蚤。

“石虎，又叫亚洲豹猫，山猫什么的，因为是王可可救来的，孟姐姐因她命名。其实到现在我们也没搞清它究竟是弃婴、母亲遇难留下的块肉，还是孟孟狗乘猫妈妈不在时偷的。”

“很好，走私偷猎国家保护动物，真行啊！”赵思琪默默记录。
// 豹猫其实是三有，赵思琪没查过林业部名录，想当然以为是保护动物。

// 4/19 
“成年的石虎比家猫稍大，其实是本土原生猫种。繁西有一次过来说，最近考古在陕西泉护村出土了一批五千多年前的家猫化石，经国外古生物学家鉴定，发现竟然就是王可可们，而非几千年后才留学到中国的家猫。”

繁西偶然说起这些，虽然他的目的，和平时一样，攻击进化生物学家。

“自从泉护村的猫咪证实为石虎之后，”繁西冷笑着，“进化生物学家立刻又发明了一项真理：驯化的石虎是被几千年后跟随西域和尚进口的中东家猫取代的。换句话说，如果没有中东猫，现在在我们大腿上打呼噜、讨摸摸的还是王可可们。他们不但是科学家，还是历史发明家，真不愧是科学教的神棍。证据，给我证据！什么时候起，科学他妈的成了幻想文学？”
// 这段考虑放到之后和曦和陈皮皮那章写。

里娓接着说，“亚洲豹猫几乎在全国都有分布，有趣的是，家猫也在豹猫的餐桌上。也许这是为什么流浪猫在我国不会重新野化成它们长腿祖先的原因。嘻嘻，这话千万不能让繁西听到。”

赵思琪第一次听说这些，觉得新奇。

“说起来王可可也可怜，虽然曾经遍布中国，上世纪政府还鼓励捕杀，好换取外汇。一年可以出口几十万张毛皮。所以如今它们也已难觅。”里娓总结，“他们的美丽是他们的催命符，在江苏已经成为重点保护动物，希望未来别又成为新的‘华南虎’吧。。。”

// 4/22
吃完点心的王可可正舔手回味，刚那两个女孩子过来，小心翼翼地抱起她，送到不远处的一张桌上，十好几个早已等待的女子强行压抑着面部的潮红，轮流爱抚逗弄。

“那也是王可可社会化训练的一部分。”里娓道，“王可可是纯粹的野生动物 。野性终有一天在她心中轰鸣，所以孟姐姐要求在她成长的每一天都充分接触人类，可以说，花在她身上的精力抵得上十只家猫。”是的，孟任是这世界上仅存的两位精通驯养大型猫科猛兽的专家。她与另一位曾经常年拥有三位数的猛虎，像外国人常说的，她遗忘的比全人类知道的还多。

“孟姐姐还不许我们抓猫咪的后颈，说我们不是猫妈妈，不晓得轻重缓急，老去抓，猫咪长大容易变得怕人，也就是那些人口中的养不熟。”

赵思琪点点头，看来这地方训养野猫确实有一套，等等，为什么感觉如此奇怪，甚至不安？她们做的事情好像与网上爱猫论坛的完全无关。。。

赵思琪看着王可可在隔壁桌上淘气，撒娇，在一个个脑袋上跳来跳去，又趴在姑娘肩上，使劲蹭。那姑娘的表情在说话，诉说着爪牙的尖利。赵思琪心说，如果我处于她的位子，也一定像她现在这样傻笑，不敢随便摆动躲避，免得吓到猫咪。

正看得入神，白葭里娓拉了拉她的手臂，指着地上。原来那只大的超乎梦幻的纯白猫咪起身，正往后庭踱去。

// 4/23
前庭还像正常的咖啡馆，后庭就是猫咪的丛林。猫窝猫架猫柱随处都有，五花八门。咚咚咚，三只小猫从两人头顶跑过，赵思琪昂首，原来空中也布满了梁柱，供猫咪高来高去，偷窥下方闯入领地的无知人类。
// 猫的丛林完全不会写，要大修

“这里才是猫咪的世界，想看得来这儿。”里娓自矜地说，“我们这里只有猫咪想找人类玩耍时才会到前面去，这里没有强迫他们出来娱宾的。”
//好难，不是猫的专家，写这章时时卡词

于是二人去看那些心情正好，愿意呆在地面的猫，比如一路跟踪，里娓口中的‘臭繁西’。

“臭繁西每天最重要的工作就是巡视领地。”
“就像现在这样。”里娓笑嬉嬉地咬耳朵，“有时候，我觉得他才是这里的主人，比我们还关心这片土地。”

大白猫左闻右嗅，四处玩耍。一路上的公猫纷纷让路，可母猫并不怕他，时时挥动爪子作势要打，臭繁西嬉皮笑脸地跳开，继续游荡。

大坏猫逛完地面一层，没有发现异常和敌人，老婆们也像往常一样与自己打情骂俏，你侬我侬，不由得朕心甚慰。走到墙角，抬头、凝踞、猛然窜起，前爪在墙面上一蹭，借力转身，直接扒上空中两米多高的猫梁。“好，，，好厉害！”云养猫的赵思琪平生第一次见识猫咪的二段跳，心旌荡漾。

然而上了猫梁的大坏猫变了一个猫，又凶又狠，对着梁下两个跟踪狂哈气嘶嘶、亮爪、吡牙，在想像中扯开了她俩白嫩的喉咙，侧头吸吮新鲜喷涌的热血。

就在此时，一只母猫走出猫树中央的猫窝，叫唤起来，寻找自己的姐妹，幼崽的阿姨。

大坏猫听到，立时止住示威，从墙边溜缝落到地上，不管那母猫，先窜到里娓两腿间乱蹭，要摸摸。

“嗷~~~”嗷呜的里娓完全丧失了思考能力，如果她曾经拥有的话。双膝跪地，两臂延揽大坏猫入怀，在他耳边喃喃，“坏宝贝，坏宝贝。你刚才没认出我吗？那么凶！你都不晓得我有多爱你。”

大坏猫任由里娓亲吻抚摸，终至无可忍耐，嗖的窜出，去找呼唤的母猫。

// 4/26
母猫原也是南京大学流浪着的主人，因为怀孕时后腿骨折才被紧急带回，未久。在这里她养好伤，生下娃，还遇到阔别数年的母亲和妹妹。一家人以这种怪异的方式团圆，如果流浪猫也有团圆一词的话。

四个娃，有橘有白有狸有花，正是最淘气的年龄。连续带娃一个多月的母猫也不堪其忧，出来呼唤自己的妹妹，好去进食进水，眯盹一会儿。然而猫阿姨、猫外婆现在统统失踪，不知道是躲到哪里睡觉，还是跑前厅玩去了。

呜呜叫唤半天没有回音，猫妈妈有点沮丧，这时竟看到自己的老相好翘着尾巴巴巴地赶过来。

大怒！老娘都这样了，还想过来交配？？！！大坏猫吓得小了两个身姿，伏在地面，趴了双耳，在母猫咆哮的间隙小声回话。什么？你来带孩子？母猫疑惑了，然而疲倦战胜了她，最终大坏猫如愿以偿。

里娓见此，掏出手机喊人。两个女孩子扛着各种摄像设备匆匆赶来。毕竟临时起意，人手不足，里娓走去举起一块补光板相助。赵思琪也去拾起一块，站在另一边。里娓见了，忙感激地冲她一笑，赵思琪看似害羞，转过头去，对着自己诡异地咧嘴笑了。

妈妈带孩子千妥万妥，一切安排的井井有条，孩子们干净健康，毛光瓦亮，活泼天真。爸爸带孩子。。。手忙脚乱，东倒西歪，孩子也凄凄惨惨、乌眉皂目、灰头土脸、不成猴子耳朵。母猫在的时候，幼猫互相偎依，相亲相爱。母猫才动身，块头最大的老大老二立刻为了领导地位施展喵喵拳，打得不可开交。老三最老实，呆呆趴着，见无猫注意，偷偷往哥哥尾巴上咬一口，让他们以为遭到对手偷袭，从而战火更炽。最小是只美女，这时候怕起来，啾啾哀鸣，要找妈妈。于是四只小猫一起颠颠的爬出巢穴，哇哇大哭，去找妈妈。
// 这章结构简单，却常有无力驾驭之感，是因为愤怒么？

// 2018/9/2 晚上又忍不住去白咪子那里，一年过去了，发生了很多事，但我忘了和她说。因我想摘点石蒜给她，可附近没有。我想，也许今年的气候与去年不同。不知道是开过了，还是未开。突然想起，去年这里也没有石蒜，我也是在离这里十几，二十米的小树林另一端摘的。是啊，她倒下的地方并没有这种毒物。于是已经下的结论又动摇了。

// 9/6 前些时候特别苦恼，总觉得在写场景切换时，用的是电视剧的手法，可能从小看电视，身染。昨天偶然重读左传，则如此手法历历在目，由来已久矣。

// 摔角不知放哪里。。。

// 孟任最后一节发言少了中年出任公司CEO那一小段