= 猫咪咖啡馆

:docdate: 2018年/2月/15日

“猫咪咖啡馆？猫咪咖啡馆？在哪呢？”赵思琪攥着杂志，立在路的尽头，东张西望。不会地址印错了吧？
// 远处在刷墙，赵思琪没想到这么简单一弄，还挺有味道。

又见街对面有两个丫头在跳皮筋，丢沙包，赵思琪望了一会儿，呆呆吐出一口气，一时间仿佛与儿时的自己在这旧巷斜阳里不期而遇。只可惜那时的自己早已遗失，连模糊的影子都无可寻觅。

右手遮住太阳，笑着穿过道路，走向两个小娃儿，“嗨！你们两个！知道猫咪咖啡馆怎么走么？”

“不晓得！孟姐姐说了，问人要讲礼貌，方方最乖的。”胖丫头扭过去，不看赵思琪，弯腰去拾毽子。

扎小辫的胖丫头抱着皮球，迎了来，“圆圆知道。孟姐姐说回答别人也要礼貌的。姐姐你刚才站的地方就是，只不过咖啡馆在院子里，被树挡了。姐姐还请别大声喊，这时间孟姐姐多半在午睡哩。”

赵思琪好笑，我还要听两个矮冬瓜教训？回头望望来处，果然院子里有个招牌，一行字透出盘屈XX的枝叶。“爪白白咖啡馆？”赵思琪多少疑惑。

方方也走了来，“孟姐姐说了，一个东西有两个名字很正常。就像方方是个乖孩子，又叫方方一样。爪白白咖啡馆就是猫咪咖啡馆，猫咪咖啡馆也叫爪白白。不信看招牌上还有许许多白小爪子呢。”

笑嘻嘻谢过两个丫头，赵思琪咚咚咚跑过街，穿过院门，边跑边想，“此间人为什么全都傻傻的？”

// 3/17
后来她在的店铺倒闭，像每天路边大多数小店一样。经同乡介绍，去了家私立幼儿园打杂，就此别离了小店街。好容易逃离魔窑，冥顽不灵的她仍把孟任平日的胡言乱语当成真理。想起孟任成天挂在嘴边当招牌的**学**与**日新**，也硬着头皮学起了幼儿教育。两年之后，居然混到了幼教资格证，转成了正经的**执证**教师。

谁都知道，中国人最舍得在孩子身上花钱。她的幼儿园赶上了城市化的浪潮，新近又弄来一笔巨额投资，所以像任何企业一样决心大大扩张。十家新建的幼儿园就有一家在小店街，集团还专门任命李梅出任园长，自然是希望和小店街黑社会大头头孟任搞好关系，至少不开罪她。

然而李梅一切都好，就是缺乏商人的灵活/油滑。她左手一本幼儿园规章制度，右手一本《幼儿教育》，做任何事情，都要先以查黄历请菩萨式的虔诚在书中寻找依据。别说与书上写的有一个字的差别，就算差一个标点符号，她也必然不行。与她龃龉的男子是小店街上新疆餐厅新聘来的青海大厨，小娃儿长到可以送幼儿园的年龄，本想着就此可以轻松一半，哪知一头撞上李梅的死脑筋，生疼。

已经很不耐烦的孟任，抓住这个空隙，对二人扬唇，“朕也听了半天了。”装出一付剧烈思考、脑海冒泡的模样，良久，“大厨也不足，李梅也过了，都有错。”

见二人呆呆凝望自己，孟任心底得意，得意成抓耳挠腮的猴子王，“先说你，宗教局的人也说，无论小学大学，上学的问题都可以为你出面，就是幼儿园没办法，可见李梅他们没有违反政策嘛。”

又指李梅，“你的死脑筋又犯了，比牛还犟。大厨又不要你专门为他家孩子开餐厅，他自己每天送饭，你为何就不肯行个方便呢？”

李梅急了，“不是不肯行个方便。”把右手的《幼儿教育》摊开，哗哗翻到一页，“孟姐姐请看，这里写着的，写着的！‘幼儿在园中必须按规定吃园餐，这是他们人生第一次参加集体活动，可以潜移默化地培养他们尊重社会、学校以及公众的行为规范的意识，并且纠正由于家长溺爱形成的挑食的坏习惯和唯我独尊的小皇帝、小公主思想。’我们园的规章制度也禁止家长送饭，我马上翻给你看。”
// 有意把引文写成啰嗦的长句。

“够了够了，”孟任摆摆小手，自认很潇洒，“朕怕你根本不懂什么叫民族宗教吧。”

李梅怔住，出身寒鄙的她见过的第一位回族人就是眼前的大厨，还是从他的口中第一次听到**伊斯兰法**四个字。等搞清楚这四字怎么写，她不免在背后偷偷对着先知发出许多亵渎的啧啧声。
//塙有如此漏人，从小到大不知道民族宗教的。

// 3/18 得知李敖去世，想有点感伤又不知在何处，唉

“这样说吧，信道教的不吃狗肉，并非他们挑食，或者怀疑幼儿园的菜肉不洁，来源不安全，而是信仰，你懂了吧？”

没有，完全没有，李梅并不认识任何道士，更没听说道士不能吃狗肉的，所以看上去更加呆头了。

“那你总有亲戚信佛吧？平时吃素斋的。”

这个。。。李梅勉强懂了，她的外婆在生命的最后岁月皈依了佛教，丝毫荦腥不沾。外人看着都觉得不忍，家人更是忧心忡忡。所以，，，李梅从小红旗下长大的唯物主义少女又把食物禁忌理解成**封建迷信**，害人不浅！

呃，没想到讲道理起了反作用，孟任好气好笑，只能求诸擅长的暴力。把电脑屏转动90度，一手揪住李梅的脑袋按桌上，一手在亚马逊图书信息页上指指点点，先吹嘘自己，“看看，像朕这般伟大的君王也懂得学习日新，‘苟日新，日日新，又日新’。哪想到你这小学生倒不学习的，天天捧着十几年前出版的第三版旧书当宝贝，你看看这里，这书去年已经出到第六版，第六版序言有一句，‘除了上述变化，本次修订还添加了民族宗教和少儿心理学内容，这符合社会主义初级阶段生产力与生产关系辩证统一的。。。吧啦吧啦，哼哼哈哈，阿弥托佛嘛咪嘛咪哄，’见鬼，全是咒语？总之，大意你反正了解了，记住，回去第一次事就是去买一本第六版更新一下你的死脑筋，记住了没？”为了帮助李梅回忆，孟任又咚咚咚在她脑壳上凿了三个暴栗，才放手。

李梅早被孟任锤惯，逆来顺受，这时只好委委屈屈先答应下来，但立刻提出了新问题，如果别的家长得知，哪个孩子没有特殊情况，人人要给孩子送饭，那该如何应对？

谁料这问题竟惹了一位未来的英雌排空出世。站在白葭里娓身畔，红衣少女赵思琪早已不耐，天哪，这都什么人啊！不过一件芝麻绿豆大的小事，这伙人唧唧歪歪、唧唧歪歪、唧唧歪歪个不停！冲动之下，脱口而出，“换个说法不就好了？不然还说成开了个专供穆斯林的餐厅，别提家长送饭，全推到宗教局身上，就说他们规定必须要有的。给所有家长两个选项，要么吃园餐，要么吃清真饭。到时候不管几个人，都让大厨按人头送来好了。”
// 排空出世那里还要修饰。赵思琪固然是未来英雌，但她在本书里只零散出现，并非主要人物，如白葭里娓。

李梅听了，缓缓点头琢磨，不提家长送饭，其他家长也不会想到送，加上幼儿园的孩子们也没有奇奇怪怪的信仰，比如佛教，不怕有人乘机要幼儿园再添个素菜馆子，如此看来，这办法也许真的可行？

// 3/19 昨天未见的，今日见了，不见李生久，佯狂真可哀

众人观察孟任的神色，孟任正色道，“又何必骗人？满腹心事，伪饰出来的言辞真以为能欺瞒世人？小店街之人虽笨，可也不都是傻子！这样吧，李梅你明天再来一趟，朕为你写张告示，把事情本末由来一一详明，你贴在大门上，晓谕众生。还有不理解的，让他来找朕。还有，你书上只提到尚同，只想到集体意识，可人生而不同，已不仅仅是宗教；有些孩子体质特殊，吃点豆油都过敏，你们也逼着非要吃定餐？”挥挥手，遣走了李梅。

竟见未被采纳，对于只有十六岁的赵思琪来说本是寻常事，毕竟年龄不到，就像还未长出鬃毛的公狮子，没有哪个母狮会将他放在心上。然而这一次她着实羞红了脸，因为无知的围观群众听了眼前和自己一般大的小女孩胡说，个个露出信服的表情，仿佛听到的是黄钟大吕，金声而玉振。

“啊呸，好恶心。被我抢先了，这小毛丫头才特意换一种说法出风头，保持她在众人眼中的地位。如果一开始我用她的说法，她一定换我的，为了不同而不同，哼哼，就有这种人。”

大厨见事情解决，喜上眉梢，正待告辞，却低估了孟任。“你也知道，李梅收你家娃是出于善意，许多人劝李梅，为你说话也是一份善意。你的孩子现在信仰你们的圣教，因他生来就是你的孩子。等他长成，如果有别的选择，别的信仰，也请你尊重至少不干涉，看在今日这许许多多在场人士善意的份上。”

大厨呆了，全然想不到还有这么一出，嗫嚅半天，像坏了的闹钟，身子乱颤，戏味十足就是发不出一丝声响。

有个女孩见孟任要打发他，忙窜出来，咬着耳朵密报。愤怒的火星迸发，炸雷在寥廓的屋㝢内来回激荡，

“什么？打孩子？？！！你别走，你给朕讲清楚，为什么事打孩子？”

“小孩子不听话就该打？你还占理了？你那么占理，为什么把他拖到后面的车棚偷偷打？不敢在路边光明正大的‘教育’？要不是你下手太狠，车棚那边的声音也不会给姑娘们听到！”

“下次小孩子不听话，你把他送这里。你不会教育，朕这里最多有耐心的阿姨。你再敢打孩子，别的朕做不到，在小店街上你只怕混不下去！”

见大厨服软，孟任颜色略霁，“对了，你老婆怎么回事？每天在你店里打杂、炒菜、收银，托人带过几次话，就是从来不肯登朕的大门？是看不起这里的女孩子还是想学离群索居的商？商也悔于失群，她难道还贤于商？你记得带话，不管疲倦还是XX，都可以来这里休憩，嬉游。就算龙生九种，个个有别。这里人多，必有她能合得来的，总好过天天守着你。贵教的声望被一些极端份子拖累，你们又不出来交际，在旁人眼里，难免觉得你们神神秘秘，甚至鬼鬼祟祟。就算为了贵教，她也应该来这边教育出身穷乡僻壤、无知愚昧，连伊斯兰三个字都没听说过的女孩子。她不肯来，莫非是对贵教信心不坚的缘故？”

大厨失魂落魄地走了，得一而失二，总算见识到小店街统治者真正的颜色。