= 猫咪咖啡馆

:docdate: 2018年/2月/15日

“猫咪咖啡馆？猫咪咖啡馆？在哪呢？”赵思琪攥着杂志，立在路的尽头，东张西望。不会地址印错了吧？
// 远处在刷墙，赵思琪没想到这么简单一弄，还挺有味道。

又见街对面有两个丫头在跳皮筋，丢沙包，赵思琪望了一会儿，呆呆吐出一口气，一时间仿佛与儿时的自己在这旧巷斜阳里不期而遇。只可惜那时的自己早已遗失，连模糊的影子都无可寻觅。

右手遮住太阳，笑着穿过道路，走向两个小娃儿，“嗨！你们两个！知道猫咪咖啡馆怎么走么？”

“不晓得！孟姐姐说了，问人要讲礼貌，方方最乖的。”胖丫头扭过去，不看赵思琪，弯腰去拾毽子。

扎小辫的胖丫头抱着皮球，迎了来，“圆圆知道。孟姐姐说回答别人也要礼貌的。姐姐你刚才站的地方就是，只不过咖啡馆在院子里，被树挡了。姐姐还请别大声喊，这时间孟姐姐多半在午睡哩。”

赵思琪好笑，我还要听两个矮冬瓜教训？回头望望来处，果然院子里有个招牌，一行字透出盘屈XX的枝叶。“爪白白咖啡馆？”赵思琪多少疑惑。

方方也走了来，“孟姐姐说了，一个东西有两个名字很正常。就像方方是个乖孩子，又叫方方一样。爪白白咖啡馆就是猫咪咖啡馆，猫咪咖啡馆也叫爪白白。不信看招牌上还有许许多白小爪子呢。”

笑嘻嘻谢过两个丫头，赵思琪咚咚咚跑过街，穿过院门，边跑边想，“此间人为什么全都傻傻的？”

3/17
后来她在的店铺倒闭，像每天路边大多数小店一样。经同乡介绍，去了家私立幼儿园打杂，就此别离了小店街。好容易逃离魔窑，冥顽不灵的她仍把孟任平日的胡言乱语当成真理。想起孟任成天挂在嘴边当招牌的**学**与**日新**，也硬着头皮学起了幼儿教育。两年之后，居然混到了幼教资格证，转成了正经的**执证**教师。

谁都知道，中国人最舍得在孩子身上花钱，她的幼儿园赶上了城市化的浪潮，新近又弄了一笔巨额投资。所以像任何企业，决心大大扩张。十家新建幼儿园中就有一家在小店街，集团又专门任命李梅出任园长，自然是希望和小店街黑社会大头头孟任搞好关系，至少不开罪她。

然而李梅一切都好，就是缺乏商人的灵活/油滑。她左手一本幼儿园规章制度，右手一本《幼儿教育》，做任何事情，都要先以查黄历请菩萨式的虔诚在书中寻找依据。别说与书上写的有一个字的差别，就算差一个标点符号，她也必然不行。与她龃龉的男子是小店街上新疆餐厅新聘来的青海大厨，小娃儿长到可以送幼儿园的年龄，本想着就此可以轻松一半，哪知一头撞上李梅的死脑筋，生疼。

已经很不耐烦的孟任，抓住这个空隙，对二人扬唇，“朕也听了半天了。”装出一付剧烈思考、脑海冒泡的模样，良久，“大厨也不足，李梅也过了，都有错。”

见二人呆呆凝望自己，孟任心底得意，得意成抓耳挠腮的猴子王，“先说你，宗教局的人也说，无论小学大学，上学的问题都可以为你出面，就是幼儿园没办法，可见李梅他们没有违反政策嘛。”

又指李梅，“你的死脑筋又犯了，比牛还犟。大厨又不要你专门为他家孩子开餐厅，他自己每天送饭，你为何就不肯行个方便呢？”

李梅急了，“不是不肯行个方便。”把右手的《幼儿教育》摊开，哗哗翻到一页，“孟姐姐请看，这里写着的，写着的！‘幼儿在园中必须按规定吃园餐，这是他们人生第一次参加集体活动，可以潜移默化地培养他们尊重社会、学校以及公众的行为规范的意识，并且纠正由于家长溺爱形成的挑食的坏习惯和唯我独尊的小皇帝、小公主思想。’我们园的规章制度也禁止家长送饭，我马上翻给你看。”
// 有意把引文写成啰嗦的长句。

“够了够了，”孟任摆摆小手，自认很潇洒，“朕怕你根本不懂什么叫民族宗教吧。”

李梅怔住，出身寒鄙的她见过的第一位回族人就是眼前的大厨，而且是从他的口中第一次听到**伊斯兰法**四个字。等搞清楚这四个字怎么写，她不免在背后偷偷对着先知发出许多亵渎的啧啧声。
//塙有如此漏人，从小到大不知道民族宗教的。

